### PR TITLE
biobloomtools 2.1.1

### PR DESCRIPTION
**Pull request by jonchang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jonchang** [comment]
macOS - invalid implicit conversion

```
In file included from SeqEval.cpp:1:
../Common/SeqEval.h: In function 'bool SeqEval::evalSingle(const string&, const BloomFilter&, double, const BloomFilter*)':
../Common/SeqEval.h:59:23: error: invalid conversion from 'const uint64_t*' {aka 'const long long unsigned int*'} to 'const size_t*' {aka 'const long unsigned int*'} [-fpermissive]
   if (filter.contains(*itr)) {
                       ^~~~
In file included from ../Common/SeqEval.h:19,
                 from SeqEval.cpp:1:
../btl_bloomfilter/BloomFilter.hpp:216:29: note:   initializing argument 1 of 'bool BloomFilter::contains(const size_t*) const'
  bool contains(const size_t precomputed[]) const {
                ~~~~~~~~~~~~~^~~~~~~~~~~~~
```

Linux - can't find google/dense_map

```
In file included from tree.cc:1:0:
tree.hh:8:33: fatal error: google/dense_hash_map: No such file or directory
compilation terminated.
```

**Comment by sjackman** [comment]
@justinchu Any thoughts on these two errors when building biobloomtools?

**Comment by JustinChu** [comment]
The last error is a bit weird, but the first one is [known](https://github.com/bcgsc/biobloom/issues/30) that can be easily fixed by changing some types or casting some values, but I need to setup an environment to reproduce so I haven't gotten around to fixing.

The last error is strange to be because `google/dense_hash_map` is imported the same way in other files so long google sparse hash is installed correctly I don't know why this error is occurring.

**Comment by sjackman** [comment]
@jonchang Try adding…
```ruby
depends_on "google-sparsehash" => :build
```

**Comment by jonchang** [comment]
Good catch, weird that it doesn't affect macOS.

**Pull request closed without merging**
