### PR TITLE
readseq 2.1.30_1

### PR DESCRIPTION
**Pull request by tseemann**
I want this bottled as the .jar file often fails to download from the home page.

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman why does CIRCLE macos not ever read `http` urls?    (as opposed to `https`)

```
==> FAILED
==> Fetching readseq from brewsci/bio
==> Downloading http://iubio.bio.indiana.edu/soft/molbio/readseq/java/readseq.jar
curl: (52) Empty reply from server
==> Retrying download
==> Downloading http://iubio.bio.indiana.edu/soft/molbio/readseq/java/readseq.jar
curl: (52) Empty reply from server
Error: Failed to download resource "readseq"
Download failed: http://iubio.bio.indiana.edu/soft/molbio/readseq/java/readseq.jar
```

**Comment by sjackman** [comment]
I don't know of any fix for this issue. Sorry. `insecure` applies only to `https`. You could ssh into CircleCI and try to troubleshoot the problem interactively. Or you could mirror the source file on a different server, like Bintray or GitHub.

**Comment by sjackman** [comment]
You could mirror the sources elsewhere (or find a mirror) and download from there.

**Comment by sjackman** [comment]
The web site hosting the homepage and JAR file are not responding. I've opened PR https://github.com/brewsci/homebrew-bio/pull/596 to remove `readseq`.

**Pull request closed without merging**
