### PR TITLE
star-aligner 2.7.5b

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
```
g++-5 -c   -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE="Fri Jul 17 23:47:29 UTC 2020 :/tmp/star-aligner-20200717-3472-17gwz0w/STAR-2.7.5a/source"' -pipe -Wall -Wextra SuperTranscriptome.cpp
SuperTranscriptome.cpp: In member function ‘void SuperTranscriptome::load(char*, std::vector<long long unsigned int>&, std::vector<long long unsigned int>&)’:
SuperTranscriptome.cpp:51:41: error: cannot convert ‘std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}’ to ‘bool’ in initialization
         bool inGood = (superTrSJ >> sutr);
```
https://github.com/brewsci/homebrew-bio/pull/1098/checks?check_run_id=883794222

Report the issue upstream I suppose. The following untested patch may work.

```
-bool inGood = (superTrSJ >> sutr);
+bool inGood = !(superTrSJ >> sutr).fail();
```

See https://en.cppreference.com/w/cpp/io/basic_ios/operator_bool

**Comment by sjackman** [comment]
On macOS
```
g++-10 -c   -O3 -std=c++11 -fopenmp -D'COMPILATION_TIME_PLACE="Fri Jul 17 23:49:11 UTC 2020 :/private/tmp/star-aligner-20200717-15994-8zq8u8/STAR-2.7.5a/source"' -D'COMPILE_FOR_MAC' -pipe -Wall -Wextra Genome_genomeLoad.cpp
Genome_genomeLoad.cpp: In member function 'void Genome::genomeLoad()':
Genome_genomeLoad.cpp:152:35: error: 'log' was not declared in this scope; did you mean 'long'?
  152 |         GstrandBit = (uint) floor(log(nGenome)/log(2))+1;
      |                                   ^~~
      |                                   long
```

**Comment by SeekingMeaning** [comment]
https://github.com/brewsci/homebrew-bio/runs/947644744?check_suite_focus=true#step:4:284

```
clang: clangerror: : unsupported option '-static-libgcc'
```

**Comment by sjackman** [comment]
`clang: clangerror: : unsupported option '-static-libgcc'`

It looks to me like STAR expects to be built with GCC and current fails to build with Clang. I can't say how much work it would be to get STAR to build with Clang. You could report this error upstream if you wished.

**Pull request merged**
