### PR TITLE
seqan3 3.0.0 (new formula)

### PR DESCRIPTION
**Pull request by rrahn**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

This adds a new formula for SeqAn3 3.0.0 version the new major release of the modern C++ library for sequence analysis based on C++17/20. This is a new formula as SeqAn and SeqAn3 can live along next to each other.

### CODE REVIEW

**Comment by rrahn** [comment]
Hi there, anyone looking into this PR? Should I ping someone directly? Please, help me out if I did something wrong in the contribution process. Thanks a lot.

**Comment by sjackman** [comment]
Hi, @rrahn. Thank you for your contribution Brewsci/bio. I'm terribly sorry for the extended delay in my reply. I haven't had much time for open source work this fall.

Please rename `seqan.rb` to `seqan@2.rb` and rename this formula to `seqan@3.rb`, and create a symlink named `seqan` (note no `.rb` extenssion) in a newly-created `Aliases` folder.

```bash
mkdir Aliases
ln -s ../Formula/seqan@3.rb Aliases/seqan
git add Aliases/seqan
```

**Comment by rrahn** [comment]
Hi @sjackman now I am terribly sorry for the long delay, but we were quite busy with the latest release :D. I was wondering how the symlink works for the users. The point is that seqan3 is not backward compatible with SeqAn 2. So I am afraid that software would break with the new update when they link against SeqAn but get SeqAn3 instead of SeqAn2. Both of them can coexists though. Many thanks for your help

**Comment by sjackman** [comment]
Try the above suggestions naming the formulae, and then `brew install seqan@2 seqan@3` to install both formulae, and see how the files exist on disk. It should all work fine if they can coexist as you say.

**Comment by rrahn** [comment]
@sjackman I applied the changes and was able to install both libraries in parallel. 
We have already a new version of the library. Should I make this in another PR or directly apply the changes to this PR?

**Comment by rrahn** [comment]
test bot error seems unrelated?

**Comment by sjackman** [comment]
> We have already a new version of the library. Should I make this in another PR or directly apply the changes to this PR?

You can submit that new version in a new PR after merging this one.

**Comment by sjackman** [comment]
Merged in commit 2eae073. Thank you! 🌟

**Pull request closed without merging**
