### PR TITLE
Subread 1.6.4

### PR DESCRIPTION
**Pull request by czhu**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----
https homepage isn't available

### CODE REVIEW

**Comment by sjackman** [comment]
```
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz.so.1
```
https://circleci.com/gh/brewsci/homebrew-bio/5722

Add…
```ruby
depends_on "zlib" unless OS.mac?
```

**Comment by sjackman** [comment]
```
brewsci/bio/subread:
  * C: 4: col 3: http://subread.sourceforge.net should be `https://subread.sourceforge.io/`
```
https://circleci.com/gh/brewsci/homebrew-bio/5722

http://subread.sourceforge.net works but https://subread.sourceforge.net does not work. I'll look into it.

**Comment by sjackman** [comment]
As a hack workaround, you can set the homepage to something else, like the URL of the paper, until I'm able to sort out this issue.

**Comment by czhu** [comment]
Tx! Implemented all suggestions.

**Comment by sjackman** [comment]
Merged. Thanks again for your contributions to Brewsci/bio, Chenchen! 🌟

**Pull request closed without merging**
