### PR TITLE
edirect 8.50

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Configuring Net-SSLeay-1.85 ... OK
Building and testing Net-SSLeay-1.85 ... ! Installing Net::SSLeay failed. See /private/tmp/edirect-20180420-7424-11qb2e2/edirect/.brew_home/.cpanm/work/1524213458.7432/build.log for details. Retry with --force to force install it.
FAIL
```

**Comment by tseemann** [comment]
```
Building and testing WWW-RobotRules-6.02 ... OK
Successfully installed WWW-RobotRules-6.02
! Installing the dependencies failed: Module 'Net::HTTP' is not installed
! Bailing out the installation for libwww-perl-6.33.
! Installing the dependencies failed: Module 'Net::HTTPS' is not installed, Module 'LWP::UserAgent' is not installed
! Bailing out the installation for LWP-Protocol-https-6.07.
21 distributions installed
```

**Comment by sjackman** [comment]
```
Installing Net::HTTPS failed. See /private/tmp/edirect-20180420-7480-12ajbah/edirect/.brew_home/.cpanm/work/1524290432.7488/build.log for details. Retry with --force to force install it.
```
If you can reproduce this issue on the `linuxbrew/linuxbrew` Docker image, then you can read that `build.log` file.

**Comment by suujia** [comment]
please see #279 for part 2 of edirect migrate/update

**Comment by sjackman** [comment]
Shh stale bot

**Comment by tseemann** [comment]
Closing due to #279 effort.

**Pull request closed without merging**
