### PR TITLE
raxml-ng 0.6.0

### PR DESCRIPTION
**Pull request by jonchang**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by jonchang** [comment]
* include new patch to fix builds

**Comment by jonchang** [comment]
I think there's a bug somewhere. Building from bottle `-march=core2` blows up during `brew test` on my local machine and CI but building from source `-march=native` doesn't. I don't have time to check it out this week but I'll see about opening an issue against upstream maybe.

**Comment by sjackman** [comment]
I had a similar issue with OpenMPI recently here: https://github.com/Linuxbrew/homebrew-core/pull/8112
The fix was to clear `HOMEBREW_OPTFLAGS`.
```ruby
    ENV["HOMEBREW_OPTFLAGS"] = "" if !OS.mac? && build.bottle?
```
See https://github.com/Linuxbrew/homebrew-core/blob/05357a5229c14fdbe0c71a78f3dad72fdad15583/Formula/open-mpi.rb#L38

Better though would be `ENV["HOMEBREW_OPTFLAGS"] = "-march=sandybridge"` (or some architecture). 
See https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures

**Comment by jonchang** [comment]
Waiting on a new release from upstream.

**Pull request closed without merging**
