### PR TITLE
bam2wig: import from brewsci/science

### PR DESCRIPTION
**Pull request by suujia**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----
```
==> Downloading http://www.epigenomes.ca/resources/BAM2WIG/BAM2WIG-1.0.0.jar
Error: No such file or directory - zipinfo
```
and update to version 1.5

### CODE REVIEW

**Comment by suujia** [comment]
See: https://github.com/brewsci/homebrew-science/pull/205

**Comment by suujia** [comment]
Oops, I see. 

https://hub.docker.com/r/bcgsc/orca-2/builds/bwopbqqkfswmwdqsi5vv8ha/
I rebuilt orca again and it gave error message: 
```
No such file or directory - zipinfo
```
I got this message when building on singularity hub as well.

**Comment by sjackman** [comment]
```
==> Installing bam2wig from brewsci/science
==> Downloading http://www.epigenomes.ca/resources/BAM2WIG/BAM2WIG-1.0.0.jar
Error: No such file or directory - zipinfo
```
https://hub.docker.com/r/bcgsc/orca-2/builds/bwopbqqkfswmwdqsi5vv8ha

The tool `zipinfo` is provided by the package `unzip`, which is installed in `orca-0`:
https://github.com/bcgsc/orca/blob/e5979ad9ff552073b180bc35612d333d3be85477/orca-0/Dockerfile#L37

So strange that you're getting this error. I'm also not able to reproduce this error in the `linuxbrew/linuxbrew` image, where `brew install brewsci/science/bam2wig` succeeds. I'm fine with removing `bam2wig` from ORCA if this error persists. The same functionality is provided by `bedtools`.

**Comment by sjackman** [comment]
I am able to reproduce this error in the `linuxbrew/linuxbrew` Docker image!
```
brew install brewsci/science/bam2wig
==> Installing brewsci/science/bam2wig
==> Downloading http://www.epigenomes.ca/resources/BAM2WIG/BAM2WIG-1.0.0.jar
######################################################################## 100.0%
Error: No such file or directory - zipinfo
```

**Comment by sjackman** [comment]
This issue may hopefully be resolved with Linuxbrew/brew 1.7.2, which I'm working on now.

**Comment by sjackman** [comment]
Closing this PR, as the error being addressed is due to a bug in Linuxbrew/brew, caused by attempting to inspect a JAR file using `zipinfo` (provided by `unzip`) when that program is not available.

**Pull request closed without merging**
