### PR TITLE
kssd 1.0

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
gcc -std=gnu11 -Wall -Wno-unused-result -O3 -ggdb -lz -fopenmp  *.c -o ./kssd -lm
In file included from co2mco.h:17,
                 from co2mco.c:15:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from command_dist.h:17,
                 from command_dist.c:15:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from command_dist_wrapper.h:17,
                 from command_dist_wrapper.c:15:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from command_reverse.h:17,
                 from command_reverse.c:15:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from command_shuffle.c:15:
command_shuffle.h:35:11: fatal error: argp.h: No such file or directory
   35 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from global_basic.c:15:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from global_wrapper.c:16:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from iseq2comem.h:17,
                 from iseq2comem.c:15:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
In file included from kssd.1.0.c:19:
global_basic.h:53:11: fatal error: argp.h: No such file or directory
   53 |  #include <argp.h>
      |           ^~~~~~~~
compilation terminated.
make: *** [all] Error 1
```

**Comment by jonchang** [comment]
Probably needs `argp-standalone`

**Comment by tseemann** [comment]
```
==> brew linkage --test brewsci/bio/kssd

==> brew install --only-dependencies --include-test brewsci/bio/kssd

==> brew test brewsci/bio/kssd --verbose

==> brew uninstall --force zlib
mv: cannot stat 'brew-test-bot.xml': No such file or directory
Exited with code 1
```

**Comment by tseemann** [comment]
I need to add `argp-standalone` include dir to the compilation somehow.

```
compilation terminated.
global_basic.c:26:10: fatal error: sys/sysinfo.h: No such file or directory
   26 | #include <sys/sysinfo.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
global_wrapper.c:27:10: fatal error: argz.h: No such file or directory
   27 | #include <argz.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [all] Error 1
```

**Pull request closed without merging**
