### PR TITLE
salmon 0.10.2

### PR DESCRIPTION
**Pull request by sjackman**
See https://github.com/COMBINE-lab/salmon/releases/tag/v0.10.2

### CODE REVIEW

**Comment by sjackman** [comment]
CirlceCI on Linux
```
cd /tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/src && /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5   -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/include -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/include/eigen3 -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/external -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/external/cereal/include -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/external/install/include -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/external/install/include/bwa -I/home/linuxbrew/.linuxbrew/include -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/external/install/include/rapmap -I/tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/external/install/include/rapmap/digestpp  -pthread -ftree-vectorize -funroll-loops -fPIC -fomit-frame-pointer -O3 -DRAPMAP_SALMON_SUPPORT -DHAVE_ANSI_TERM -DHAVE_SSTREAM -Wall -Wno-unknown-pragmas -Wno-reorder -Wno-unused-variable -std=c++11 -Wreturn-type -Werror=return-type -Wno-unused-function -Wno-unused-local-typedef -static-libstdc++  -Wno-unused-local-typedefs -pthread -ftree-vectorize -funroll-loops -fPIC -fomit-frame-pointer -O3 -DRAPMAP_SALMON_SUPPORT -DHAVE_ANSI_TERM -DHAVE_SSTREAM -Wall -Wno-unknown-pragmas -Wno-reorder -Wno-unused-variable -std=c++11 -Wreturn-type -Werror=return-type -Wno-unused-function -Wno-unused-local-typedef -static-libstdc++  -Wno-unused-local-typedefs   -o CMakeFiles/salmon.dir/SalmonQuantMerge.cpp.o -c /tmp/salmon-20181130-14383-1ubefcz/salmon-0.10.2/src/SalmonQuantMerge.cpp
{standard input}: Assembler messages:
{standard input}:172563: Error: unknown pseudo-op: `.'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
```
https://circleci.com/gh/brewsci/homebrew-bio/4939

Depending on `binutils` didn't help.

**Comment by sjackman** [comment]
CircleCI on macOS
```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -pthread -ftree-vectorize -funroll-loops -fPIC -fomit-frame-pointer -O3 -DRAPMAP_SALMON_SUPPORT -DHAVE_ANSI_TERM -DHAVE_SSTREAM -Wall -Wno-unknown-pragmas -Wno-reorder -Wno-unused-variable -std=c++11 -Wreturn-type -Werror=return-type -Wno-unused-function -Wno-unused-local-typedef -undefined dynamic_lookup -stdlib=libc++ -DBOOST_HAS_INT128 -Wno-deprecated-register -pthread -ftree-vectorize -funroll-loops -fPIC -fomit-frame-pointer -O3 -DRAPMAP_SALMON_SUPPORT -DHAVE_ANSI_TERM -DHAVE_SSTREAM -Wall -Wno-unknown-pragmas -Wno-reorder -Wno-unused-variable -std=c++11 -Wreturn-type -Werror=return-type -Wno-unused-function -Wno-unused-local-typedef -undefined dynamic_lookup -stdlib=libc++ -DBOOST_HAS_INT128 -Wno-deprecated-register -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/unitTests.dir/__/tests/UnitTests.cpp.o CMakeFiles/unitTests.dir/FragmentLengthDistribution.cpp.o CMakeFiles/unitTests.dir/__/external/install/src/rapmap/rank9b.cpp.o CMakeFiles/unitTests.dir/__/external/install/src/rapmap/bit_array.c.o  -o unitTests  -L/tmp/salmon-20181130-5746-wh9jy6/salmon-0.10.2/lib  -L/tmp/salmon-20181130-5746-wh9jy6/salmon-0.10.2/external/install/lib -Wl,-rpath,/tmp/salmon-20181130-5746-wh9jy6/salmon-0.10.2/lib -Wl,-rpath,/tmp/salmon-20181130-5746-wh9jy6/salmon-0.10.2/external/install/lib libsalmon_core.a libalevin_core.a -lgff /usr/local/lib/libboost_iostreams-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_timer-mt.a /usr/local/lib/libboost_chrono-mt.a /usr/local/lib/libboost_program_options-mt.a /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libboost_date_time-mt.a /usr/local/lib/libboost_atomic-mt.a ../external/install/lib/libstaden-read.a /usr/lib/libz.dylib ../external/install/lib/libdivsufsort.a ../external/install/lib/libdivsufsort64.a ../external/install/lib/libbwa.a -lm /usr/local/lib/liblzma.a /usr/lib/libbz2.dylib /usr/local/lib/libtbbmalloc_proxy.dylib /usr/local/lib/libtbbmalloc.a /usr/local/lib/libtbb.a -all_load ../external/install/lib/libjemalloc.a 
duplicate symbol __ZN3tbb8internal20__TBB_load_ittnotifyEv in:
    /usr/local/lib/libtbbmalloc.a(itt_notify_malloc.o)
    /usr/local/lib/libtbb.a(itt_notify.o)
```
https://circleci.com/gh/brewsci/homebrew-bio/4938

**Comment by gaberoo** [comment]
Hi @sjackman,

I was just looking into moving the formula to 0.11.2 — get the same error (macOS 10.14).

Do you have any leads yet before I start digging? My guess is it's poorly specified linking in the unitTests that didn't survive a version upgrade. Any thoughts?

**Comment by sjackman** [comment]
@gaberoo Sorry, Gabriel. I have no leads.
@rob-p Any thoughts on either of these two Salmon build errors above? `Error: unknown pseudo-op` on Linux and `duplicate symbol` on macOS?

**Comment by sjackman** [comment]
I resolved the build issue on Linux. The build on macOS is still failing with
```
duplicate symbol __ZN3tbb8internal20__TBB_load_ittnotifyEv in:
    /usr/local/lib/libtbbmalloc.a(itt_notify_malloc.o)
    /usr/local/lib/libtbb.a(itt_notify.o)
```
https://circleci.com/gh/brewsci/homebrew-bio/5082

**Comment by gaberoo** [comment]
Hi @sjackman ,

Just FYI, I've revisited this compile issue. I've managed to compile salmon (0.13.1) now on macOS. This involved a couple patches to the CMake system, as well as a new Formula for the Staden-IOLib package.

The patches to Cmake are rather messy. I've submitted a PR to upstream (https://github.com/COMBINE-lab/salmon/pull/348), we'll see what they do with it.

**Comment by sjackman** [comment]
Excellent. Thanks for opening the PR upstream, Gabriel!

**Comment by gaberoo** [comment]
@sjackman and @rob-p, the formula is ready whenever the next salmon version is released: https://github.com/gaberoo/homebrew-bio/blob/981cd43729f4daee782ea7218b8ffcc402152467/Formula/salmon.rb

**Pull request closed without merging**
