### PR TITLE
fastani 1.2

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
`C: 21:  1: Trailing whitespace detected.`

**Comment by tseemann** [comment]
```
==> brew install gcc
Error: SIGTERM
/usr/local/Homebrew/Library/Homebrew/system_command.rb:144:in `initialize'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:144:in `initialize'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:144:in `select'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:144:in `block in each_line_from'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:143:in `loop'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:143:in `each_line_from'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:130:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:41:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:15:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:284:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1299:in `test'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:684:in `rescue in install_gcc_if_needed'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:667:in `install_gcc_if_needed'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:950:in `formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1374:in `block in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1373:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1373:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1779:in `test_bot'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1880:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:79:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:79:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
Too long with no output (exceeded 30m0s)

Uploading test results
0s
```

**Comment by sjackman** [comment]
```
macOS: 10.12.6-x86_64
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/7669
macOS 10.12 is Sierra, and Sierra no longer has a bottle for `gcc`, so it's being built from source, as you suspected. It'd be nice if that showed up in the log though.
https://github.com/Homebrew/homebrew-core/blob/6eb3028f2c4a37ac8bb89e9adb6631f9ff70125d/Formula/gcc.rb#L10-L14

You can change this line: `macos: xcode: "9.2"`
https://github.com/brewsci/homebrew-bio/blob/f6c81c02bd63dc5043f0e64b250dcbb20103d6b0/.circleci/config.yml#L47
to change the version of macOS used on CircleCI from Sierra to macOS High Sierra 10.13. You can do that from within this PR, if you like. You'll have to check the CircleCI documentation to figure out which version of Xcode corresponds to which version of macOS.

**Comment by tseemann** [comment]
MacOS:
```
checking gsl/gsl_cdf.h presence... yes
checking for gsl/gsl_cdf.h... yes
configure: creating ./config.status
config.status: creating Makefile
==> make install
g++-9 -O3 -DNDEBUG -std=c++11 -Isrc -I /usr/local/opt/gsl/include -fopenmp -mmacosx-version-min=10.7 -stdlib=libc++ -Xpreprocessor -fopenmp -lomp  src/cgi/core_genome_identity.cpp -o fastANI -L/usr/local/opt/gsl/lib -lgsl -lgslcblas -lstdc++ -lz -lm  
g++-9: error: unrecognized command line option '-stdlib=libc++'
make: *** [fastANI] Error 1
```

**Comment by tseemann** [comment]
```
Framework search paths:
	/Library/Frameworks/
	/Applications/Xcode-10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/
	/Applications/Xcode-10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/
ld: library not found for -lomp
collect2: error: ld returned 1 exit status
make: *** [fastANI] Error 1

```
macos

**Comment by sjackman** [comment]
```
g++-9: error: unrecognized command line option '-stdlib=libc++'
```

`'-stdlib=libc++` is a `clang` compiler option, not supported with `gcc`.

**Comment by sjackman** [comment]
```
ld: library not found for -lomp
```
You could use Apple Clang and `libomp` on macOS if upstream supports it.

**Comment by tseemann** [comment]
@sjackman See https://github.com/ParBLiSS/FastANI/issues/17

**Pull request closed without merging**
