### PR TITLE
star-aligner 2.7.3a

### PR DESCRIPTION
**Pull request by czhu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to Brewsci/bio! 🏆

**Comment by sjackman** [comment]
Do you know about this list of packages in Brewsci/bio?
https://repology.org/projects/?inrepo=homebrew_tap_brewsci_bio
https://repology.org/projects/?inrepo=homebrew_tap_brewsci_bio&outdated=1

**Comment by czhu** [comment]
no I had no idea. This is very interesting. Does this mean that version updating is automatic now?

**Comment by sjackman** [comment]
The version information in Repology is updated automatically. The formulae in Brewsci/bio are not updated automatically.

**Pull request closed without merging**
