### PR TITLE
biobloomtools 2.2.0

### PR DESCRIPTION
**Pull request by JustinChu**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by JustinChu** [comment]
@sjackman I've fixed some issues but the logs look like an issue with sdsl-lite.

**Comment by sjackman** [comment]
CircleCI on macOS
```
g++-8 -Wall -Wextra -Werror  -fopenmp -g -O2 -fopenmp  -o biobloommimaker biobloommimaker-BioBloomMIMaker.o biobloommimaker-Options.o ../Common/libcommon.a -lz -lsdsl -ldl 
Undefined symbols for architecture x86_64:
  "sdsl::util::demangle2(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > sdsl::util::class_name<unsigned long long>(unsigned long long const&) in biobloommimaker-BioBloomMIMaker.o
```
https://circleci.com/gh/brewsci/homebrew-bio/4918

One possibility is that it's an error caused by `sdsl-lite` being compiled with clang on macOS, whereas you're compiling Biobloomtools using GCC. You can likely reproduce this error locally on a macOS machine for troubleshooting.

**Comment by sjackman** [comment]
> I've tested installing the code on mac os before. So this is a bit strange. How do you prevent it from installing sdsl with clang?

It's not easy but possible. Let's troubleshoot first. Try installing SDSL using Homebrew on macOS, and then `brew install -dv biobloomtools`.

> Also aren't I just using a header anyway?

We tested on Linux, and yes. It's possible (though strange) that the situation is different on macOS.

**Comment by sjackman** [comment]
`sdsl-lite` on macOS is compiled with `clang`. You'll need to compile it with GCC.
See https://github.com/brewsci/homebrew-bio/blob/master/Formula/lofreq.rb for an example of a resource block. You'll need to remove the `sdsl-lite` dependency and build `sdsl-lite` in your formula using `gcc`. This change only applies to macOS. On Linux you could keep the `sdsl-lite` dependency.

**Pull request closed without merging**
