### PR TITLE
snippy 4.0.5 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
I can't identify the actual error in the (gigantic) log file:

```
==> brew bottle --verbose --json snippy --root-url=https://linuxbrew.bintray.com/bottles-bio
==> Determining brewsci/bio/snippy bottle rebuild...
==> Bottling snippy--4.0.0.x86_64_linux.bottle.tar.gz...
tar cf /tmp/bottles/snippy--4.0.0.x86_64_linux.bottle.tar snippy/4.0.0
gzip -f snippy-bottle.tar
==> Detecting if snippy--4.0.0.x86_64_linux.bottle.tar.gz is relocatable...
./snippy--4.0.0.x86_64_linux.bottle.tar.gz
  bottle do
    root_url "https://linuxbrew.bintray.com/bottles-bio"
    cellar :any_skip_relocation
    sha256 "d63be45540470f4c6a25133e95f30dd97af4e689d7671730433d88d73df1ce76" => :x86_64_linux
  end
==> brew bottle --merge --write --no-commit ./snippy--4.0.0.x86_64_linux.bottle.json
==> brewsci/bio/snippy
  bottle do
    root_url "https://linuxbrew.bintray.com/bottles-bio"
    cellar :any_skip_relocation
    sha256 "d63be45540470f4c6a25133e95f30dd97af4e689d7671730433d88d73df1ce76" => :x86_64_linux
  end
==> brew uninstall --force snippy
Uninstalling snippy... (23 files, 21.7MB)
==> brew uninstall --force autoconf automake check cmake cpanminus gawk gettext gmp gpatch gperf libtool m4 mpfr patchelf pkg-config python@2 readline sphinx-doc sqlite
Uninstalling patchelf... (6 files, 1.2MB)
==> brew install --only-dependencies ./snippy--4.0.0.x86_64_linux.bottle.tar.gz
==> Installing dependencies for snippy: patchelf
==> Installing snippy dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/patchelf--0.9_1.x86_64_linux.bottle.tar.gz
==> Pouring patchelf--0.9_1.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.9_1: 6 files, 1.2MB
==> brew install ./snippy--4.0.0.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/Cellar/snippy/4.0.0: 23 files, 21.6MB
==> brew install --only-dependencies --include-test brewsci/bio/snippy
==> Installing snippy from brewsci/bio
All dependencies for brewsci/bio/snippy are satisfied.
==> brew test brewsci/bio/snippy --verbose
Testing brewsci/bio/snippy
==> /home/linuxbrew/.linuxbrew/Cellar/snippy/4.0.0/bin/snippy --version 2>&1
==> /home/linuxbrew/.linuxbrew/Cellar/snippy/4.0.0/bin/snippy-core --version 2>&1
==> /home/linuxbrew/.linuxbrew/Cellar/snippy/4.0.0/bin/snippy --check
.
==> brew linkage --test brewsci/bio/snippy
No broken library linkage
==> brew uninstall --force brewsci/bio/snippy
Uninstalling snippy... (23 files, 21.7MB)
==> brew uninstall --force bcftools berkeley-db bioperl bwa bzip2 curl emboss expat fontconfig freebayes freetype gd gdbm gsl gzip htslib jdk jpeg k8 libbsd libharu libpng libtiff minimap2 ncurses openssl parallel perl samclip samtools seqtk snp-sites snpeff util-linux vcflib vt webp xz zlib
Uninstalling bcftools... (43 files, 6.1MB)
Uninstalling berkeley-db... (5,672 files, 131.3MB)
Uninstalling bioperl... (2,240 files, 25.4MB)
Uninstalling bwa... (8 files, 1.6MB)
Uninstalling bzip2... (30 files, 1.5MB)
Uninstalling curl... (434 files, 3.5MB)
Uninstalling emboss... (2,324 files, 504MB)
Uninstalling expat... (18 files, 1.8MB)
Uninstalling fontconfig... (514 files, 5.9MB)
Uninstalling freebayes... (10 files, 14.3MB)
Uninstalling freetype... (61 files, 11.0MB)
Uninstalling gd... (36 files, 3.3MB)
Uninstalling gdbm... (40 files, 1MB)
Uninstalling gsl... (273 files, 37MB)
Uninstalling gzip... (34 files, 622.0KB)
Uninstalling htslib... (163 files, 21.2MB)
Uninstalling jdk... (1,220 files, 556.3MB)
Uninstalling jpeg... (22 files, 4MB)
Uninstalling k8... (5 files, 4.8MB)
Uninstalling libbsd... (82 files, 717.9KB)
Uninstalling libharu... (39 files, 1.9MB)
Uninstalling libpng... (27 files, 1.3MB)
Uninstalling libtiff... (248 files, 8MB)
Uninstalling minimap2... (19 files, 1.3MB)
Uninstalling ncurses... (3,856 files, 15.4MB)
Uninstalling openssl... (1,799 files, 14.8MB)
Uninstalling parallel... (67 files, 3.3MB)
Uninstalling perl... (2,652 files, 72.8MB)
Uninstalling samclip... (8 files, 214.5KB)
Uninstalling samtools... (29 files, 841.5KB)
Uninstalling seqtk... (5 files, 254.6KB)
Uninstalling snp-sites... (38 files, 968KB)
Uninstalling snpeff... (126 files, 152.6MB)
Uninstalling util-linux... (373 files, 15.5MB)
Uninstalling vcflib... (86 files, 157.2MB)
Uninstalling vt... (24 files, 22.8MB)
Uninstalling webp... (42 files, 14.5MB)
Uninstalling xz... (99 files, 3.3MB)
Uninstalling zlib... (12 files, 427.5KB)
Error: Kernel.exit
Exited with code 1
```

**Comment by tseemann** [comment]
Maybe it's the perl XML error again?
```
ln -s ../../../Cellar/perl/5.28.0/share/man/man1/perlartistic.1 perlartistic.1
Only the first 100 operations were output.
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/cpan -i XML::Parser
..
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/perl/post_install.01.cpan:
# <head><title>An Error Occurred</title></head>
# <body>
# <h1>An Error Occurred</h1>
# <p>500 Can't locate HTML/Entities.pm in @INC (you may need to install the HTML::Entities module) (@INC contains: /home/linuxbrew/.cpan/build/libwww-perl-6.35-0/blib/lib /home/linuxbrew/.cpan/build/libwww-perl-6.35-0/blib/arch /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/site_perl/5.28.0 /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0 /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi /home/linuxbrew/.linuxbrew/lib/perl5/site_perl/5.28.0 .)</p>
# </body>
# </html>
# Looks like you failed 1 test of 4.
t/local/autoload.t ............. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests 
t/local/get.t .................. ok

#   Failed test 'get file: good title'
#   at t/local/http.t line 165.
#          got: undef
#     expected: 'En pr�ve'

#   Failed test 'get file: good content'
#   at t/local/http.t line 166.
#                   ''
#     doesn't match '(?^u:� v�re)'

#   Failed test 'terminate: bye bye'
#   at t/local/http.t line 312.
#                   ''
#     doesn't match '(?^:Bye, bye)'
# Looks like you failed 3 tests of 90.
t/local/http.t ................. 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/90 subtests 
t/local/httpsub.t .............. ok
t/local/protosub.t ............. ok
t/robot/ua-get.t ............... ok
t/robot/ua.t ................... ok

Test Summary Report
-------------------
t/base/ua.t                  (Wstat: 512 Tests: 41 Failed: 2)
  Failed tests:  19-20
  Non-zero exit status: 2
t/local/autoload-get.t       (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
t/local/autoload.t           (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
t/local/http.t               (Wstat: 768 Tests: 90 Failed: 3)
  Failed tests:  34-35, 89
  Non-zero exit status: 3
Files=18, Tests=214, 17 wallclock secs ( 0.08 usr  0.03 sys +  3.04 cusr  0.56 csys =  3.71 CPU)
Result: FAIL
Failed 4/18 test programs. 7/214 subtests failed.
Makefile:1027: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
  ETHER/libwww-perl-6.35.tar.gz
2 dependencies missing (HTML::Entities,HTML::HeadParser); additionally test harness failed
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports ETHER/libwww-perl-6.35.tar.gz
Running install for module 'Test::LeakTrace'
Fetching with HTTP::Tiny:
```

**Comment by sjackman** [comment]
`brew postinstall perl` failed.
```
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/cpan -i XML::Parser
…
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
```
https://circleci.com/gh/brewsci/homebrew-bio/3185

This issue is unfortunately a known problem. `brew install perl` succeeds in an empty `linuxbrew/linuxbrew` Docker image. It fails in a number of PRs though. There must be an interaction with another package. I'm not sure which yet.

cc @iMichka

**Comment by iMichka** [comment]
I think it has to do with either: the new make shim, or the superenv migration. I did not have time to investigate further though:

**Comment by tseemann** [comment]
On macos:
```
==> /usr/local/Cellar/snippy/4.0.0/bin/snippy --version 2>&1
==> /usr/local/Cellar/snippy/4.0.0/bin/snippy-core --version 2>&1
Error: brewsci/bio/snippy: failed
<0> expected but was
<255>.
```

**Comment by tseemann** [comment]
I'll bump to my 4.0.5 now and try a rebuild.

**Comment by tseemann** [comment]
I've rebuilt `vt` which was not linked properly in SSH CIRCLE debugging.

**Pull request closed without merging**
