### PR TITLE
Link DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates all static DOI links, as you also show [in the CONTRIBUTING.md](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md#citation).

Because I'm touching only comments, I omitted the build tests. Hope this is OK.

-----

- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

### CODE REVIEW

**Comment by jonchang** [comment]
Thanks @katrinleinweber for contributing to Brewsci!

**Comment by jonchang** [comment]
abricate fix in https://github.com/brewsci/homebrew-bio/pull/189

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Comment by sjackman** [comment]
Excellent! Thanks for this fix, Katrin!

**Pull request merged**
