### PR TITLE
nextflow 21.04.1

### PR DESCRIPTION
**Pull request by heuermh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by heuermh** [comment]
Ping @pditommaso for review

**Review by pditommaso — APPROVED** [review]

**Comment by pditommaso** [comment]
👏

**Comment by sjackman** [comment]
@heuermh Feel free to merge version bump PR that pass CI. The workflow is to simply mash that GitHub web interface `Squash and Merge` button, and CI handles updating the bottles.

Thanks again for all of your contributions to Brewsci/bio, Michael! 🌟

**Comment by heuermh** [comment]
Thank you, @sjackman!

I thought perhaps it was bad form to merge my own pull requests; will do so in the future. 😄

**Comment by sjackman** [comment]
Not at all! I encourage it for a simple version bump.

**Comment by sjackman** [comment]
I'd suggest waiting one for the bottle commit to be pushed by CI (usually takes a few minutes, and you can watch it under the `Actions` tab) before merging a second PR, if you're merging multiple PRs. The action is supposed to handle multiple PRs merged in quick succession, but better not to test it.

**Pull request merged**
