### PR TITLE
rasusa 0.2.0

### PR DESCRIPTION
**Pull request by mbhall88**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tseemann** [comment]
Thanks @mbhall88 !

**Comment by sjackman** [comment]
Thanks for your PR, Michael.
The default development branch has changed from `master` to `develop`. Please run
```sh
git -C $(brew --repo brewsci/bio) remote set-head origin -a
```

**Comment by mbhall88** [comment]
No problems. Might be worth mentioning this in the [contribution document](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md).

**Comment by sjackman** [comment]
I'm hoping to work around this issue in other ways that's not exposed to contributors. Just need a bit of time to do it… 😁

**Pull request merged**
