### PR TITLE
cutadapt 2.5

### PR DESCRIPTION
**Pull request by czhu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tseemann** [comment]
@czhu Would it be possible to use the source .tgz from `https://github.com/marcelm/cutadapt/releases/tag/v2.5`  instead of git checkout?
This is the preferred method.

@sjackman should we consider updating the python resources too?

https://files.pythonhosted.org/packages/89/63/7faada886f14843eee160973c246fb74538283cce00235d9c2ec2381fcb5/dnaio-0.4.tar.gz
  https://files.pythonhosted.org/packages/6e/df/b1ef7cda087e5f4cfabe5ce0189cdde07fc842c07c5cb5b9d5b726c12534/xopen-0.8.3.tar.gz

**Comment by tseemann** [comment]
UPDATE: 2.6 is now out.

**Comment by czhu** [comment]
created another pull for 2.6. updated all python resources. cannot use source .tgz because it doesn't build.

**Comment by sjackman** [comment]
> should we consider updating the python resources too?

Yep!

**Comment by czhu** [comment]
> > should we consider updating the python resources too?
> 
> Yep!

already taken care of in the commit

**Pull request closed without merging**
