### PR TITLE
gemma 0.98

### PR DESCRIPTION
**Pull request by pjotrp**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by pjotrp** [comment]
Started on a gemma package.

**Comment by pjotrp** [comment]
@sjackman I think it almost works. Can you check what is wrong with the MacOS build? It complains about a key.

**Comment by pjotrp** [comment]
```
brewsci/bio/gemma:
Warning: Unable to create issue comment: GitHub {
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}

The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
Error: 1 problem in 1 formula detected
```

**Comment by pjotrp** [comment]
Amazingly, this time, Azure succeeds.

**Comment by pjotrp** [comment]
Too much magic here. Don't know how to proceed.

**Comment by pjotrp** [comment]
Should I rebase and rerun the tests now?

**Comment by sjackman** [comment]
The GitHub credentials error is a red herring. You can ignore it. The real error is…
```
Error: 1 problem in 1 formula detected
  * Dependency 'openblas' may be unnecessary as it is provided by macOS; try to build this formula without it.
```
You can reproduce this error locally by running…
```sh
brew audit brewsci/bio/gemma --online --new-formula
```

Homebrew/core uses [macOS Accelerate](https://developer.apple.com/documentation/accelerate) rather than OpenBLAS. On macOS, would you rather use macOS Accelerate or `openblas`? I'm fine with either.

By happy chance, this PR by @dpo addresses this very issue to allow using `openblas` in taps. https://github.com/Homebrew/brew/pull/5072 Once it's merged, this issue will go away.

**Comment by pjotrp** [comment]
When I did not include openblas it gave a cblas.h error on MacOS

**Comment by pjotrp** [comment]
And yes, we use openblas - that is what I debug.

**Comment by tseemann** [comment]
@pjotrp 

1. instead of adding consecutive commits, you can keep it as a single commit by using `git commit --amend gemma.rb && git push -f` as you debug.

2. i realise i had packaged gemma previously for linux only: https://github.com/tseemann/homebrew-bioinformatics-linux/blob/master/Formula/gemma.rb and I note `system "make", "FORCE_DYNAMIC=1"` in my version - that must have been for a reason.
.

**Comment by pjotrp** [comment]
Hi @tseemann! Long time no see.

> instead of adding consecutive commits, you can keep it as a single commit by using git commit --amend gemma.rb && git push -f as you debug. Then when in succeeds you don't have to squash and rebuild again. It's done.

The downside is that you don't see what people do and how it affects the integration tests. I am happy to squash in the end. We did the same for sambamba here. 
 
> i realise i had packaged gemma previously for linux only: https://github.com/tseemann/homebrew-bioinformatics-linux/blob/master/Formula/gemma.rb I did not realise you were involved!

Since summer 2017 I am pretty much the maintainer. We are rapidly adding new functionality these days.
 
> always check formular with brew audit --strict --online --new-formula gemma.rb
> 
> bare git urls not allowed i thought
> 
> url "https://github.com/genetics-statistics/gemma.git" # , :revision => "595197546e1418b4944e2f797d8ceac6d495f741"
> version "0.98"

I wrote a patch which helped building. It is in above trail. 

Thanks for helping. It is important we provide pre-built binaries and the integration systems bring problems out. That is why I am packaging.

**Comment by sjackman** [comment]
Superseded by PR https://github.com/brewsci/homebrew-bio/pull/479

**Pull request closed without merging**
