### PR TITLE
circlator: import from brewsci/science

### PR DESCRIPTION
**Pull request by suujia**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----
upgraded to circlator ver 1.5.5 & fixes `Missing libraries: libpython3.6m.so.1.0`

### CODE REVIEW

**Comment by suujia** [comment]
```
    pysam/libchtslib.c:14572:12: error: too many arguments to function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth'
         return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
```
Perhaps a problem with pysam?

There was no problem running brew install, audit strict, and test locally though

**Comment by tseemann** [comment]
I vaguely recall `htslib` changing its API slightly and maybe `pysam` needs to be upgraded.

**Comment by sjackman** [comment]
My first guess would be that that Python API changed from version 3.6 to 3.7, and as Torsten suggested, upgrading `pysam` may help. I'm also okay dropping this formula from ORCA if it's not an easy fix.

**Comment by suujia** [comment]
Issue is found here: https://github.com/pysam-developers/pysam/issues/697 
Pysam is not yet integrated with python 3.7 (until new version):
```
The solution pip3 install git+https://github.com/pysam-developers/pysam should work until pysam tags off a new version and uploads to pypi. Thank you for making that known.
```

**Comment by sjackman** [comment]
The current stable release of `pysam` doesn't support Python 3.7, but the unstable release in GitHub does. Let's try replacing `pip3 install pysam` with
```
pip3 install git+https://github.com/pysam-developers/pysam
```

**Comment by sjackman** [comment]
Does updating `pysam` in this PR to 0.15.0.1 help?

**Comment by suujia** [comment]
Just tested it using pysam 0.15.0.1
```
 Running command python setup.py egg_info
    # pysam: no cython available - using pre-compiled C
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-qdhk32dw/setup.py", line 175, in <module>
        .format(fn))
    ValueError: no cython installed, but can not find pysam/libchtslib.c.Make sure that cython is installed when building from the repository
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-qdhk32dw/
```

I have tested it successfull in bcgsc/orca-6 with: 

1. install unstable version of pysam
2. pip3 install cython
3. brew install circlator 


I can add cython and unstable pysam to orca!

**Comment by sjackman** [comment]
Woohoo! Good sleuthing, Susie!

**Comment by sjackman** [comment]
Does adding `cython` to this PR fix it?

**Comment by suujia** [comment]
Adding cython doesn't seem to work, but pip3 install cython works. As demonstrated: 

including `depends_on: "cython" `
```
==> Installing dependencies for brewsci/science/circlator: cython
==> Installing brewsci/science/circlator dependency: cython
==> Downloading https://linuxbrew.bintray.com/bottles/cython-0.28.3.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cython-0.28.3.x86_64_linux.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /home/linuxbrew/.linuxbrew,
because this formula is mainly used internally by other formulae.
Users are advised to use `pip` to install cython.

If you need to have this software first in your PATH run:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/cython/bin:$PATH"' >> ~/.bash_profile
```

produced error: 
```
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/circlator/08.pip:
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.5/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.5/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.5/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.5/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.5/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 126, in prep_for_dist
    self.req.run_egg_info()
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.5/libexec/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 636, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/home/linuxbrew/.linuxbrew/Cellar/circlator/1.5.5/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 701, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-x9qu_r5c/

```

Then doing `pip3 install cython `and running the same `brew reinstall circlator ` runs successfully. 

(despite when installing cython, warning message: Cache entry deserialization failed, entry ignored)

**Comment by sjackman** [comment]
`pip3 install cython` fixes ORCA, but that doesn't unfortunately fix this PR. CI is still 🔴.
Try adding a resource for `cython` to this formula.
See https://pypi.org/project/Cython/#files
The very last file is…
```
Cython-0.28.5.tar.gz (1.9 MB)  Copy SHA256 hashSHA256 | Source | None | Aug 3, 2018
-- | -- | -- | --
```
```ruby
resource "cython" do
  url "https://files.pythonhosted.org/packages/21/89/ca320e5b45d381ae0df74c4b5694f1471c1b2453c5eb4bac3449f5970481/Cython-0.28.5.tar.gz"
  sha256 "b64575241f64f6ec005a4d4137339fb0ba5e156e826db2fdb5f458060d9979e0"
end
```

**Comment by suujia** [comment]
On travis: similar to https://github.com/Homebrew/brew/issues/1518
```
==> brew audit brewsci/bio/circlator --online --new-formula
==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
ERROR:  Error installing rubocop:
	ERROR: Failed to build gem native extension.
```

**Comment by sjackman** [comment]
You can generally ignore a TravisCI failure as long as CircleCI is 💚.

Success! Woohoo! Thanks, Susie!

**Pull request closed without merging**
