### PR TITLE
kat 2.4.1

### PR DESCRIPTION
**Pull request by maplesond**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by maplesond** [comment]
Looks like we hit a timeout on the linux build.  Could this be increased to get the build through?

**Comment by sjackman** [comment]
CircleCI on macOS was good. CircleCI on Linux failed.
```
==> brew install --only-dependencies --verbose --build-bottle brewsci/bio/kat
Too long with no output (exceeded 20m0s)
```
https://circleci.com/gh/brewsci/homebrew-bio/1970

**Comment by sjackman** [comment]
@maplesond In this same PR, but in a separate commit, add…
```diff
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 7aceca8..371e2e4 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -25,7 +25,7 @@ jobs:
           mkdir -p /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME
           cp -a . /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
       - run:
-          no_output_timeout: 20m
+          no_output_timeout: 30m
           command: |
             mkdir /tmp/bottles
             cd /tmp/bottles
@@ -68,7 +68,7 @@ jobs:
           mkdir -p $repo
           cp -a ./ $repo/
       - run:
-          no_output_timeout: 20m
+          no_output_timeout: 30m
           command: |
             mkdir /tmp/bottles
             cd /tmp/bottles
```

**Comment by maplesond** [comment]
Thanks @sjackman.

**Comment by sjackman** [comment]
```
==> brew install --only-dependencies --verbose --build-bottle brewsci/bio/kat
Too long with no output (exceeded 30m0s)
```
Let the search continue! Try 60m or 120m. Perhaps the build is hung up. If that's the case, CircleCI provides interactive debugging via ssh.

**Comment by maplesond** [comment]
Hmm bizarre.  It shouldn't take anywhere near that long to build.  I've increased the timeout to 1hr.  Let's see if that fixes the issue...

**Comment by sjackman** [comment]
🍏 It succeeded! I wonder whether a 30 m timeout would work. I'll merge it as 60 m though.

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to Brewsci/bio, Daniel!

**Pull request closed without merging**
