### PR TITLE
adam 0.36.0

### PR DESCRIPTION
**Pull request by heuermh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by YoshitakaMo** [comment]
This issue is now resolved (See https://github.com/brewsci/homebrew-bio/issues/1395). Your PR will pass the CI now if you merge the latest commit and push it again.

**Comment by heuermh** [comment]
Thank you, @YoshitakaMo!

**Comment by heuermh** [comment]
I tried fetching and rebasing against `develop`, is it possible I missed the commit that fixes this issue?

**Comment by YoshitakaMo** [comment]
```
Error: apache-spark: no bottle available!
You can try to install from source with:
  brew install --build-from-source apache-spark
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

The linuxbrew-core's `apache-spark.rb` doesn't have the bottle (https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/apache-spark.rb), though the homebrew-core's one has (https://github.com/Homebrew/homebrew-core/blob/master/Formula/apache-spark.rb). Normally these two should be synchronized, but for some reason they are not.
If someone updates `apache-spark.rb` in homebrew-core somehow, linuxbrew-core will automatically be updated and a bottle should be generated short time later. You may also want to ask a question about it on GitHub or Twitter for Homebrew.

**Comment by heuermh** [comment]
Ah, thanks for the clarification.  I haven't seen this out of sync happen before, will investigate upstream.

**Comment by heuermh** [comment]
Please don't close this, bot

**Pull request merged**
