### PR TITLE
mican 20191127 (new formula)

### PR DESCRIPTION
**Pull request by YoshitakaMo**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

`mican` is a structure alignment algorithm that can handle Multiple-chain complexes, Inverse direction of secondary structures, Cα only models, Alternative alignments, and Non-sequential alignments.

### CODE REVIEW

**Review by sjackman — CHANGES_REQUESTED** [review]

**Comment by sjackman** [comment]
Merged. Thanks again, @YoshitakaMo !🌟

**Comment by sjackman** [comment]
Would you like to join Brewsci/bio as a maintainer?

**Comment by YoshitakaMo** [comment]
Thanks for the suggestion. I am interested in becoming a maintainer, but may not be able to devote too much time to it. I would still like to participate if that is okay with you.

**Comment by sjackman** [comment]
Great! Glad to have you join the Brewsci/bio team. Commit as much time as you are able and wish.

**Pull request merged**
