### PR TITLE
abricate 0.8.10

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/blast/2.7.1: 4,123 files, 672.0MB
==> Installing brewsci/bio/abricate dependency: zlib
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/downloads/e26d7f94e9190e27f35a0ca17586414d88d5bb82ae7927206a18556eab619109--zlib-1.2.11.x86_64_linux.bottle.tar.gz
==> Verifying e26d7f94e9190e27f35a0ca17586414d88d5bb82ae7927206a18556eab619109--zlib-1.2.11.x86_64_linux.bottle.tar.gz checksum
==> Pouring zlib-1.2.11.x86_64_linux.bottle.tar.gz
tar xf /home/linuxbrew/.cache/Homebrew/downloads/e26d7f94e9190e27f35a0ca17586414d88d5bb82ae7927206a18556eab619109--zlib-1.2.11.x86_64_linux.bottle.tar.gz -C /tmp/d20181102-4668-8cjxau
cp -pR /tmp/d20181102-4668-8cjxau/zlib/. /home/linuxbrew/.linuxbrew/Cellar/zlib
chmod -Rf +w /tmp/d20181102-4668-8cjxau
/home/linuxbrew/.linuxbrew/bin/patchelf --force-rpath --set-rpath /home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11/lib/libz.so.1.2.11
Error: The `brew link` step did not complete successfully
==> Finishing up
ln -s ../Cellar/zlib/1.2.11/include/zconf.h zconf.h
ln -s ../Cellar/zlib/1.2.11/include/zlib.h zlib.h
ln -s ../../../Cellar/zlib/1.2.11/share/man/man3/zlib.3 zlib.3
rm /home/linuxbrew/.linuxbrew/include/zconf.h
rm /home/linuxbrew/.linuxbrew/include/zlib.h
rm /home/linuxbrew/.linuxbrew/share/man/man3/zlib.3
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink lib/libz.a
Target /home/linuxbrew/.linuxbrew/lib/libz.a
is a symlink belonging to blast. You can unlink it:
  brew unlink blast

To force the link and overwrite all conflicting files:
  brew link --overwrite zlib

To list all files that would be deleted:
  brew link --overwrite --dry-run zlib

Possible conflicting files are:
/home/linuxbrew/.linuxbrew/lib/libz.a -> /home/linuxbrew/.linuxbrew/Cellar/blast/2.7.1/lib/libz.a
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11: 12 files, 423.5KB
```

**Comment by sjackman** [comment]
Ugh. That's a bug in the Blast bottle for sure.

**Comment by sjackman** [comment]
```
tar tf $(brew --cache --force-bottle blast) | grep libz
blast/2.7.1/lib/libz.a
blast/2.7.1/lib/libz-static.a
```
wah wah wah
😢

**Comment by tseemann** [comment]
Why does `brew ls -v blast | grep libz` give an empty result?

**Comment by sjackman** [comment]
You likely had `zlib` and `bzip2` installed when you built BLAST from source. Try…
```sh
brew fetch --force-bottle blast
tar tf $(brew --cache --force-bottle blast) | egrep 'libbz2|libz'
```

I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/10125 to add the missing dependencies.

**Pull request closed without merging**
