### PR TITLE
skesa: add SRA functionality

### PR DESCRIPTION
**Pull request by jonchang**
Also revision bump for `boost`.

### CODE REVIEW

**Comment by sjackman** [comment]
Success on Linux! Failed on macOS.
```
c++ -std=c++11 -c -o glb_align.o glb_align.cpp -Wall -Wno-format-y2k  -pthread -fPIC -O3 -finline-functions -fstrict-aliasing -fomit-frame-pointer -msse4.2 -I /usr/local/opt/boost/include -I /usr/local/Cellar/skesa/2.3.0_1/libexec/ngs_out/include -I /usr/local/Cellar/skesa/2.3.0_1/libexec/vdb_out/include
c++ -std=c++11 -o skesa skesa.o glb_align.o -L /usr/local/Cellar/skesa/2.3.0_1/libexec/vdb_out/lib64 -lncbi-ngs-c++-static -lncbi-vdb-static -L /usr/local/Cellar/skesa/2.3.0_1/libexec/ngs_out/lib64 -lngs-c++-static -L /usr/local/opt/boost/lib -lboost_program_options -lboost_iostreams -lboost_regex -lboost_timer -lboost_chrono -lboost_system -ldl -lm  -lpthread -lz
Undefined symbols for architecture x86_64:
  "ncbi::NGS::openReadCollection(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
```
https://circleci.com/gh/brewsci/homebrew-bio/6602

**Comment by jonchang** [comment]
Yeah I can't figure out what's going on. The exact same commands are getting run on my machine and CI. Might be some symbol visibility problems since I can't see why the linker can't see symbols from the standard library.

**Comment by sjackman** [comment]
You can ssh into CircleCI interactively. From the link line, it looks like the library `-lncbi-ngs-c++-static` should provide the symbol `ncbi::NGS::openReadCollection` but doesn't.

**Comment by jonchang** [comment]
Yeah I'm gonna say this is some kind of weird sierra / xcode 9 problem. On circle these symbols are exported:

0000000000000054 T __ZN4ncbi3NGS18openReadCollectionERKSs

but not the full templated version on my mojave machine:

0000000000000066 T __ZN4ncbi3NGS18openReadCollectionERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE

**Comment by sjackman** [comment]
Running these two symbols through `c++filt` yields
```
0000000000000054 T ncbi::NGS::openReadCollection(std::string const&)
0000000000000066 T ncbi::NGS::openReadCollection(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
```
Googling these symbol names looks like it's related to using `libstdc++` vs `libc++` or perhaps C++98 vs C++11.

**Comment by jonchang** [comment]
This got me down the right track. superenv only sets MACOSX_DEPLOYMENT_TARGET to 10.9 on high sierra and up.

**Pull request closed without merging**
