### PR TITLE
xmatchview 1.2.3

### PR DESCRIPTION
**Pull request by lcoombe**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by lcoombe** [comment]
macOS error:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-wr6_3mwi/pillow/setup.py", line 914, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
```

**Comment by lcoombe** [comment]
I'm struggling to fix this error...It is confusing because I can't reproduce this on my local mac homebrew installation and nothing I've tried so far has helped (adding dependency on pkg-config, installing particular version, having full dependency on zlib, etc)

**Comment by sjackman** [comment]
Congratulations on PR number 1000, Lauren! 🍾

**Comment by sjackman** [comment]
Fortunately / unfortuantely I can reproduce this error locally on macOS 10.14 (Mojave). I'll troubleshoot and get back to you.

Do you have `/usr/include` on your macOS? I do not. That's likely the cause.

**Comment by lcoombe** [comment]
Thank you very much for the troubleshooting help, Shaun!

Yes, I do have `/usr/include/` on my macOS

**Comment by sjackman** [comment]
Here's the upstream bug and fix: https://github.com/python-pillow/Pillow/issues/3438#issuecomment-543812237

**Comment by sjackman** [comment]
I'm not sure why Pillow is being built from source though. It looks like there is a binary package (wheel) available, `Pillow-7.1.1-cp37-cp37m-macosx_10_10_x86_64.whl ` and `Pillow-7.1.1-cp38-cp38-macosx_10_10_x86_64.whl` at https://pypi.org/project/Pillow/#files

**Comment by lcoombe** [comment]
I think I built from source to attempt to solve issues I was having when I originally added `xmatchview`: https://github.com/brewsci/homebrew-bio/pull/586#issuecomment-481038979

I tried removing the build from source at some point in this troubleshooting process, but I saw different errors cropping up..

**Comment by sjackman** [comment]
Success!

**Comment by lcoombe** [comment]
Yay! Thanks for your help Shaun :)

**Pull request merged**
