### PR TITLE
ghostz 1.0.2

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI failed on macOS during `brew install gcc`
```
Too long with no output (exceeded 30m0s)
```
https://circleci.com/gh/brewsci/homebrew-bio/7642
It's hopefully a transient error. Try again.

**Comment by tseemann** [comment]
```
/usr/local/Homebrew/Library/Homebrew/system_command.rb:144:in `block in each_line_from'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:143:in `loop'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:143:in `each_line_from'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:130:in `each_output_line'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:41:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:15:in `system_command'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:284:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1299:in `test'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:684:in `rescue in install_gcc_if_needed'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:667:in `install_gcc_if_needed'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:950:in `formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1374:in `block in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1373:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1373:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1779:in `test_bot'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1880:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
Too long with no output (exceeded 30m0s)
```

@sjackman it's still happening. this one's not urgent.

**Comment by sjackman** [comment]
Might be time to move to AzureCI.

**Comment by tseemann** [comment]
I'll tag `depends_on :linux` for now and reference this thread.

**Comment by tseemann** [comment]
```
 brewsci-pull https://github.com/brewsci/homebrew-bio/pull/794
==> Fetching patch
Patch: https://github.com/brewsci/homebrew-bio/pull/794.patch
#=#=-#  #
==> Applying patch
Applying: ghostz 1.0.2
==> Patch closes issue #794
==> Fetching patch (bottle commit)
Patch: https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-794.patch
curl: (22) The requested URL returned error: 404 Not Found

Error: Failure while executing; `/home/linuxbrew/.linuxbrew/opt/curl/bin/curl -q --globoff --show-error --user-agent Linuxbrew/2.1.14-35-g9e33797\ \(Linux\;\ x86_64\ \"Red\ Hat\ Enterprise\ Linux\ Server\ release\ 7.7\ \(Maipo\)\"\)\ curl/7.66.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /home/linuxbrew/.cache/Homebrew/brewsci:master...pr-794.patch https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-794.patch` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404 Not Found
```

**Pull request closed without merging**
