### PR TITLE
gatk 4.4.0.0

### PR DESCRIPTION
**Pull request by lbergelson**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

* Update the gatk formula to 4.4.0.0, 
* set the java dependency to `opendjk@17`

### CODE REVIEW

**Comment by lbergelson** [comment]
Any thoughts on this?   It's failing the bottle build because the bottle build isn't using the right verson of java, although I think I've specified the java version in the dependencies.  Am I specifying it wrong or is the bottle build not picking it up correctly?

**Comment by heuermh** [comment]
Sorry, there is a brew audit failure unrelated to your changes, see https://github.com/brewsci/homebrew-bio/issues/1638

**Comment by heuermh** [comment]
If you could rebase to pull in fixes made for CI, then we can try to address the jdk 17 issue.

**Comment by YoshitakaMo** [comment]
The easiest way may be to update your branch once to the latest version and then re-create the pull request again. If anyone knows of a better way to do this, please let me know.

**Comment by lbergelson** [comment]
Took me a bit to get back to it but I finally rebased it... Looks like one error is solved but I'm still having the java version issue.  Is something wrong with my dependency statement maybe?

**Comment by heuermh** [comment]
In #1647 `depends_on` is simply `openjdk` even though it strictly requires JDK 17 or later; this passes CI but I am not sure it would always work on a user's workstation?  Or perhaps because at this point and time `openjdk` is newer than JDK 17 it doesn't matter.

**Comment by YoshitakaMo** [comment]
I've updated gatk to 4.6.0.0 now. `openjdk@17` is used.

**Comment by heuermh** [comment]
Thank you, @YoshitakaMo!

**Comment by lbergelson** [comment]
Thanks @YoshitakaMo.  I had forgotten about this one.

**Pull request closed without merging**
