### PR TITLE
proteinortho 5.16b

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Error: 2 problems in 1 formula
brewsci/bio/proteinortho:
  * The URL http://www.bioinf.uni-leipzig.de/Software/proteinortho/ should use HTTPS rather than HTTP
  * Stable: The URL http://www.bioinf.uni-leipzig.de/Software/proteinortho/proteinortho_v5.16b_src.tar.gz should use HTTPS rather than HTTP
```

If i use HTTPS the other tests fail!

**Comment by tseemann** [comment]
How to I resolve this http / https conun drum ?

**Comment by sjackman** [comment]
What's the error message when you use `https`?

**Comment by tseemann** [comment]
Why does this only happen on linux and not macos @sjackman ?

```
==> Downloading https://www.bioinf.uni-leipzig.de/Software/proteinortho/proteinortho_v5.16b_src.tar.gz
/usr/bin/curl -q --show-error --user-agent Linuxbrew/1.7.1-172-g4ff4e7f\ \(Linux\;\ x86_64\ 4.4.0-130-generic\)\ curl/7.47.0 --fail --silent --location --remote-time --continue-at - --output /home/linuxbrew/.cache/Homebrew/proteinortho--5.16b.tar.gz.incomplete https://www.bioinf.uni-leipzig.de/Software/proteinortho/proteinortho_v5.16b_src.tar.gz
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "proteinortho"
Download failed: https://www.bioinf.uni-leipzig.de/Software/proteinortho/proteinortho_v5.16b_src.tar.gz
```

**Comment by sjackman** [comment]
My guess is that that HTTPS certificate of https://www.bioinf.uni-leipzig.de is somehow misconfigured. You could report the issue upstream.

> Why does this only happen on linux and not macos @sjackman ?

Most likely because Linux uses OpenSSL and macOS uses Apple SecureTransport.

**Comment by tseemann** [comment]
It seems someone has created this:

https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/proteinortho.rb

I guess we can delete our one?

**Comment by sjackman** [comment]
> I guess we can delete our one?

Yep, you can close this PR.

There's no Linux bottle yet: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/proteinortho.rb`
You can run `brew build-bottle-pr proteinortho` to open a PR to build a bottle for it.

**Comment by tseemann** [comment]
Someone else did `proteinortho/6.0.6`

**Pull request closed without merging**
