### PR TITLE
parasail 2.2.0

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
checking for Z... no
configure: error: in `/tmp/parasail-20181005-2674-1ovh6el/parasail-2.2.0':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables Z_CFLAGS
and Z_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
```

**Comment by tseemann** [comment]
macos:
```
==> /usr/local/Cellar/parasail/2.2.0/bin/parasail_aligner 2>&1
Error: brewsci/bio/parasail: failed
An exception occured within a child process:
  Test::Unit::AssertionFailedError: </gap_extend/> expected to be =~
<"no sentinal(0) found in input\n">.
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:55:in `block in assert_block'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1627:in `_wrap_assertion'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:53:in `assert_block'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:542:in `block in assert_match'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1632:in `_wrap_assertion'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:533:in `assert_match'
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/parasail.rb:28:in `block in <class:Parasail>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1720:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:523:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1719:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:869:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1718:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1959:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1958:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1712:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:27:in `<main>'

==> brew uninstall --force brewsci/bio/parasail
Exited with code 1
```

**Comment by sjackman** [comment]
Can you replicate this issue locally on a macOS machine?

**Comment by tseemann** [comment]
On my Mojave laptop I get a much earlier error:
```
./configure
--prefix=/usr/local/Cellar/parasail/2.2.0

checking whether make supports nested variables... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... build-aux/install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-apple-darwin18.0.0
checking host system type... x86_64-apple-darwin18.0.0
configure:
configure: C compiler
configure:
checking for style of include used by make... GNU
checking for gcc... gcc-8
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/tmp/parasail-20181007-60098-rsrx21/parasail-2.2.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

HOMEBREW_VERSION: 1.7.6-114-g8883735
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c5a3cb75f36313491c81044274289ea977375f91
Last commit: 89 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 346ca20ecf823752169652849e63b4862158b9c9
Core tap last commit: 23 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/torsten/Library/Caches/Homebrew
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 10.0 build 1000
Git: 2.19.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: 1.8.0_31, 1.7.0_25
macOS: 10.14-x86_64
CLT: N/A
Xcode: 10.0
```

**Comment by tseemann** [comment]
```
Target: x86_64-apple-darwin17.7.0
Configured with: ../configure --build=x86_64-apple-darwin17.7.0 --prefix=/usr/local/Cellar/gcc/8.2.0 --libd
ir=/usr/local/Cellar/gcc/8.2.0/lib/gcc/8 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-8
--with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/
usr/local/opt/isl --with-system-zlib --enable-checking=release --with-pkgversion='Homebrew GCC 8.2.0' --wit
h-bugurl=https://github.com/Homebrew/homebrew-core/issues --disable-nls
Thread model: posix
gcc version 8.2.0 (Homebrew GCC 8.2.0)
configure:4262: $? = 0
configure:4251: gcc-8 -V >&5
gcc-8: error: unrecognized command line option '-V'
gcc-8: fatal error: no input files
compilation terminated.
configure:4262: $? = 1
configure:4251: gcc-8 -qversion >&5
gcc-8: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc-8: fatal error: no input files
compilation terminated.
configure:4262: $? = 1
configure:4282: checking whether the C compiler works
configure:4304: gcc-8    conftest.c  >&5
configure:4308: $? = 0
configure:4356: result: yes
configure:4359: checking for C compiler default output file name
configure:4361: result: a.out
configure:4367: checking for suffix of executables
configure:4374: gcc-8 -o conftest    conftest.c  >&5
configure:4378: $? = 0
configure:4400: result:
configure:4422: checking whether we are cross compiling
configure:4430: gcc-8 -o conftest    conftest.c  >&5
In file included from conftest.c:11:
/usr/local/Cellar/gcc/8.2.0/lib/gcc/8/gcc/x86_64-apple-darwin17.7.0/8.2.0/include-fixed/stdio.h:78:10: fatal error: _stdio.h: No such file or directory
 #include <_stdio.h>
          ^~~~~~~~~~
compilation terminated.
configure:4434: $? = 1
configure:4441: ./conftest
./configure: line 4443: ./conftest: No such file or directory
configure:4445: $? = 127
configure:4452: error: in `/Users/torsten/tmp/parasail-2.2.0':
configure:4454: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

**Comment by tseemann** [comment]
Travis was just GIT API limit reached.

**Pull request closed without merging**
