### PR TITLE
adam 0.26.0

### PR DESCRIPTION
**Pull request by heuermh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
```
Warning: Suspicious Homebrew/linuxbrew-core git origin remote found.
```
on CircleCI on Linux. https://circleci.com/gh/brewsci/homebrew-bio/5277

This issue should resolve itself in about one hour, when the Linuxbrew/brew Docker image is updated. The Docker image is being rebuilt now. https://hub.docker.com/r/linuxbrew/brew/builds

**Comment by sjackman** [comment]
@heuermh The Linuxbrew/brew Docker image has been updated. Could you please trigger a rebuild of this PR using…
```sh
git checkout adam-0.26.0
git commit --amend
git push --force
```

**Comment by sjackman** [comment]
Merged. Thanks again for your contributions to Brewsci/bio, Michael! 🏆

**Comment by heuermh** [comment]
Thank you, @sjackman!

**Pull request closed without merging**
