### PR TITLE
minia 2.0.7 migrate

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew linkage --test brewsci/bio/minia
Missing libraries:
  libz.so.1
No unwanted system libraries
==> FAILED
```
https://travis-ci.org/brewsci/homebrew-bio/builds/353235881#L2702

**Comment by tseemann** [comment]
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/minia/2.0.7 -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DSKIP_DOC=1
.
==> make
.Error: Cannot allocate memory @ io_write - /home/linuxbrew/.cache/Homebrew/Logs/minia/02.make
```

**Comment by tseemann** [comment]
```
../../gcc/graphite-optimize-isl.c:30:22: fatal error: isl/band.h: No such file or directory
 #include <isl/band.h>
                      ^
compilation terminated.
```

**Comment by sjackman** [comment]
Something's wrong with `gcc` on TravisCI. I'll look into it. You can ignore this error.

**Comment by sjackman** [comment]
The `gcc` issue should be resolved now.

**Pull request closed without merging**
