### PR TITLE
edirect: revision bump

### PR DESCRIPTION
**Pull request by hwalinga**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

As discussed in https://github.com/brewsci/homebrew-bio/issues/414 edirect needs to be "revised".

### CODE REVIEW

**Comment by sjackman** [comment]
Please copy-and-paste the error that this PR resolves into the description of the issue (better than linking to another issue). For example:

Fix the error:
```
Parser.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
```

**Comment by sjackman** [comment]
Merged. Thank you very much for your fist contribution to Brewsci/bio, Hielke! I hope that there are more to come. 🥇

**Comment by hwalinga** [comment]
Sorry to be annoying, but what exactly did I do. I looked at the commit the bump-revision command did, and the only thing it did was incrementing a number. That can't have solved it right?

**Comment by sjackman** [comment]
Try `brew update && brew upgrade edirect && brew test edirect`. Does it work now?

Bumping the revision triggered a rebuild of the binary bottles (precompiled packages) using CircleCI, which were uploaded to Bintray for permanent storage.
See https://circleci.com/gh/brewsci/homebrew-bio/6456#artifacts/containers/0
and https://bintray.com/linuxbrew/bottles-bio/edirect/9.70_2#files

**Comment by hwalinga** [comment]
Thanks for explaining, yes it works now.

**Comment by sjackman** [comment]
Glad to hear it. Thanks for following up, Hielke.

**Pull request closed without merging**
