### PR TITLE
libstatgen 1.0.15

### PR DESCRIPTION
**Pull request by alexreg**
This will be needed for [`bamUtil`](https://github.com/statgen/bamUtil), for which I will submit a new formula PR shortly.

- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `HOMEBREW_NO_INSTALL_FROM_API=1 brew install --build-from-source --verbose --keep-tmp ./Formula/<FORMULA>.rb`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your formula have no offenses with `brew style /path/to/formula.rb`?
- [x] Does your formula pass `brew audit --formula brewsci/bio/<FORMULA> --online --git --skip-style`?
- [x] Does your formula pass `brew linkage --cached --test --strict brewsci/bio/<FORMULA>` after manual installation?

-----

### CODE REVIEW

**Comment by YoshitakaMo** [comment]
>  * The homepage URL https://genome.sph.umich.edu/wiki/C%2B%2B_Library:_libStatGen is not reachable

Can the URL be changed to pass the test?

**Comment by alexreg** [comment]
@YoshitakaMo That's odd it's saying it's not reachable, as I can reach it with no problems here. Maybe a ephemeral error, and CI simply needs to be rerun?

**Comment by YoshitakaMo** [comment]
@alexreg I re-runed the CI several times but finally failed. Curiously, I can reach the website https://genome.sph.umich.edu/wiki/C%2B%2B_Library:_libStatGen from my mac, but not from my Linux with the command `curl "https://genome.sph.umich.edu/wiki/C%2B%2B_Library:_libStatGen"`. Probably this is the cause.

I recommend changing that URL to the GitHub one, https://github.com/statgen/libStatGen.

**Comment by alexreg** [comment]
@YoshitakaMo Yeah, that sounds fair. It doesn't like the colon in the URL, most likely. I've done what you suggested and pushed now.

**Comment by YoshitakaMo** [comment]
Perhaps the `-lstatgen` flag should be `-lStatGen` because the flag is case-sensitive on Linux (but not on macOS).

**Comment by YoshitakaMo** [comment]
Merged! Thank you, @alexreg !

**Pull request merged**
