### PR TITLE
portcullis 1.1.2

### PR DESCRIPTION
**Pull request by maplesond**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> Verifying portcullis--pandas--0.20.1.tar.gz checksum
gunzip -N -- /tmp/d20180811-13212-go3k4t/pandas-0.20.1.tar.gz
tar xf /tmp/d20180811-13212-go3k4t/pandas-0.20.1.tar -C /tmp/d20180811-13212-1l7nn9c
==> /home/linuxbrew/.linuxbrew/Cellar/portcullis/1.1.2_1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /tmp/portcullis--pandas-20180811-13212-11zva4g/pandas-0.20.1
…
checking python3 module: pandas... no
configure: error: failed to find required module pandas
```
https://circleci.com/gh/brewsci/homebrew-bio/3343

I see that there is a `pandas` resource, and it was installed, so I'm not entirely sure what's going on here. The `linuxbrew/linuxbrew` Docker image is useful for troubleshooting issues like these.

**Comment by sjackman** [comment]
It's possible this issue is related to https://github.com/Linuxbrew/brew/pull/783
You may want to wait until that's merged.

**Comment by sjackman** [comment]
PR https://github.com/Linuxbrew/brew/pull/783 was merged.
@maplesond Would you like to try rebasing this PR onto `master`?

**Comment by sbastkowski** [comment]
Hi @sjackman, sorry I haven't looked at the ticket for a while.  But it looks to me that the build is still failing.  should I try rebasing just to trigger a new build?

**Comment by maplesond** [comment]
Hi @sjackman, looks like the checks have still failed.  Should I rebase just to trigger a new build?

**Comment by sjackman** [comment]
I can't say why this formula worked before and is no longer working now.
The dependencies are installed in a virtual env in `libexec`, but the tool itself is being installed in `prefix`, so I suspect the problem is that the tool doesn't know where to find its dependencies. Try installing the tool in the virtualenv by changing

```diff
-    cd "scripts/portcullis" do
-      system "python3", *Language::Python.setup_install_args(prefix)
-    end
-    cd "scripts/junctools" do
-      system "python3", *Language::Python.setup_install_args(prefix)
-    end
+    venv.pip_install_and_link "scripts/portcullis", "scripts/junctools"
```
Note that's totally untested and just a guess.

**Comment by sjackman** [comment]
@maplesond I've moved away from using resources for Python dependencies, and instead using pip to install the dependencies. See for example
https://github.com/brewsci/homebrew-bio/blob/9f73707a3c03a63a24ea81289201a992eca6d30f/Formula/nxrepair.rb#L31
https://github.com/brewsci/homebrew-bio/blob/9f73707a3c03a63a24ea81289201a992eca6d30f/Formula/tigmint.rb#L32-L35
Would you like to try this approach?

**Comment by maplesond** [comment]
Hi @sjackman.  Looks good.  I'll try modifying the recipe sometime this weekend.

**Pull request closed without merging**
