### PR TITLE
xs v2

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
Do you prefer `xs` over `wgsim` or `dwgsim` or other simulators?

**Comment by tseemann** [comment]
I tend to use `art_illumina` from the `art` package as I can simulate specific Illumina instruments.  We even made a NextSeq500 profile from 10,000 of our own samples.

**Comment by sjackman** [comment]
Neat!

I'm inclined not to add this tool unless you're actively using `xs` yourself.

**Comment by tseemann** [comment]
@sjackman  you would really not accept this?

**Comment by sjackman** [comment]
I'm happy to accept it if you're using it, or have some other use case for it. Why are you adding it?

**Pull request closed without merging**
