### PR TITLE
nullarbor 2.0.20180825

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
2019-08-25T06:53:51.6418417Z Configuring Module-Build-0.4229 ... OK
2019-08-25T06:53:51.6419087Z Building and testing Module-Build-0.4229 ... ! Installing Module::Build failed. See /tmp/nullarbor-20190825-74120-vbbf7v/nullarbor-2.0.20190825/.brew_home/.cpanm/work/1566715861.74214/build.log for details. Retry with --force to force install it.
2019-08-25T06:53:51.6419705Z ! Installing the dependencies failed: Module 'Module::Build' is not installed
2019-08-25T06:53:51.6420262Z ! Bailing out the installation for Module-Runtime-0.016.
```

**Comment by tseemann** [comment]
```
--> Working on List::MoreUtils
Fetching http://www.cpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.428.tar.gz ... OK
Configuring List-MoreUtils-0.428 ... ! No MYMETA file is found after configure. Your toolchain is too old?
! Configure failed for List-MoreUtils-0.428. See /tmp/nullarbor-20190909-74081-206itm/nullarbor-2.0.20190825/.brew_home/.cpanm/work/1568006866.74176/build.log for details.
N/A
13 distributions installed
```

**Comment by jonchang** [comment]
```
Testing brewsci/bio/nullarbor
==> /home/linuxbrew/.linuxbrew/Cellar/nullarbor/2.0.20190825/bin/nullarbor.pl --version 2>&1
Error: brewsci/bio/nullarbor: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </2\.0\.20190825/> expected to be =~
<"nullarbor.pl 2.0.20181015\n">.
```

**Comment by tseemann** [comment]
==> Downloading https://linuxbrew.bintray.com/bottles-bio/snp-sites-2.5.1.x86_64_linux.bottle.1.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "snp-sites"
Download failed: https://linuxbrew.bintray.com/bottles-bio/snp-sites-2.5.1.x86_64_linux.bottle.1.tar.gz
==> FAILED

**Pull request closed without merging**
