### PR TITLE
gubbins 2.3.4

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Homebrew/brew 1.7.1-1-gc46aef1 (Restore (fixed) make shim (#766))
Homebrew/homebrew-core 7bf405a (samtools: update 1.9 bottle for Linuxbrew.)
brewsci/bio origin/master 688f82e (trimmomatic: update 0.38 bottle.)
brewsci/bio HEAD b8f49db (gubbins 2.3.1)
==> brew doctor
==> brew --env
==> brew config
==> brew readall --aliases brewsci/bio
Error: No available formula with the name "fasttree" 
Exited with code 1
```

What?

```
brew info fasttree
brewsci/bio/fasttree: stable 2.1.10 (bottled)
Approximately-maximum-likelihood phylogenetic trees
http://microbesonline.org/fasttree/
/home/linuxbrew/.linuxbrew/Cellar/fasttree/2.1.10 (3 files, 391.8KB) *
```

**Comment by tseemann** [comment]
```
usr/local/opt/python/bin/python3 setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/gubbins
copying gubbins/__init__.py -> build/lib/gubbins
copying gubbins/common.py -> build/lib/gubbins
copying gubbins/PreProcessFasta.py -> build/lib/gubbins
copying gubbins/RAxMLExecutable.py -> build/lib/gubbins
copying gubbins/RAxMLSequenceReconstruction.py -> build/lib/gubbins
copying gubbins/ValidateFastaAlignment.py -> build/lib/gubbins
running build_scripts
creating build/scripts-3.7
copying and adjusting scripts/run_gubbins.py -> build/scripts-3.7
copying and adjusting scripts/gubbins_drawer.py -> build/scripts-3.7
changing mode of build/scripts-3.7/run_gubbins.py from 644 to 755
changing mode of build/scripts-3.7/gubbins_drawer.py from 644 to 755
/usr/local/opt/python/bin/python3 setup.py install
make[2]: Nothing to be done for `install-data-am'.
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 1] Operation not permitted: '/usr/local/lib/python3.7/site-packages/test-easy-install-11734.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.7/site-packages/
```

**Comment by jonchang** [comment]
Shouldn't this be `system "python3"` etc instead? `depends_on "python"` is python 3.

**Comment by sjackman** [comment]
> `/usr/local/opt/python/bin/python3 setup.py build`

It shouldn't be using the host's `python3` executable. Other than that, no idea.

**Comment by tseemann** [comment]
@jonchang if i use `system "python3"` i get an audit failure ... which tells me python IS python3... which I know is wrong.

**Comment by sjackman** [comment]
> if i use system "python3" i get an audit failure

That's… odd, and doesn't seem right.

**Comment by jonchang** [comment]
Yeah that shouldn't be right. There's plenty of places in core that do `system "python3" ...`

**Comment by tseemann** [comment]
```
make[2]: Nothing to be done for `install-data-am'.
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 1] Operation not permitted: '/usr/local/lib/python3.7/site-packages/test-easy-install-11720.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.
```

**Comment by tseemann** [comment]
I'm tempted to make this Linux only , but only after your opinion @sjackman

**Comment by sjackman** [comment]
My guess is that even though the error is only produce on macOS (thanks to Sandbox), the root issue (writing to `$HOMEBREW_PREFIX/lib/python3.7/site-packages/`) affects both OS. That issue should probably be fixed.

**Comment by sjackman** [comment]
Ah, found the problem. `make install` runs `python3 setup.py install` in the default installation directory, which won't work.
See https://github.com/sanger-pathogens/gubbins/blob/bd5fd24fe5ff168cd2276be377dcbc9551e235b5/python/Makefile.am#L8

**Comment by sjackman** [comment]
Try changing
```diff
-system "make", "install"
+system "make", "install", "-C", "src"
```

**Comment by tseemann** [comment]
That hasn't helped.
I think it is maybe to do with this in `run_gubbins.py`
```
mport sys
sys.path.append(".")
sys.path.append("..")
```

**Comment by sjackman** [comment]
Well, it helped in that `brew install` isn't failing now. Now `brew test` is failing, which is progress! You may have to replace that `run_gubbins.py` symlink with a shell script that sets `PYTHONPATH` so it know where to find its Python libraries.

**Comment by sjackman** [comment]
Also this `audit` failure:
```
  * Formulae should not have a `HEAD` or `devel` spec
```
I work around that by merging the original PR without `head`, merge that PR, and then add `head`.

**Comment by sjackman** [comment]
Try…
```ruby
(bin/"run_gubbins.py").write_env_script(libexec/"bin/run_gubbins.py",
    :PYTHONPATH => Dir[libexec/"lib/python*/site-packages"].first)
```

**Comment by tseemann** [comment]
```
==> brew test brewsci/bio/gubbins --verbose
Testing brewsci/bio/gubbins
==> /home/linuxbrew/.linuxbrew/Cellar/gubbins/2.3.4/bin/gubbins -h 2>&1
==> /home/linuxbrew/.linuxbrew/Cellar/gubbins/2.3.4/bin/run_gubbins.py -h 2>&1
Error: brewsci/bio/gubbins: failed
<0> expected but was
<1>.
```


ARGHH. i guess i have to SSH this one....

**Comment by sjackman** [comment]
Looks like `brew test gubbins` is timing out. I believe the timeout is sixty seconds. How long should this test take?

```
==> /home/linuxbrew/.linuxbrew/Cellar/gubbins/2.3.4/bin/gubbins -h 2>&1
2755
==> /home/linuxbrew/.linuxbrew/Cellar/gubbins/2.3.4/bin/run_gubbins.py -h 2>&1
2756
Error: brewsci/bio/gubbins: failed
2757
An exception occurred within a child process:
2758
  Test::Unit::AssertionFailedError: <0> expected but was
2759
<1>.
2760
…
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
2783
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
2784
==> FAILED
```
https://github.com/brewsci/homebrew-bio/pull/343/checks?check_run_id=462945042

**Comment by tseemann** [comment]
The test should take 2 seconds. It's just -version and -help.

**Comment by sjackman** [comment]
Are you able to reproduce this issue in the `homebrew/brew` Docker image?

**Pull request closed without merging**
