### PR TITLE
bbtools 37.93

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
-- Found Java: /home/linuxbrew/.linuxbrew/bin/java (found version "9.0.1") 
CMake Error at /home/linuxbrew/.linuxbrew/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JNI (missing: JAVA_JVM_LIBRARY)
Call Stack (most recent call first):
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.10.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/linuxbrew/.linuxbrew/Cellar/cmake/3.10.2/share/cmake/Modules/FindJNI.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
```

**Comment by tseemann** [comment]
@sjackman I thought I told it to use Java 1.7 but it keeps installing Java 1.8.
That said, the `cmake` java stuff worked fine on my own system with Java 1.8.
Looking for advice!

**Comment by sjackman** [comment]
`depends_on :java` will install Java 9 on Linuxbrew, regardless of any qualification like `depends_on :java => "8"`. It's a known bug. A pull request is welcome if you're inclined to fix it.

Here's the relevant `cmake` documentation for that error message: `Could NOT find JNI (missing: JAVA_JVM_LIBRARY)`
https://cmake.org/cmake/help/v3.0/module/FindJNI.html

It looks like setting the `JAVA_HOME` environment variable in your script may help.

**Comment by sjackman** [comment]
What do you use BBTools for? Just curious.

**Comment by tseemann** [comment]
I was tempted to use `bbmerge.sh` as PEAR was no longer open source.
But `bbtools` pollutes the `$PATH` quite badly :-(

@sjackman how do I know what `JAVA_HOME` is?  
if it is using system java it could be anywhere?

**Comment by sjackman** [comment]
On CircleCI `:java` is satisfied by the `jdk` formula. So I guess I mean to try setting `JAVA_HOME` for that particular situation, and see if it helps.

**Comment by tseemann** [comment]
I'll ask my next question officially: https://github.com/brewsci/homebrew-bio/issues/105

**Comment by tseemann** [comment]
Someone else got it in!

**Pull request closed without merging**
