### PR TITLE
bbtools: import from brewsci/science

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
```
In file included from BandedAlignerJNI.c:1:0:
/home/linuxbrew/.linuxbrew/include/jni.h:45:20: fatal error: jni_md.h: No such file or directory
compilation terminated.
```
https://circleci.com/gh/brewsci/homebrew-bio/4899

```
$ brew list openjdk | grep jni_md.h
…/Cellar/openjdk/1.8.0-181/include/linux/jni_md.h
```

The file exists, but does not appear to be in the header search path.

**Comment by sjackman** [comment]
```
gcc -O3 -Wall -std=c99 -fPIC -I"/include" -I"/include/linux"
```
I suspect it's attempting to use the `JAVA_HOME` environment variable, which is currently the empty string on Linuxbrew. As a hack workaround, you could try setting `JAVA_HOME` to `HOMEBREW_PREFIX`. As I recall though that angers `brew audit`.

**Comment by sjackman** [comment]
That may help here. That PR is very nearly ready to merge.

**Comment by jonchang** [comment]
@sjackman yes I do but there are few hours in the day to get this work done! I will get around to it soon though.

**Pull request closed without merging**
