### PR TITLE
jmol 14.31.49

### PR DESCRIPTION
**Pull request by sumanthratna**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
Thanks again, Sumanth!

**Comment by sjackman** [comment]
Something went wrong with uploading the bottles for this PR. I'm not sure why.
jmol
https://github.com/brewsci/homebrew-bio/runs/3263197009
The web interface says this artifact file is 38.6 MB, but when you download it from the web interface, it's only 2,940 bytes, and doesn't include the bottle tarballs.
```console
$ wc -c bottles.zip
    2940 bottles.zip
$ unzip -l bottles.zip
Archive:  bottles.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
      746  08-06-2021 14:49   bottle_output.txt
     1808  08-06-2021 14:49   jmol--14.31.49.catalina.bottle.json
     8175  08-06-2021 14:47   jmol--14.31.49.x86_64_linux.bottle.json
       17  08-06-2021 14:49   steps_output.txt
---------                     -------
    10746                     4 files
```

**Comment by sjackman** [comment]
```
Total file: 4 ---- Processed file: 3 (75%)
98
Fail to upload '/home/runner/work/_temp/bottles/jmol--14.31.49.x86_64_linux.bottle.tar.gz' due to 'Service Unavailable'.
99
GitHub.Services.WebApi.VssServiceResponseException: Service Unavailable
100
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
101
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
102
   at GitHub.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState)
103
   at GitHub.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Boolean uploadFirstChunk, Object userState, Boolean compressStream)
104
   at GitHub.Runner.Plugins.Artifact.FileContainerServer.UploadAsync(RunnerActionPluginExecutionContext context, Int32 uploaderId, CancellationToken token)
105
File upload complete.
106
Uploaded '8817' bytes from '/home/runner/work/_temp/bottles' to server
107
Associated artifact bottles (19238958) with run #1918
```
https://github.com/brewsci/homebrew-bio/runs/3263197009#step:6:98

`Fail to upload '/home/runner/work/_temp/bottles/jmol--14.31.49.x86_64_linux.bottle.tar.gz' due to 'Service Unavailable'.`
…
`File upload complete.`
Looks like it may have been due to a transient failure, which unfortunately still marked the artifact upload as being successful, despite it having actually failed.

**Comment by sjackman** [comment]
```console
$ brew fetch -s brewsci/bio/jmol
==> Fetching jmol from brewsci/bio
==> Downloading https://downloads.sourceforge.net/project/jmol/Jmol/Version%2014
==> Downloading from https://netactuate.dl.sourceforge.net/project/jmol/Jmol/Ver
######################################################################## 100.0%
Downloaded to: /Users/shaun.jackman/Library/Caches/Homebrew/downloads/29dcdd9be81176b3c12a449c5732fa9e8498d5fdb37bc52d1a87f6610aeb33c5--Jmol-14.31.49-binary.zip
SHA256: ee8c4792c5008aae7f13db42f0d544f6daef348f6bae56b55518a22e2a4e777e
Warning: Formula reports different sha256: 56d0373f16988282609b37fd514f48ea0b8ad3d237d9751bfc0615cfce8d438f
brew fetch -s brewsci/bio/jmol  1.40s user 1.56s system 16% cpu 18.141 total 34140 MB
```
Looks like the upstream tarball `Jmol-14.31.49-binary.zip` has changed SHA-256 as well?
@sumanthratna Would you like to verify with the upstream authors why that taball has changed its checksum, and open a new PR to change the SHA-256 of the tarball?

**Comment by sumanthratna** [comment]
> ```
> $ brew fetch -s brewsci/bio/jmol
> ==> Fetching jmol from brewsci/bio
> ==> Downloading https://downloads.sourceforge.net/project/jmol/Jmol/Version%2014
> ==> Downloading from https://netactuate.dl.sourceforge.net/project/jmol/Jmol/Ver
> ######################################################################## 100.0%
> Downloaded to: /Users/shaun.jackman/Library/Caches/Homebrew/downloads/29dcdd9be81176b3c12a449c5732fa9e8498d5fdb37bc52d1a87f6610aeb33c5--Jmol-14.31.49-binary.zip
> SHA256: ee8c4792c5008aae7f13db42f0d544f6daef348f6bae56b55518a22e2a4e777e
> Warning: Formula reports different sha256: 56d0373f16988282609b37fd514f48ea0b8ad3d237d9751bfc0615cfce8d438f
> brew fetch -s brewsci/bio/jmol  1.40s user 1.56s system 16% cpu 18.141 total 34140 MB
> ```
> 
> Looks like the upstream tarball `Jmol-14.31.49-binary.zip` has changed SHA-256 as well?
> @sumanthratna Would you like to verify with the upstream authors why that taball has changed its checksum, and open a new PR to change the SHA-256 of the tarball?

Looking at the [commit history](https://sourceforge.net/p/jmol/activity/?page=0&limit=100#610dc3b3f5dd3be5a399aa4f) it looks like the developers released 14.31.49, made some fixes to `JSpecView`, and then published a new release under the same tag (maybe assuming that no-one had installed the newest version, or maybe they just forgot to update the tag)

I'll start a new PR to fix the SHA—@sjackman should I add a `revision`?

**Pull request merged**
