### PR TITLE
fastani 1.1

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
config.status: creating Makefile
==> make install
clang++ -O3 -DNDEBUG -std=c++11 -Isrc -I /usr/local/opt/boost/include  -mmacosx-version-min=10.7 -stdlib=libc++ -DUSE_BOOST src/cgi/core_genome_identity.cpp -o fastANI /usr/local/opt/boost/lib/libboost_math_c99.a -lstdc++ -lz -lm  
src/cgi/core_genome_identity.cpp:11:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [fastANI] Error 1

==> Formula
```

New threaded version needs openMP - ok!

**Comment by tseemann** [comment]
```
==> make install
g++-8 -O3 -DNDEBUG -std=c++11 -Isrc -I /usr/local/opt/boost/include -fopenmp -mmacosx-version-min=10.7 -stdlib=libc++ -DUSE_BOOST src/cgi/core_genome_identity.cpp -o fastANI /usr/local/opt/boost/lib/libboost_math_c99.a -lstdc++ -lz -lm  
g++-8: error: unrecognized command line option '-stdlib=libc++'
make: *** [fastANI] Error 1
```

**Comment by sjackman** [comment]
The option `-stdlib=libc++` is specific to clang.

**Comment by tseemann** [comment]
It must be detecting it is on Darwin and setting those options irrespective of the compiler.
Which is odd, as they added OMP support and that doesn't work in clang.

**Comment by sjackman** [comment]
Perhaps this released wasn't tested on macOS. It should be fixable with something like…
```ruby
inreplace "Makefile", "-stdlib=libc++", ""

**Comment by tseemann** [comment]
I made it use the non-Darwin flags and get a different error now. I'll try plan C.

```
g++-8 -O3 -DNDEBUG -std=c++11 -Isrc -I /usr/local/opt/boost/include -fopenmp -include src/common/memcpyLink.h -Wl,--wrap=memcpy -DUSE_BOOST src/cgi/core_genome_identity.cpp -o fastANI /usr/local/opt/boost/lib/libboost_math_c99.a -lstdc++ -lz -lm  
/private/tmp/cciS78NP.s:2:2: error: unknown directive
        .symver memcpy,memcpy@GLIBC_2.2.5
        ^
```

**Comment by sjackman** [comment]
```
error: unknown directive
        .symver memcpy,memcpy@GLIBC_2.2.5
```
That looks to me like an assembler `as` error, which you'd get if `binutils` were too old. How did you resolve this issue?

**Pull request closed without merging**
