### PR TITLE
anvio: import from brewsci/science

### PR DESCRIPTION
**Pull request by suujia**
See: https://github.com/brewsci/homebrew-science/pull/204

### CODE REVIEW

**Comment by suujia** [comment]
Linux
```
Error compiling Cython file:  raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: sklearn/metrics/cluster/expected_mutual_info_fast.pyx
Running setup.py install for scikit-learn: finished with status 'error'
```
MacOS
```
pip._internal.exceptions.InstallationError: Command "/usr/local/Cellar/anvio/5.1/libexec/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-dakwo0mc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-ijv6iuh9/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/Cellar/anvio/5.1/libexec/bin/../include/site/python3.7/scikit-learn" failed with error code 1 in /private/tmp/pip-req-build-dakwo0mc/
```

**Comment by tseemann** [comment]
`brewsci/bio/matplotlib`  exists now.

**Comment by sjackman** [comment]
@ozcan Hi, Özcan. I see that you originally authored the `anvio` formula for Homebrew/science. Would you have the time and interest to update it for Brewsci/bio?

**Comment by tseemann** [comment]
http://merenlab.org/2016/06/26/installation-v2/

```
brew tap merenlab/anvio
brew install merenlab/anvio/anvio
# Once the installation is complete, test anvi’o quickly to make sure everything is in order:
anvi-self-test --suite mini
```

**Pull request closed without merging**
