### PR TITLE
sambamba: import from brewsci/science

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
make sambamba-ldmd2-64
./gen_ldc_version_info.py /home/linuxbrew/.linuxbrew/opt/ldc/bin/ldmd2 > utils/ldc_version_info_.d
cd htslib && /usr/bin/make
cd lz4/lib && gcc-5 -O3 -c lz4.c lz4hc.c lz4frame.c xxhash.c && ar rcs liblz4.a lz4.o lz4hc.o lz4frame.o xxhash.o
/usr/bin/env: ‘python’: No such file or directory
make[1]: Entering directory '/tmp/sambamba-20180831-14390-ev8i9s/htslib'
Makefile:56: recipe for target 'ldc-version-info' failed
```
https://circleci.com/gh/brewsci/homebrew-bio/3877

**Comment by sjackman** [comment]
```
sambamba/depth.d(1154): Error: Implicit string concatenation is deprecated, use "mapping_quality > 0 and " ~ "not duplicate and " instead
sambamba/depth.d(1155): Error: Implicit string concatenation is deprecated, use "not duplicate and " ~ "not failed_quality_control" instead
```
https://circleci.com/gh/brewsci/homebrew-bio/3878

Reported upstream at https://github.com/biod/sambamba/issues/363

**Comment by sjackman** [comment]
Hopefully this build failure will be resolved by sambamba 0.6.8.

**Comment by pjotrp** [comment]
the failure says 

    make: *** No rule to make target 'sambamba-ldmd2-64'.  Stop.

run make without sambamba-ldmd2-64.

    make release
    make check

**Comment by sjackman** [comment]
Done. Thanks for the tip, Pjotr!

**Comment by sjackman** [comment]
```
make release
cd lz4/lib && gcc -O3 -c lz4.c lz4hc.c lz4frame.c xxhash.c && ar rcs liblz4.a lz4.o lz4hc.o lz4frame.o xxhash.o
cd htslib && /usr/bin/make
python3 ./gen_ldc_version_info.py /home/linuxbrew/.linuxbrew/opt/ldc/bin/ldmd2 > utils/ldc_version_info_.d
make[1]: Entering directory '/tmp/sambamba-20181004-15108-195pr81/htslib'
compile single object...
/bin/sh: 1: python3: not found
Makefile:67: recipe for target 'ldc-version-info' failed
```
@pjotrp It appears to depend on `python3` now. Is that a new dependency? And is it a build-time or run-time dependency?

**Comment by pjotrp** [comment]
python3 is now a build-time dependency. Need to go with the times...

**Comment by sjackman** [comment]
`make check` is failing with
```
==> make check
.
Error: An exception occured within a child process:
  Errno::ENOENT: No such file or directory - build/sambamba
```
See https://travis-ci.org/brewsci/homebrew-bio/builds/437315739#L3811

**Comment by sjackman** [comment]
```
==> brew test brewsci/bio/sambamba --verbose
Testing brewsci/bio/sambamba
==> /home/linuxbrew/.linuxbrew/Cellar/sambamba/0.6.8/bin/sambamba --help 2>&1
Error: brewsci/bio/sambamba: failed
An exception occured within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was <1>.
```
https://travis-ci.org/brewsci/homebrew-bio/builds/437406024#L3985

@pjotrp Has the exit status of `sambamba --help` changed from 0 to 1?

**Comment by sjackman** [comment]
@pjotrp I'm getting this error when building on macOS, both when building on my laptop and on CircleCI.
```
linking...
ldc2 -wi -I. -IBioD -IundeaD/src -g -O3 -release -enable-inlining -boundscheck=off -of=bin/sambamba bin/sambamba.o  htslib/libhts.a lz4/lib/liblz4.a -L-L -L-lpthread -L-lm
Undefined symbols for architecture x86_64:
  "__D5utils17ldc_version_info_18DMD_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
  "__D5utils17ldc_version_info_18LDC_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
  "__D5utils17ldc_version_info_19LLVM_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
  "__D5utils17ldc_version_info_24BOOTSTRAP_VERSION_STRINGyAa", referenced from:
      __D4main12printVersionFZv in sambamba.o
ld: symbol(s) not found for architecture x86_64
```
https://circleci.com/gh/brewsci/homebrew-bio/4425

**Comment by pjotrp** [comment]
Yes, the binary directory is now 'bin' instead of 'build'.

**Comment by pjotrp** [comment]
The symbol error is because the python generated utils/ldc_version_info_.d is not linked in. This is probably because it does not exist when the makefile starts so it is not listed in the inputs. I used to have it on the linker line, but then at some point the linker started complaining about the duplicate object. Hmmm. 

The quick hack is to generate this file before you invoke the make command. Can you try that? I'll think of a fix later. Strangely all other build systems work, including the MacOS on sambamba Travis.

**Comment by pjotrp** [comment]
I think I provided a fix.

**Comment by sjackman** [comment]
I tried adding `make utils/ldc_version_info_.d`, but I got this error:
```
==> make utils/ldc_version_info_.d
make: *** No rule to make target `utils/ldc_version_info_.d'.  Stop.
```
https://circleci.com/gh/brewsci/homebrew-bio/4444
What's the correct command, or would you like to tag a stable release 0.6.9?

**Comment by pjotrp** [comment]
If you update the github hash to latest a plain make should work

    make
    make check

please try one more time. Leave it at 0.6.8 because the binary does not change.

**Comment by sjackman** [comment]
Superseded by PR https://github.com/brewsci/homebrew-bio/pull/469.

**Pull request closed without merging**
