### PR TITLE
nextflow: Use depends_on openjdk instead of java 1.8+

### PR DESCRIPTION
**Pull request by heuermh**
See #1158 

- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
```console
$ brew install nextflow
$ nextflow -v
nextflow version 20.07.1.5412
```
Works for me?

**Comment by heuermh** [comment]
@pditommaso Might you have a preference here (depends_on `openjdk` vs `java`)?

I am presenting Nextflow to a non-science audience next week, and the fewer barriers to getting started, the better 😉

**Comment by sjackman** [comment]
`depends_on :java` leaves the choice of Java implementation up to the user. `brew install openjdk` will satisfy this requirement.

**Comment by sjackman** [comment]
> `depends_on :java` is when java 1.8 is needed …

Ah, that is news to me! I didn't realize that the meaning of `depends_on :java` had changed from what it used to mean. Sorry for all the confusion. In that case, I'm fine with `depends_on "openjdk"`.

I did like though that `depends_on :java` could make use of `/usr/bin/java` when it was sufficient. `brew install openjdk` takes 337 MB of disk space, and its dependencies take another 95 MB of disk space.

**Comment by sjackman** [comment]
Could you please rebase this PR onto `origin/develop`?

**Comment by heuermh** [comment]
Superceded by #1215

**Pull request closed without merging**
