### PR TITLE
sortmerna 3.0.3

### PR DESCRIPTION
**Pull request by dmohadjel**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by dmohadjel** [comment]
CircleCI
```
==> ./configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cellar/sortmerna/3.0.3
Failed to execute: ./configure
```
```
Error: 1 problem in 1 formula detected
brewsci/bio/sortmerna:
  * The URL http://bioinfo.lifl.fr/RNA/sortmerna/ should use HTTPS rather than HTTP
```

**Comment by sjackman** [comment]
Looks like they've switched from Autoconf `./configure` to CMake. See https://github.com/biocore/sortmerna#getting-started

You could use the GitHub project page as the web page instead to avoid that HTTPS error.

**Comment by dmohadjel** [comment]
CircleCI for macOS
```
CMake Error at src/sortmerna/CMakeLists.txt:15 (find_package):
  Could not find a package configuration file provided by "RocksDB" with any
  of the following names:

    RocksDBConfig.cmake
    rocksdb-config.cmake

  Add the installation prefix of "RocksDB" to CMAKE_PREFIX_PATH or set
  "RocksDB_DIR" to a directory containing one of the above files.  If
  "RocksDB" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/sortmerna-20190729-5249-1tjqtal/sortmerna-3.0.3/build/CMakeFiles/CMakeOutput.log".
```
`rocksdb` dependency not being installed on macOS?

**Comment by sjackman** [comment]
Are you able to reproduce and troubleshoot this issue locally on macOS? Have you tried setting `RocksDB_DIR` as the error suggested?

**Comment by dmohadjel** [comment]
I'm not sure which directory is containing either of those files if I want to try setting `RocksDB_DIR`.

**Pull request closed without merging**
