### PR TITLE
salmon 1.2.1

### PR DESCRIPTION
**Pull request by sjackman**
See https://github.com/COMBINE-lab/salmon/releases/tag/v1.2.0

- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

### CODE REVIEW

**Comment by sjackman** [comment]
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURL_LIBRARY
```
https://github.com/brewsci/homebrew-bio/pull/984/checks?check_run_id=590473550#step:6:2476

**Comment by sjackman** [comment]
```
/tmp/salmon-20200415-4274-7xisxp/salmon-1.2.0/include/jellyfish/int128.hpp:130:7: error: explicit specialization of 'std::__1::numeric_limits<__int128>' after instantiation
class numeric_limits<__int128> {
      ^~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:934:86: note: implicit instantiation first required here
    _LIBCPP_INLINE_VISIBILITY static _LIBCPP_CONSTEXPR _Rep min()  _NOEXCEPT {return numeric_limits<_Rep>::lowest();}
```
https://github.com/brewsci/homebrew-bio/pull/984/checks?check_run_id=590473539#step:4:3095

**Comment by rob-p** [comment]
Yea, I am not on Catalina yet, so thats why I didnt see this when we did our mac builds before release.  Looks like the C++ compiler being friendly again.

**Comment by sjackman** [comment]
Yeah, I'm not on Catalina yet either. GitHub Actions uses macOS Catalina, which is how I saw the error. I highly recommend GitHub Actions for CI! It's great.

**Comment by rob-p** [comment]
@sjackman :

Ok, so it seems if we pass `-DHAVE_NUMERIC_LIMITS128` in the compiler flags, perhaps here (https://github.com/COMBINE-lab/salmon/blob/master/CMakeLists.txt#L71), it may resolve this issue.  The obvious question is how we problem to set that value during the configure step.

**Comment by sjackman** [comment]
I'm not terribly familiar with `cmake`. I use `autoconf` and `automake` more. Sorry!

**Comment by rob-p** [comment]
Sems try_compile will do it.  But is there a way to add this manually and see if it fixes the build?

**Comment by sjackman** [comment]
> Sems try_compile will do it. But is there a way to add this manually and see if it fixes the build?

I don't have access to a physical Catalina machine.
TravisCI supports macOS 10.14 https://docs.travis-ci.com/user/reference/osx/#macos-version
You could try to reproduce the issue using that (though I suspect it won't reproduce).
If you had the time and interest, you could setup GitHub Actions for testing Salmon on macOS.

**Comment by rob-p** [comment]
Is there a way to apply a patch to a brew build?  I think I have a fix upstream, but don't want to cut a new release for this.

**Comment by sjackman** [comment]
Yes! See for example https://github.com/brewsci/homebrew-bio/blob/5176e1f2cd1de39dddfda66e90e2b23efd99c44f/Formula/sga.rb#L23-L27

**Comment by rob-p** [comment]
Can we see if 1.2.1 fixes it?

**Comment by rob-p** [comment]
I can't parse the output easily.  Is the salmon build still failing?  It looks like something trinity related.

**Comment by sjackman** [comment]
That failure was unrelated to Salmon. I've fixed that issue in PR #998. Retrying the Salmon build now.

**Comment by rob-p** [comment]
W00t!  It's awesome to finally have a salmon build that looks to work in brew :) !

**Comment by sjackman** [comment]
Woohoo! Thanks for the fix, Rob!🍾

**Comment by rob-p** [comment]
Sure thing!  Glad to have a new salmon release on brew.  Thanks for leading the charge :).

**Pull request merged**
