### PR TITLE
repeatmasker 4.0.9

### PR DESCRIPTION
**Pull request by dmohadjel**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by dmohadjel** [comment]
CircleCI
```
==> brew install --verbose --build-bottle brewsci/bio/repeatmasker
Error: SIGHUP
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:149:in `select'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:149:in `block in each_line_from'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:148:in `loop'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:148:in `each_line_from'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:135:in `each_output_line'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:41:in `run!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/system_command.rb:15:in `system_command'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:282:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1259:in `test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:958:in `formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1334:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1333:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1333:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1719:in `test_bot'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1820:in `<top (required)>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:22:in `require'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:22:in `require?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:108:in `<main>'
Too long with no output (exceeded 30m0s)
```

**Comment by sjackman** [comment]
Can you reproduce this error locally?

**Comment by dmohadjel** [comment]
I tried reproducing it locally and it eventually led me to this prompt:
```
Add a Search Engine:
   1. Crossmatch - Phrap             [ Un-configured ]
   2. RMBlast - Improved NCBI Blast  [ Un-configured ]
   3. HMMER3.1 & DFAM                [ Un-configured ]
   4. ABBlast/WUBlast                [ Un-configured ]

   5. Done


Enter Selection: Invalid selection!
```
Although I wasn't actually able to make a selection.

**Comment by dmohadjel** [comment]
I observed something odd relating to this formula. So somehow over the weekend my disk space on the `hpce706` server became completely full. I wasn't working on it when it reached capacity so I'm not sure how that happened. I was looking into what was taking up so much space and this is what I found:
```
[dmohadjel@hpce706 Logs]$ du -h --max-depth=1
755K	./expat
1.6M	./viennarna
36G	./repeatmasker
28K	./ant
155K	./bzip2
28K	./trimmomatic
1.4M	./pkg-config
576K	./mlst
79K	./sumaclust
2.3M	./salmon
549K	./stacks
175K	./kmc
4.0M	./openssl
2.3M	./wget
5.4M	./glib
717K	./hmmer2
525K	./vsearch
3.6M	./perl
4.6M	./gettext
2.0M	./git
53K	./finch-rs
795K	./maker
247K	./edirect
2.5M	./gmap-gsnap
203K	./patchelf
152K	./megahit
28K	./salmid
2.2M	./ncurses
357K	./phyml
3.3M	./emboss
41M	./glibc
272K	./last
336K	./mash
127K	./stringtie
28K	./abricate
4.6M	./python
271K	./nanopolish
53K	./trf
7.4M	./blast
53K	./sortmerna
584K	./paml
3.8M	./curl
1.6M	./mothur
79K	./porechop
130K	./libbigwig
1.1M	./webp
1.7M	./fontconfig
250K	./bioperl
994K	./iqtree
1.9M	./meme
79K	./transdecoder
1.8M	./cpio
127K	./kma
3.6M	./util-linux
4.0M	./python@2
453K	./nextflow
683K	./circos
2.2M	./libidn2
127K	./bowtie
127K	./gemma
28K	./mosdepth
892K	./lrsim
3.0M	./exonerate
28K	./minced
186K	./beast2
381K	./trnascan
28K	./cpanminus
36G	.
```
`repeatmasker` alone was taking 36G and these were the processes running:
```
[dmohadjel@hpce706 Logs]$ lsof +D /home/dmohadjel/.cache/Homebrew/Logs
COMMAND    PID      USER   FD   TYPE DEVICE    SIZE/OFF        NODE NAME
lsof     25338 dmohadjel  cwd    DIR   0,67        1645 16677084407 /home/dmohadjel/.cache/Homebrew/Logs
lsof     25339 dmohadjel  cwd    DIR   0,67        1645 16677084407 /home/dmohadjel/.cache/Homebrew/Logs
bash     75190 dmohadjel  cwd    DIR   0,67        1645 16677084407 /home/dmohadjel/.cache/Homebrew/Logs
sh       98242 dmohadjel    1w   REG   0,67 14572757026 17011954178 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/02.configure
sh       98242 dmohadjel    2w   REG   0,67 14572757026 17011954178 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/02.configure
perl     98247 dmohadjel    1w   REG   0,67 14572757690 17011954178 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/02.configure
perl     98247 dmohadjel    2w   REG   0,67 14572757690 17011954178 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/02.configure
sh      126841 dmohadjel    1w   REG   0,67 24228577974 16965021998 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/.nfs00000003f331b12e000b6367
sh      126841 dmohadjel    2w   REG   0,67 24228577974 16965021998 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/.nfs00000003f331b12e000b6367
perl    126844 dmohadjel    1w   REG   0,67 24228577974 16965021998 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/.nfs00000003f331b12e000b6367
perl    126844 dmohadjel    2w   REG   0,67 24228577974 16965021998 /home/dmohadjel/.cache/Homebrew/Logs/repeatmasker/.nfs00000003f331b12e000b6367
```

**Comment by sjackman** [comment]
You can delete those `repeatmasker` files.

Manually configure `repeatmasker` by running the `./configure` script manually, and ensure the prompts and responses agree with those listed in the formula here:
https://github.com/brewsci/homebrew-bio/blob/master/Formula/repeatmasker.rb#L36-L59

**Comment by dmohadjel** [comment]
CircleCI for macOS
```
==> /usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker
Error: brewsci/bio/repeatmasker: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - /usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker
```

**Comment by sjackman** [comment]
CircleCI on macOS
```
==> brew test brewsci/bio/repeatmasker --verbose
==> FAILED
Testing brewsci/bio/repeatmasker
/usr/bin/sandbox-exec -f /private/tmp/homebrew20190729-18644-waphhn.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-cobertura-1.3.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-macho-2.2.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-rspec-1.34.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-performance-1.4.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rubocop-0.73.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unicode-display_width-1.6.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ruby-progressbar-1.10.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-wait-0.0.9/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-retry-0.6.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-its-1.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-3.8.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-mocks-3.8.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-expectations-3.8.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-core-3.8.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rspec-support-3.8.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ronn-0.7.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rdiscount-2.2.0.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/rdiscount-2.2.0.1:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/rainbow-3.0.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/plist-3.5.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parser-2.6.3.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel_tests-2.29.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/parallel-1.17.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mustache-1.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mechanize-2.7.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/webrobots-0.1.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ntlm-http-0.1.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/nokogiri-1.10.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/nokogiri-1.10.3:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mini_portile2-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-persistent-3.1.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/net-http-digest_auth-1.4.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-3.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/mime-types-data-3.2019.0331/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/jaro_winkler-1.5.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.3:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/http-cookie-1.0.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/hpricot-0.8.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/hpricot-0.8.6:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/domain_name-0.5.20190701/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf-0.1.4/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/unf_ext-0.0.7.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/diff-lcs-1.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/coveralls-0.8.23/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thor-0.20.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/term-ansicolor-1.7.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tins-1.21.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-0.16.1/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/simplecov-html-0.10.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/docile-1.3.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/json-2.2.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/extensions/universal-darwin-18/2.3.0/json-2.2.0:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/connection_pool-2.2.2/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/backports-3.15.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/ast-2.4.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/activesupport-5.2.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/tzinfo-1.2.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/thread_safe-0.3.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/minitest-5.11.3/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/i18n-1.6.0/lib:/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.3.0/gems/concurrent-ruby-1.1.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/power_assert-0.2.6/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/gems/2.3.0/gems/test-unit-3.1.5/lib:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby/2.3.0/x86_64-darwin13:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/site_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin13:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/vendor_ruby:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0:/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/x86_64-darwin13:/usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/repeatmasker.rb --verbose
==> /usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker
Error: brewsci/bio/repeatmasker: failed
An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - /usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6967

Are you able to reproduce this issue locally on macOS?

**Comment by dmohadjel** [comment]
There is a `RepeatMasker` file in `/usr/local/Cellar/repeatmasker/4.0.9/bin/`, although it is of type `ISO-8859 text`. If I try to run any command with `/usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker` I get the following error:
```
/usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker: perl: bad interpreter: No such file or directory
```

**Comment by sjackman** [comment]
What's interpreter specified by the shebang `#!` line of this file? On macOS the formula does not depend on brewed `perl`, so on macOS the interpreter should be the Perl executable provided by macOS `#!/usr/bin/perl`. On Linux we used the brewed perl executable.

**Comment by dmohadjel** [comment]
> What's interpreter specified by the shebang `#!` line of this file? 

In the `RepeatMasker` file it uses `#!perl`.

**Comment by sjackman** [comment]
That's not a valid shebang line. It must be an absolute path or `#!/usr/bin/env perl`. I prefer an absolute path.

**Comment by dmohadjel** [comment]
I wasn't able to recreate it, but at some point `$ /usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker options` was able to run and responded with:
```
RepeatMasker version open-4.0.9
Search Engine: HMMER [ 3.2.1 (June 2018) ]
There is no writing access to the current directory (/usr/bin) nor to the directory containing the query sequence.
Consider using "-dir" or changing current directory. at /usr/local/Cellar/repeatmasker/4.0.9/bin/RepeatMasker line 6779.
```
I'm not really sure why it was suddenly able to run. I tried repeating the steps and it wasn't able to run on my second try. Although even when it was working, `brew test brewsci/bio/repeatmasker --verbose` still failed. Should `RepeatMasker` be an executable? The ones I'm seeing are only `ISO-8859 text` files on macOS.

**Comment by sjackman** [comment]
> Should RepeatMasker be an executable? The ones I'm seeing are only ISO-8859 text files on macOS.

```console
$ file /gsc/btl/linuxbrew/Cellar/repeatmasker/4.0.7_4/bin/RepeatMasker
/gsc/btl/linuxbrew/Cellar/repeatmasker/4.0.7_4/bin/RepeatMasker: Bourne-Again shell script, ASCII text executable
$ head -n1 /gsc/btl/linuxbrew/Cellar/repeatmasker/4.0.7_4/bin/RepeatMasker
#!/bin/bash
```

**Pull request closed without merging**
