### PR TITLE
skesa 2.2.1

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
Turns out `sed -i` doesn't work in osx, a backup extension is mandatory `sed -i.bak`

**Comment by tseemann** [comment]
TRAVIS is giving lots of C++ errors regarding boost. Not apparent on the CI OS builds?
```
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/skesa/01.make:
/home/linuxbrew/.linuxbrew/opt/boost/lib/libboost_regex.a(instances.o): In function `boost::re_detail_106700::basic_regex_creator<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::append_set(boost::re_detail_106700::basic_char_set<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, mpl_::bool_<false>*)':
instances.cpp:
```
Does this prevent bottles being uploaded?

**Comment by sjackman** [comment]
No, TravisCI does not prevent bottles from being built. You can ignore the TravisCI error and merge this PR.

**Comment by tseemann** [comment]
The bottles never appeared on bintray

https://bintray.com/linuxbrew/bottles-bio/skesa

**Pull request closed without merging**
