### PR TITLE
pugz 0.8.0

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
/usr/bin/ld: /tmp/ccNbQPgH.ltrans0.ltrans.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:192: recipe for target 'gunzip' failed
make: *** [gunzip] Error 1
```
I assume this in OpenMP related; will depend on gcc and see.

**Comment by tseemann** [comment]
Now with `make V=1`:
```
ar cr libdeflate.a 
CC="g++-5" CFLAGS=" -std=c++14 -I. -Icommon -lpthread -Iexternal/type_safe/include -Iexternal/type_safe/external/debug_assert -Wall -Wundef -Wrestrict -Wnull-dereference -Wuseless-cast -Wshadow -Weffc++ -Wpedantic -Wvla -O4 -flto -march=native -mtune=native -g -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H" programs/detect.sh > programs/config.h
g++-5 -o programs/gunzip.o -c  -std=c++14 -I. -Icommon -lpthread -Iexternal/type_safe/include -Iexternal/type_safe/external/debug_assert -Wall -Wundef -Wrestrict -Wnull-dereference -Wuseless-cast -Wshadow -Weffc++ -Wpedantic -Wvla -O4 -flto -march=native -mtune=native -g -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H programs/gunzip.cpp
g++-5 -o programs/prog_util.o -c  -std=c++14 -I. -Icommon -lpthread -Iexternal/type_safe/include -Iexternal/type_safe/external/debug_assert -Wall -Wundef -Wrestrict -Wnull-dereference -Wuseless-cast -Wshadow -Weffc++ -Wpedantic -Wvla -O4 -flto -march=native -mtune=native -g -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H programs/prog_util.cpp
g++-5 -o programs/tgetopt.o -c  -std=c++14 -I. -Icommon -lpthread -Iexternal/type_safe/include -Iexternal/type_safe/external/debug_assert -Wall -Wundef -Wrestrict -Wnull-dereference -Wuseless-cast -Wshadow -Weffc++ -Wpedantic -Wvla -O4 -flto -march=native -mtune=native -g -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H programs/tgetopt.cpp
g++-5 -o gunzip   -std=c++14 -I. -Icommon -lpthread -Iexternal/type_safe/include -Iexternal/type_safe/external/debug_assert -Wall -Wundef -Wrestrict -Wnull-dereference -Wuseless-cast -Wshadow -Weffc++ -Wpedantic -Wvla -O4 -flto -march=native -mtune=native -g -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H programs/gunzip.o programs/prog_util.o programs/tgetopt.o libdeflate.a -lrt
/usr/bin/ld: /tmp/cclubzas.ltrans0.ltrans.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by sjackman** [comment]
```sh
g++-5 -o gunzip   -std=c++14 -I. -Icommon -lpthread -Iexternal/type_safe/include -Iexternal/type_safe/external/debug_assert -Wall -Wundef -Wrestrict -Wnull-dereference -Wuseless-cast -Wshadow -Weffc++ -Wpedantic -Wvla -O4 -flto -march=native -mtune=native -g -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H programs/gunzip.o programs/prog_util.o programs/tgetopt.o libdeflate.a -lrt
```
The `-lpthread` is in the wrong location on this command line. All the `-l` options need to occur after the object files `programs/gunzip.o programs/prog_util.o programs/tgetopt.o` where the `-lrt` is currently found.

**Comment by sjackman** [comment]
A hack fix for now would be either
```ruby
inreplace "Makefile", " -lpthread", " -pthread"
```
or
```ruby
inreplace "Makefile", " -lrt", " -lpthread -lrt"
```

**Comment by sjackman** [comment]
It'd be good to report this bug upstream. It should be easily reproducible on any Ubuntu system.

**Comment by tseemann** [comment]
@tseemann reported upstream, added hack w/ note - thank you!

**Comment by tseemann** [comment]
Fails on macos now:
```
==> make V=1
ar cr libdeflate.a 
CC="g++-9" CFLAGS=" -std=c++14 -I. -Icommon -lpthread -Iexternal/type_safe/include -Iexternal/type_safe/external/debug_assert -Wall -Wundef -Wrestrict -Wnull-dereference -Wuseless-cast -Wshadow -Weffc++ -Wpedantic -Wvla -O4 -flto -march=native -mtune=native -g -D_POSIX_C_SOURCE=200809L -D_FILE_OFFSET_BITS=64 -DHAVE_CONFIG_H" programs/detect.sh > programs/config.h
ar: no archive members specified
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make: *** [libdeflate.a] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by Piezoid** [comment]
The (empty) static lib is now disabled on master.
Link argument order should also be fixed.

Imho, it is a bit early for a distributed release. But at least this will allow to sort out bugs on macos.

I didn't try at all to build on macos, nor do I have the hardware to do so.
The linux specific syscalls (non posix madvises) should be disabled by the preprocessor.

**Comment by sjackman** [comment]
Thanks for your help, Maël!

> Imho, it is a bit early for a distributed release. But at least this will allow to sort out bugs on macos.

In your opinion, should we close this PR, and wait for a stable release?

**Comment by tseemann** [comment]
I would just add `caveats` section about stability; but i will defer to you

**Comment by sjackman** [comment]
> Not sure why you put a requirement on gcc for openmp, pugz uses plain pthread and compile fine with clang on linux.

@tseemann Could you please remove the `gcc` dependency and `fails_with :clang`?

**Pull request closed without merging**
