### PR TITLE
ntjoin 1.0.2

### PR DESCRIPTION
**Pull request by lcoombe**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by lcoombe** [comment]
Error: 
```
==> brew linkage --test brewsci/bio/ntjoin
Missing libraries:
  libz-eb09ad1d.so.1.2.3
==> FAILED
```
Not sure what this is due to?

**Comment by tseemann** [comment]
@lcoombe 

```
f OS.mac?
    depends_on "gcc" # for openmp
  else
    depends_on "zlib"
  end
```

replace with

```

  depends_on "gcc" if OS.mac? # for openmp

uses_from_macos "zlib"
```

**Comment by lcoombe** [comment]
Looks like I get the same error..

**Comment by sjackman** [comment]
```
==> brew linkage --test brewsci/bio/ntjoin
Missing libraries:
  libz-eb09ad1d.so.1.2.3
==> FAILED
```
https://github.com/brewsci/homebrew-bio/pull/966/checks?check_run_id=520823932#step:6:2144

Check the output of `brew linkage --reverse ntjoin`.

**Comment by lcoombe** [comment]
Thanks @sjackman  - I'm not totally sure what I'm looking for in that output..
Here's a bit of it:
```
[lcoombe@hpce705 homebrew-bio]$ brew linkage --reverse ntjoin |grep -A1 -B1 "libz"
  libexec/lib/python3.7/site-packages/igraph/.libs/libxml2-e04a0072.so.2.7.6
  libexec/lib/python3.7/site-packages/igraph/.libs/libz-eb09ad1d.so.1.2.3
  libexec/lib/python3.7/site-packages/igraph/_igraph.cpython-37m-x86_64-linux-gnu.so
--
  libexec/lib/python3.7/site-packages/pysam/liblzma-75668d9c.so.0.0.0
  libexec/lib/python3.7/site-packages/pysam/libz-eb09ad1d.so.1.2.3

--

/projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/igraph/.libs/libz-eb09ad1d.so.1.2.3
  libexec/lib/python3.7/site-packages/igraph/_igraph.cpython-37m-x86_64-linux-gnu.so
--

/projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./libz-eb09ad1d.so.1.2.3
  libexec/lib/python3.7/site-packages/pysam/libcalignedsegment.cpython-37m-x86_64-linux-gnu.so
--

/projects/btl/lcoombe/linuxbrew/lib/libz.so.1
  libexec/bin/src/indexlr
--

libz-eb09ad1d.so.1.2.3
  libexec/lib/python3.7/site-packages/igraph/.libs/libxml2-e04a0072.so.2.7.6
```

**Comment by sjackman** [comment]
Could you please create a gist of the complete output of `brew linkage --reverse ntjoin`?

**Comment by lcoombe** [comment]
For sure!
https://gist.github.com/lcoombe/bc478d482f999e5dfe0a58250cfa5dd0

**Comment by sjackman** [comment]
I don't know why this worked before, and why it's stopped working now. That's a bit of a mystery to me. Could you please run `brew linkage --reverse ntjoin` for ntjoin 1.0.1 and for 1.0.2 and diff the two, and post the diff here? You can use triple back tick diff to syntax highlight the diff.

**Comment by lcoombe** [comment]
Yes it is strange to me -- the only changes were in the python code and the Makefile, nothing with the C++ code..

I uploaded the v1.0.1 full `brew linkage --reverse ntjoin` output here: https://gist.github.com/lcoombe/878820151db654822e0a78ff13591610

The diff:
```
[lcoombe@hpce705 linuxbrew]$ diff <(sort ntjoin.linkage.reverse.1.0.1.log |uniq) <(sort ntjoin.linkage.reverse.log |uniq) 
```
```
3a4,25
>   libexec/lib/python3.7/site-packages/igraph/.libs/libxml2-e04a0072.so.2.7.6
>   libexec/lib/python3.7/site-packages/igraph/.libs/libz-eb09ad1d.so.1.2.3
>   libexec/lib/python3.7/site-packages/numpy/core/_multiarray_tests.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/core/_operand_flag_tests.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/core/_rational_tests.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/core/_struct_ufunc_tests.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/core/_umath_tests.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/fft/_pocketfft_internal.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/.libs/libgfortran-ed201abd.so.3.0.0
>   libexec/lib/python3.7/site-packages/numpy/.libs/libopenblasp-r0-34a18dc3.3.7.so
>   libexec/lib/python3.7/site-packages/numpy/linalg/lapack_lite.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/linalg/_umath_linalg.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_bit_generator.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_bounded_integers.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_common.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_generator.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_mt19937.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/mtrand.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_pcg64.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_philox.cpython-37m-x86_64-linux-gnu.so
>   libexec/lib/python3.7/site-packages/numpy/random/_sfc64.cpython-37m-x86_64-linux-gnu.so
```
```
22,28c44,62
< /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.1/libexec/lib/python3.7/site-packages/pysam/./libbz2-13e8c345.so.1.0.4
< /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.1/libexec/lib/python3.7/site-packages/pysam/./libcbcftools.cpython-37m-x86_64-linux-gnu.so
< /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.1/libexec/lib/python3.7/site-packages/pysam/./libchtslib.cpython-37m-x86_64-linux-gnu.so
< /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.1/libexec/lib/python3.7/site-packages/pysam/./libcsamtools.cpython-37m-x86_64-linux-gnu.so
< /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.1/libexec/lib/python3.7/site-packages/pysam/./libcutils.cpython-37m-x86_64-linux-gnu.so
< /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.1/libexec/lib/python3.7/site-packages/pysam/./liblzma-75668d9c.so.0.0.0
< /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.1/libexec/lib/python3.7/site-packages/pysam/./libz-eb09ad1d.so.1.2.3
---
> libgfortran-ed201abd.so.3.0.0
> libstdc++.so.6
> libz-eb09ad1d.so.1.2.3
> /projects/btl/lcoombe/linuxbrew/Cellar/glibc/2.23/lib/libc.so.6
> /projects/btl/lcoombe/linuxbrew/Cellar/glibc/2.23/lib/libdl.so.2
> /projects/btl/lcoombe/linuxbrew/Cellar/glibc/2.23/lib/libgcc_s.so.1
> /projects/btl/lcoombe/linuxbrew/Cellar/glibc/2.23/lib/libm.so.6
> /projects/btl/lcoombe/linuxbrew/Cellar/glibc/2.23/lib/libpthread.so.0
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/igraph/.libs/libxml2-e04a0072.so.2.7.6
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/igraph/.libs/libz-eb09ad1d.so.1.2.3
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/numpy/core/../.libs/libopenblasp-r0-34a18dc3.3.7.so
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/numpy/linalg/../.libs/libopenblasp-r0-34a18dc3.3.7.so
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./libbz2-13e8c345.so.1.0.4
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./libcbcftools.cpython-37m-x86_64-linux-gnu.so
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./libchtslib.cpython-37m-x86_64-linux-gnu.so
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./libcsamtools.cpython-37m-x86_64-linux-gnu.so
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./libcutils.cpython-37m-x86_64-linux-gnu.so
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./liblzma-75668d9c.so.0.0.0
> /projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/pysam/./libz-eb09ad1d.so.1.2.3
```
```
31d64
< /projects/btl/lcoombe/linuxbrew/lib/libgomp.so.1
```
```
36d68
< /projects/btl/lcoombe/linuxbrew/lib/libxml2.so.2
```

**Comment by sjackman** [comment]
The issues appears to be that

1.0.1
```
/projects/btl/lcoombe/linuxbrew/lib/libz.so.1
  libexec/bin/src/indexlr
  libexec/lib/python3.7/site-packages/igraph/_igraph.cpython-37m-x86_64-linux-gnu.so
  libexec/lib/python3.7/site-packages/pybedtools/cbedtools.cpython-37m-x86_64-linux-gnu.so
  libexec/lib/python3.7/site-packages/pybedtools/featurefuncs.cpython-37m-x86_64-linux-gnu.so
```

changed to
1.0.2
```
/projects/btl/lcoombe/linuxbrew/lib/libz.so.1
  libexec/bin/src/indexlr
  libexec/lib/python3.7/site-packages/pybedtools/cbedtools.cpython-37m-x86_64-linux-gnu.so
  libexec/lib/python3.7/site-packages/pybedtools/featurefuncs.cpython-37m-x86_64-linux-gnu.so

libz-eb09ad1d.so.1.2.3
  libexec/lib/python3.7/site-packages/igraph/.libs/libxml2-e04a0072.so.2.7.6

/projects/btl/lcoombe/linuxbrew/Cellar/ntjoin/1.0.2/libexec/lib/python3.7/site-packages/igraph/.libs/libz-eb09ad1d.so.1.2.3
  libexec/lib/python3.7/site-packages/igraph/_igraph.cpython-37m-x86_64-linux-gnu.so
```

So it's a problem I think with `igraph/.libs/libxml2-e04a0072.so.2.7.6` linking to `libz-eb09ad1d.so.1.2.3` instead of the desired `/projects/btl/lcoombe/linuxbrew/lib/libz.so.1`.
I can't say off the top of my head why that would be. Gives you a lead to troubleshoot though, if you're into it. You could use `brew install -dv ntjoin` and look into the build log of `igraph`, and perhaps diff the build log from 1.0.1 to 1.0.2 to see why `igraph` is no longer finding the brewed `libz` and is instead building its own.

**Comment by lcoombe** [comment]
Sorry but I'm a bit lost with what to try...`igraph` pours from a bottle fine, so I don't really see anything in the log that looks helpful:
```
==> Pouring igraph-0.8.1.x86_64_linux.bottle.tar.gz
tar xof /home/lcoombe/.cache/Homebrew/downloads/ddec3a4db9b9cdaf4a87ccb05b96eb8bce101861a825de511a64598665e1806e--igraph-0.8.1.x86_64_linux.bottle.tar.gz -C /tmp/d20200330-52238-1chymps
cp -pR /tmp/d20200330-52238-1chymps/igraph/. /projects/btl/lcoombe/linuxbrew/Cellar/igraph
chmod -Rf +w /tmp/d20200330-52238-1chymps
/projects/btl/lcoombe/linuxbrew/bin/patchelf --force-rpath --set-rpath /projects/btl/lcoombe/linuxbrew/lib:/projects/btl/lcoombe/linuxbrew/Cellar/igraph/0.8.1/lib:/projects/btl/lcoombe/linuxbrew/opt/gmp/lib:/projects/btl/lcoombe/linuxbrew/opt/glpk/lib:/projects/btl/lcoombe/linuxbrew/opt/gdbm/lib:/projects/btl/lcoombe/linuxbrew/opt/openssl@1.1/lib:/projects/btl/lcoombe/linuxbrew/opt/ncurses/lib:/projects/btl/lcoombe/linuxbrew/opt/readline/lib:/projects/btl/lcoombe/linuxbrew/opt/zlib/lib:/projects/btl/lcoombe/linuxbrew/opt/sqlite/lib:/projects/btl/lcoombe/linuxbrew/opt/xz/lib:/projects/btl/lcoombe/linuxbrew/opt/bzip2/lib:/projects/btl/lcoombe/linuxbrew/opt/libffi/lib:/projects/btl/lcoombe/linuxbrew/opt/python/lib:/projects/btl/lcoombe/linuxbrew/opt/libxml2/lib:/projects/btl/lcoombe/linuxbrew/opt/mpfr/lib:/projects/btl/lcoombe/linuxbrew/opt/libmpc/lib:/projects/btl/lcoombe/linuxbrew/opt/isl@0.18/lib:/projects/btl/lcoombe/linuxbrew/opt/gcc/lib:/projects/btl/lcoombe/linuxbrew/opt/openblas/lib /projects/btl/lcoombe/linuxbrew/Cellar/igraph/0.8.1/lib/libigraph.so.0.0.0
==> Finishing up
ln -s ../Cellar/igraph/0.8.1/include/igraph igraph
ln -s ../Cellar/igraph/0.8.1/lib/libigraph.a libigraph.a
ln -s ../Cellar/igraph/0.8.1/lib/libigraph.so libigraph.so
ln -s ../Cellar/igraph/0.8.1/lib/libigraph.so.0 libigraph.so.0
ln -s ../Cellar/igraph/0.8.1/lib/libigraph.so.0.0.0 libigraph.so.0.0.0
ln -s ../../Cellar/igraph/0.8.1/lib/pkgconfig/igraph.pc igraph.pc
==> Summary
🍺  /projects/btl/lcoombe/linuxbrew/Cellar/igraph/0.8.1: 90 files, 9.8MB
```

One of the only main differences seems to be a new version of igraph, but I don't see any major changes in the formula??

**Comment by sjackman** [comment]
I should have been more specific, sorry. I meant the build log of the Python package `python-igraph` built by this line:
https://github.com/brewsci/homebrew-bio/pull/966/files#diff-ef6c4a56ebd7433879136a72b749487fR33

If the version of `python-igraph` changed from the last release of `ntjoin` to this release, you could try pinning `python-igraph` to the previous version, and see if that helps.

**Comment by lcoombe** [comment]
Thanks for the suggestion, Shaun! 
To get the older `python-igraph` version to work, I had to remove the `brew` `igraph` dependency (otherwise the versions wouldn't match), and add a dependency on `libxml2`

**Comment by sjackman** [comment]
Wow! I didn't earnestly except that to work, but I'm glad that it did!

**Pull request merged**
