### PR TITLE
Update CIRCLE XCode to 10.3, avoid sierra gcc

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Build-agent version 1.0.17376-9104d073 (2019-10-02T15:59:42+0000)
Creating a dedicated VM with xcode:10.3 image
failed to create host: Image xcode:10.3 is not supported
failed to create host: Image xcode:10.3 is not supported
```
https://xcodereleases.com/

**Comment by sjackman** [comment]
```
macOS: 10.14.4-x86_64
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/7686

macOS 10.14 is Mojave.
@tseemann Can we please instead use a version of XCode that corresponds to 10.13 High Sierra? That's the oldest version of macOS that Homebrew supports.

**Comment by tseemann** [comment]
@sjackman Sorry - I thought I chose the one corresponding to High Sierra. XCode versions are very confusing.

**Comment by sjackman** [comment]
Thanks!

**Pull request merged**
