### PR TITLE
edirect: import from brewsci/science (9.20)

### PR DESCRIPTION
**Pull request by suujia**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----
Built upon: #241  
```
Can't locate HTML/Entities.pm in @INC
``` 
```
Error: No such file or directory - README
```
also upgraded to version 8.70

### CODE REVIEW

**Comment by suujia** [comment]
``` 
Apple no longer ships openssl headers:
http://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html
``` 

For the follow errors: 
```
! Installing the dependencies failed: Module 'Net::HTTP' is not installed
! Bailing out the installation for libwww-perl-6.33.
! Installing the dependencies failed: Module 'Net::HTTPS' is not installed, Module 'LWP::UserAgent' is not installed
! Bailing out the installation for LWP-Protocol-https-6.07.
```
google searches say to install via system's package manager (apt-get, yum, etc) to install the missing portions of perl rather than using cpanm 
eg. `sudo yum install perl-LWP-Protocol-https` 
any thoughts?

**Comment by sjackman** [comment]
It succeeded on TravisCI. That's promising!

> google searches say to install via system's package manager (apt-get, yum, etc) to install the missing portions of perl rather than using cpanm
eg. sudo yum install perl-LWP-Protocol-https
any thoughts?

Linuxbrew is often used to install software on systems where the user is not able to use `sudo`, so we're not able to use the host's package manager, sadly.

**Comment by sjackman** [comment]
```
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz ... OK
Configuring Net-SSLeay-1.85 ... OK
Building and testing Net-SSLeay-1.85 ... ! Installing Net::SSLeay failed. See /tmp/edirect-20180518-8825-1iff61q/edirect/.brew_home/.cpanm/work/1526661049.8893/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.056.
! Installing the dependencies failed: Module 'IO::Socket::SSL' is not installed
! Bailing out the installation for LWP-Protocol-https-6.07.
FAIL
22 distributions installed
```
https://circleci.com/gh/brewsci/homebrew-bio/2633

Can you reproduce this issue locally or on the linuxbrew/linuxbrew Docker image, so that we can read the `build.log` file?

**Comment by tseemann** [comment]
I could never resolve this Perl problem after spending many hours on it.

**Comment by sjackman** [comment]
Could you please post on https://gist.github.com the `build.log` of the failed `Net::SSLeay` installation? I use the command line `gist` program for this purpose, or you can use the web interface.

**Comment by sjackman** [comment]
> Building and testing Net-SSLeay-1.85 ... ! Installing Net::SSLeay failed. See /tmp/edirect-20180612-13023-2abr9q/edirect/.brew_home/.cpanm/work/1528826396.13106/build.log for details. Retry with --force to force install it.

`brew gist-logs` unfortunately does not include this `build.log` file in its gist. You'll have to find and gist that file manually.

**Comment by suujia** [comment]
Updated to version 9.20. Hmm, same error occuring on circle ci. Even though I passed` brew audit strict` and `brew test` in linuxbrew/linuxbrew image.

**Comment by tseemann** [comment]
@suujia What is the comma in `-l prefix/perl5,` ?   Is that just an alternative test folder to check if it works?  And not overwrite the `perl5` foldeR?

**Comment by sjackman** [comment]
Nah just a typo.

**Comment by suujia** [comment]
Good guess! But my bad, yeah it was just a typo.

**Comment by sjackman** [comment]
Are you able to reproduce this issue locally or in Docker? If so, gist the `build.log` file mentioned here:
```
Building and testing Net-SSLeay-1.85 ... ! Installing Net::SSLeay failed.
See /tmp/edirect-20180612-13023-2abr9q/edirect/.brew_home/.cpanm/work/1528826396.13106/build.log
for details. Retry with --force to force install it.
```

**Comment by suujia** [comment]
bumped it up to version 9.30. 

I have built it, audit strict, and brew test and it has all passed on this version of the formula on linuxbrew/linuxbrew. On my local machine (mac) i received message: 
```
sh: line 1: 88979 Segmentation fault: 11  /home/schen/.homebrew/Cellar/edirect/9.30/bin/efetch --version 2>&1
Error: brewsci/science/edirect: failed
<0> expected but was
<139>.
```

**Comment by tseemann** [comment]
@suujia `rewsci/science/edirect` should that be `brewsci/bio` ?

**Comment by sjackman** [comment]
```
--> Working on Net::SSLeay
Fetching http://www.cpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz ... OK
Configuring Net-SSLeay-1.85 ... OK
Building and testing Net-SSLeay-1.85 ... ! Installing Net::SSLeay failed. See /tmp/edirect-20180712-10041-1og3fhq/edirect/.brew_home/.cpanm/work/1531429483.10109/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Net::SSLeay' is not installed
! Bailing out the installation for IO-Socket-SSL-2.056.
FAIL
```

@suujia Have you been able to reproduce this error in Docker?

**Comment by suujia** [comment]
Yes I have just tried it again, and `brew install`,  `brew audit --strict`, `brew test`, `brew postinstall `all run perfectly on docker.

**Comment by sjackman** [comment]
Can you rebase this PR onto `master` and, fingers crossed, it'll magically start working?

**Comment by tseemann** [comment]
I think it might just need `depends_on "zlib"` to build Net::SSLeay 🛑

**Comment by tseemann** [comment]
SOLVED AND PULLED in #377 

Lesson learnt!

**Comment by suujia** [comment]
Thanks for the help!! 😃

**Pull request closed without merging**
