### PR TITLE
salmon 1.1

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
I thought `cmake -DUSE_SHARED_LIBS=1` might help.

**Comment by tseemann** [comment]
Why is the salmon test installing trinity?
```
==> brew test brewsci/bio/salmon --verbose
Testing brewsci/bio/salmon
==> /home/linuxbrew/.linuxbrew/Cellar/salmon/1.1.0/bin/salmon --version 2>&1

==> brew fetch --retry brewsci/bio/trinity
==> Fetching trinity from brewsci/bio
==> Downloading https://linuxbrew.bintray.com/bottles-bio/trinity-2.8.3_1.x86_64_linux.bottle.tar.gz
```

**Comment by sjackman** [comment]
Trinity depends on Salmon, so changing Salmon tests that it didn't break Trinity.

**Comment by sjackman** [comment]
If `trinity` is broken, you can start by updating `trinity`, if you're inclined to do that.
If `trinity` is broken, and you're not inclined to fix it, we can consider removing `trinity`.

**Comment by sjackman** [comment]
Superseded by PR https://github.com/brewsci/homebrew-bio/pull/984

**Pull request closed without merging**
