### PR TITLE
gmap-gsnap 2019-09-12

### PR DESCRIPTION
**Pull request by czhu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by tseemann** [comment]
When i run the test locally I get this:
```
gsnap --version
Note: gsnap.avx2 does not exist.  For faster speed, may want to compile package on an AVX2 machine
Note: gsnap.sse42 does not exist.  For faster speed, may want to compile package on an SSE4.2 machine
Note: gsnap.sse41 does not exist.  For faster speed, may want to compile package on an SSE4.1 machine
Note: gsnap.ssse3 does not exist.  For faster speed, may want to compile package on an SSSE3 machine
Note: gsnap.sse2 does not exist.  For faster speed, may want to compile package on an SSE2 machine
```

**Comment by sjackman** [comment]
The oldest CPU that Homebrew supports on macOS is Nehalem, which supports SSE 4.2
https://en.wikipedia.org/wiki/Nehalem_(microarchitecture)
https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures#Roadmap

So I agree with Torsten. Let's target Nehalem / SSE4.2. We could compile more than one executable, if we wanted, say `sse4.2` and `avx512`.

**Comment by czhu** [comment]
> So I agree with Torsten. Let's target Nehalem / SSE4.2. We could compile more than one executable, if we wanted, say `sse4.2` and `avx512`.

the latest commit targets SSE4.2 with the flag "--with-simd-level=sse42"

**Comment by sjackman** [comment]
Great! Looks good to me!
@tseemann Could you please test this PR?

**Comment by tseemann** [comment]
```
brewsci-pull https://github.com/brewsci/homebrew-
bio/pull/814
==> Fetching patch
Patch: https://github.com/brewsci/homebrew-bio/pull/814.patch
#=#=#
##O#- #
##O=#  #
#=#=-#  #

==> Applying patch
Applying: gmap-gsnap 2019-09-12
==> Patch closes issue #814
==> Fetching patch (bottle commit)
Patch: https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:maste
r...pr-814.patch
#=#=#
##O#- #
curl: (22) The requested URL returned error: 404 Not Found

Error: Failure while executing; `/home/linuxbrew/.linuxbrew/opt/curl/bin/curl
 -q --globoff --show-error --user-agent Linuxbrew/2.1.15-95-g3944416\ \(Linux
\;\ x86_64\ \"Red\ Hat\ Enterprise\ Linux\ Server\ release\ 7.7\ \(Maipo\)\"\
)\ curl/7.66.0 --fail --progress-bar --location --remote-time --continue-at 0
 --output /home/linuxbrew/.cache/Homebrew/brewsci:master...pr-814.patch https
://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-814.p
atch` exited with 22. Here's the output:
#=#=#
##O#- #
curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by jonchang** [comment]
I've re-triggered the bottle transfer.

**Comment by tseemann** [comment]
```
linuxbrew@deepthought:~ $ brewsci-pull https://github.com/brewsci/homebrew-bio/pull/814
==> Fetching patch
Patch: https://github.com/brewsci/homebrew-bio/pull/814.patch
#=#=-#  #
==> Applying patch
Applying: gmap-gsnap 2019-09-12
==> Patch closes issue #814
==> Fetching patch (bottle commit)
Patch: https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-814.patch
curl: (22) The requested URL returned error: 404 Not Found

Error: Failure while executing; `/home/linuxbrew/.linuxbrew/opt/curl/bin/curl -q --globoff --show-error --user-agent Linuxbrew/2.1.15-107-g5da322d\ \(Linux\;\ x86_64\ \"Red\ Hat\ Enterprise\ Linux\ Server\ release\ 7.7\ \(Maipo\)\"\)\ curl/7.66.0 --fail --progress-bar --location --remote-time --continue-at 0 --output /home/linuxbrew/.cache/Homebrew/brewsci:master...pr-814.patch https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-814.patch` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404 Not Found
```

Failed again @jonchang ?

**Comment by jonchang** [comment]
The bottles are already published it seems - you might just want to build the bottle block yourself.

https://7845-105587756-gh.circle-artifacts.com/0/bottles/gmap-gsnap--2019-09-12.mojave.bottle.json
https://7845-105587756-gh.circle-artifacts.com/0/bottles/gmap-gsnap--2019-09-12.x86_64_linux.bottle.json

**Comment by tseemann** [comment]
@jonchang the SHA in those JSON files don't seem to match with what gets downloaded.

```
Error: SHA256 mismatch
Expected: 19a643b9dc76c497865d910dd38f758ea56ba0c08954cbb212aba5490f0d907b
  Actual: b4d6d09f1b7f4633054f9219d105a6fe459f71e7bcd7e35937852df240452a59
```

I think we might need a `revision 1` ?

**Comment by jonchang** [comment]
The bottle upload probably succeeded in an earlier push but not in a later
push, and were mistakenly published somehow.

I suggest:
* delete the already-published bottles on bintray (that shouldn't be in use)
* restart the CI job

**Pull request closed without merging**
