### PR TITLE
abacas 1.3.1

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Error: 1 problem in 1 formula
brewsci/bio/abacas:
  * C: 4: col 3: http://abacas.sourceforge.net/ should be `https://abacas.sourceforge.io/`
```

But that website doesn't work .... ARGH

**Comment by tseemann** [comment]
@sjackman can i still pull this in?  
i don't know how to resolve the circular problem with the URL audit.

**Comment by sjackman** [comment]
https://abacas.sourceforge.io/ works for me, though it just redirects to http://abacas.sourceforge.net/

**Comment by tseemann** [comment]
Yes it works for me too, but it never works in CIRCLE for some reason. 
Maybe the `curl` (?) check doesn't like redirects?

**Comment by sjackman** [comment]
It may not like https that redirects to http. How did you fix this in the end?

**Pull request closed without merging**
