### PR TITLE
gmap-gsnap 2019-03-15

### PR DESCRIPTION
**Pull request by czhu**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
```
==> brew style brewsci/bio/gmap-gsnap
C: 32:  1: EOS is not aligned with def caveats; <<~EOS.
```

https://dev.azure.com/brewsci/brewsci/_build/results?buildId=492&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=2770&lineEnd=2776&colStart=1&colEnd=1

**Comment by czhu** [comment]
should be fixed now

**Comment by sjackman** [comment]
The CircleCI build on Linux failed. Succeeded on macOS though.
```
gcc-5 -DHAVE_CONFIG_H -I.     -pthread -DTARGET=\"x86_64-unknown-linux-gnu\" -DGMAPDB=\"/home/linuxbrew/.linuxbrew/Cellar/gmap-gsnap/2019-03-15/share\" -DMAX_STACK_READLENGTH=300 -DGSNAP=1 -DLARGE_GENOMES=1 -mpopcnt -DHAVE_SSE2=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -DHAVE_SSE4_2=1 -DHAVE_AVX2=1 -DHAVE_AVX512=1 -msse2 -mssse3 -msse4.1 -msse4.2 -mavx2 -mbmi2 -mavx512f -mavx512cd -O3 -fomit-frame-pointer -MT gsnapl_avx512-merge-diagonals-simd-uint8.o -MD -MP -MF .deps/gsnapl_avx512-merge-diagonals-simd-uint8.Tpo -c -o gsnapl_avx512-merge-diagonals-simd-uint8.o `test -f 'merge-diagonals-simd-uint8.c' || echo './'`merge-diagonals-simd-uint8.c
merge-uint8.c: In function ‘merge_4x4’:
merge-uint8.c:72:29: error: incompatible type for argument 1 of ‘_mm_max_epu64’
   *vMergedB = _mm_max_epu64(vTmp, vMax);
                             ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:53:0,
                 from merge-uint8.c:15:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h:8028:1: note: expected ‘__m128i {aka __vector(2) long long int}’ but argument is of type ‘__m256i {aka __vector(4) long long int}’
 _mm_max_epu64 (__m128i __A, __m128i __B)
 ^
merge-uint8.c:72:35: error: incompatible type for argument 2 of ‘_mm_max_epu64’
   *vMergedB = _mm_max_epu64(vTmp, vMax);
                                   ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:53:0,
                 from merge-uint8.c:15:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h:8028:1: note: expected ‘__m128i {aka __vector(2) long long int}’ but argument is of type ‘__m256i {aka __vector(4) long long int}’
 _mm_max_epu64 (__m128i __A, __m128i __B)
 ^
Makefile:33056: recipe for target 'gsnapl_avx512-merge-uint8.o' failed
make[2]: *** [gsnapl_avx512-merge-uint8.o] Error 1
```
https://circleci.com/gh/brewsci/homebrew-bio/5743

Are you able to troubleshoot this issue yourself, or would you like to open an issue with the upstream developer?

**Comment by sjackman** [comment]
Are you able to reproduce this build failure on your own machine?

**Comment by czhu** [comment]
on my Linux machine (CentOS 7.4) it builds fine with `brew install --verbose --build-bottle brewsci/bio/gmap-gsnap` and passes the `make check`. How do I replicate?

**Comment by sjackman** [comment]
If you have access to Docker, you can try to replicated the issue in the `linuxbrew/brew` Docker image. I use Docker for macOS myself.

**Comment by czhu** [comment]
unfortunately, I don't. Shall we drop this or make it Mac only?

**Comment by sjackman** [comment]
I tested building this PR myself just now in the `linuxbrew/brew` Docker image, and it worked just fine. That same Docker image is also used by CircleCI. Could you try rebasing this PR onto master, to see if it was perhaps a transient issue?

**Comment by czhu** [comment]
seems the same error. any idea?

**Comment by sjackman** [comment]
I do have one idea. Can you test whether `brew install --build-bottle gmap-gsnap` fails? When we build a bottle, we disable support for AVX-512, so that the compiled bottle can run on any Intel CPU. My guess is that it's trying to use AVX-512 instructions (probably because it detects that the CPU supports them) even though they're disabled.

**Comment by czhu** [comment]
on my CentOS machine `brew install --build-bottle gmap-gsnap` runs fine.

**Comment by sjackman** [comment]
Yes, `brew install --build-bottle gmap-gsnap` runs fine for me as well on `CPU: dual-core 64-bit haswell`. AVX-512 was introduced with Skylake. CircleCI is running on Skylake CPUs with AVX-512.
What does `brew config | grep CPU` report for you?

**Comment by czhu** [comment]
CPU: 80-core 64-bit westmere. I have gcc installed with brew as well. not sure which gcc it uses to build the bottle.

**Comment by sjackman** [comment]
I can reproduce this build failure on a system at work with an Intel Skylake CPU.
```
merge-uint8.c:72:29: error: incompatible type for argument 1 of '_mm_max_epu64'
   *vMergedB = _mm_max_epu64(vTmp, vMax);
```
See https://gist.github.com/sjackman/3610588184f0fb5c8afbcefbc8ea25fb
Do you have access to a Skylake system?

**Comment by czhu** [comment]
My Mac has newer CPU kabylake but it doesn't run Linux.

**Comment by sjackman** [comment]
Have you tried Docker for macOS? I quite like it.

**Comment by sjackman** [comment]
This seems like an upstream bug to me though. Would you like to report it to the upstream developer of `gmap-gsnap`?

**Pull request closed without merging**
