### PR TITLE
dsh-bio 1.3.2

### PR DESCRIPTION
**Pull request by heuermh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by sjackman** [comment]
The default branch of Brewsci/bio recently changed from `master` to `develop`. Please run…

```sh
cd $(brew --repo brewsci/bio)
git remote set-head origin -a
```

Thank you!

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to Brewsci/bio! 🌟

**Comment by heuermh** [comment]
Thank you, @sjackman.

Git complained a bit, but it seems to have done the right thing
```bash
$ cd $(brew --repo brewsci/bio)

$ pwd
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio

$ git remote set-head origin -a
error: Not a valid ref: refs/remotes/origin/develop
origin/HEAD set to develop

$ brew update
Updated 4 taps (homebrew/core, homebrew/cask, homebrew/cask-fonts and brewsci/bio).
==> Updated Formulae
brewsci/bio/dsh-bio ✔
...

$ brew upgrade
...
brewsci/bio/dsh-bio 1.3.1 -> 1.3.2
...
🍺  /usr/local/Cellar/dsh-bio/1.3.2: 132 files, 18.6MB, built in 6 seconds
Removing: /usr/local/Cellar/dsh-bio/1.3.1... (129 files, 14MB)
```

**Comment by sjackman** [comment]
```console
$ git remote set-head origin -a
error: Not a valid ref: refs/remotes/origin/develop
origin/HEAD set to develop
```

Strange. Try maybe…
```
cd $(brew --repo brewsci/bio)
git fetch origin develop
git remote set-head origin -a
```

@heuermh Would you like to join Brewsci/bio as a maintainer?

**Comment by heuermh** [comment]
```
~
$ cd $(brew --repo brewsci/bio)

homebrew-bio master
$ git fetch origin develop
From https://github.com/brewsci/homebrew-bio
 * branch            develop    -> FETCH_HEAD

homebrew-bio master
$ git remote set-head origin -a
error: Not a valid ref: refs/remotes/origin/develop
origin/HEAD set to develop

homebrew-bio master
$ git remote --verbose
origin	https://github.com/brewsci/homebrew-bio (fetch)
origin	https://github.com/brewsci/homebrew-bio (push)

homebrew-bio master
$ git branch
  adam-0.25.0
  adam-0.26.0
  adam-0.27.0
  adam-0.28.0
  adam-0.29.0
  adam-0.30.0
  adam-0.31.0
  cannoli-0.3.0
  cannoli-0.6.0
  cannoli-0.7.0
  cannoli-0.8.0
  cannoli-0.9.0
  dsh-bio-1.2
  dsh-bio-1.2.1
  dsh-bio-1.3
  dsh-bio-1.3.1
  dsh-bio-1.3.2
* master
```
I'm not sure what `FETCH_HEAD` means, perhaps I need to checkout `develop`?


> Would you like to join Brewsci/bio as a maintainer?

Sure, but I might not be much help when things don't go right.  😉

**Comment by sjackman** [comment]
> perhaps I need to checkout develop?

Good idea. That should do the trick.

> Sure, but I might not be much help when things don't go right. 😉

Great! I've added you to the GitHub team and invited you to join the Slack. Welcome!

Hah. No worries. You can start by merging your own PRs, and feel free to start merging PRs from other people that just bump the version and CI is 💚. Feel free to tag me if you have any questions.

**Comment by heuermh** [comment]
Thanks, will do!

**Pull request merged**
