### PR TITLE
samclip 0.2 (new formula)

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Error: 1 problem in 1 formula
brewsci/bio/samclip:
  * GitHub repository too new (<30 days old)
```
What can I say, I work fast when I need to.

**Comment by sjackman** [comment]
The most straight forward "fix" is to wait for the repo to be old enough. We don't currently have a simple way to ignore audit failures, which prevent the `collect-bottles` CircleCI step from running.

**Comment by sjackman** [comment]
The way I tackle getting rid of poor quality alignments is by filtering on the alignment score `AS` and number of mismatches `NM`. I typically require that AS ≥ 100 and NM < 5. I filter using `sambamba`, for example https://github.com/sjackman/psitchensismt/blob/b89390848b85461a64aa50c3d6ce3a1a2f60724c/Makefile#L181

**Comment by tseemann** [comment]
@sjackman But `AS` depends on which alignment costs you used eg +5/-4 or +1/-1 or +1/0 etc. I'm happy to take a 45bp read if it aligns fully.  The `NM` thing is useful yes, but sort of depends on readlength too.  Do you use `samtools calmd` ?   I'm surprised `samtools` can't do those filterings yet; `bcftools` can do it.

**Comment by sjackman** [comment]
> But AS depends on which alignment costs you used eg +5/-4 or +1/-1 or +1/0 etc.

Yes, I usually default `bwa mem` parameters.

> I'm happy to take a 45bp read if it aligns fully.

If the read length is variables, I use `AS / read_length ≥ 0.65`

> Do you use `samtools calmd` ?

Not typically.

> I'm surprised samtools can't do those filterings yet

Me too!

**Comment by tseemann** [comment]
Another 2-3 days to go...

```
brewsci/bio/samclip:
  * GitHub repository too new (<30 days old)
  * New formulae should not have a HEAD spec
```

**Comment by tseemann** [comment]
```
Error: 1 problem in 1 formula
brewsci/bio/samclip:
  * GitHub repository too new (<30 days old)
```

**Pull request closed without merging**
