### PR TITLE
trans-abyss: import from brewsci/science

### PR DESCRIPTION
**Pull request by gejessicama**
Decided to start all over again, now both pull requests are up :)

### CODE REVIEW

**Comment by gejessicama** [comment]
Seems like all the errors have something to do with "no formula with name 'blat'"

**Comment by gejessicama** [comment]
Oh, weird. I thought I edited the file but I don't see the changes in Files changed. Whoops.

**Comment by sjackman** [comment]
Trans-ABySS depends on BLAT which hasn't been migrated yet. Would you like to migrate it? Looking a the formula, it should be pretty straight forward.

**Comment by gejessicama** [comment]
Sorry, clearly don't know how to rebase properly

**Comment by sjackman** [comment]
```
==> brew readall --aliases brewsci/bio
Error: No available formula with the name "gmap-gsnap" 
```
https://circleci.com/gh/brewsci/homebrew-bio/2403

Could you please migrate `gmap-gsnap` if you have the time? It should be an easy migration.

**Comment by sjackman** [comment]
```
brewsci/bio/trans-abyss:
  * C: 28: col 72: Trailing whitespace detected.
  * New formulae should not have a HEAD spec
```
https://circleci.com/gh/brewsci/homebrew-bio/2415

These two style issues are easy to fix. Remove the trailing white space, and remove the `head` line.

```
==> brew test brewsci/bio/trans-abyss --verbose
Testing brewsci/bio/trans-abyss
/usr/bin/sandbox-exec -f /tmp/homebrew20180427-9291-4x9eph.sb /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/trans-abyss.rb --verbose
==> /usr/local/Cellar/trans-abyss/1.5.5/bin/transabyss --help 2>&1
Error: brewsci/bio/trans-abyss: failed
<0> expected but was
<1>.
==> FAILED
```

This one may be harder to fix, depending on why it failed. On your local machine, try…
```
brew install brewsci/bio/trans-abyss
brew test trans-abyss
```

**Comment by gejessicama** [comment]
Ah. 

`brewsci/bio/trans-abyss is missing test dependencies: picard-tools`

**Comment by suujia** [comment]
error produced locally: 

``` 
  File "/home/linuxbrew/.linuxbrew/bin/transabyss", line 18, in <module>
    from utilities.adj_utils import has_edges
  File "/home/linuxbrew/.linuxbrew/Cellar/trans-abyss/1.5.5/utilities/adj_utils.py", line 7, in <module>
    import igraph
ImportError: No module named igraph
```

**Comment by sjackman** [comment]
Superseded by PR https://github.com/brewsci/homebrew-science/pull/217

**Pull request closed without merging**
