### PR TITLE
readseq 2.1.30

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
brewsci/bio/readseq:
  * The URL http://iubio.bio.indiana.edu/soft/molbio/readseq/java/ is not reachable
```

**Comment by tseemann** [comment]
```
==> Downloading http://iubio.bio.indiana.edu/soft/molbio/readseq/java/readseq.jar
/usr/bin/curl --show-error --user-agent Homebrew/1.5.12-4-g15f01bd (Macintosh; Intel Mac OS X 10.12.6) curl/7.54.0 --fail --silent --location --remote-time --continue-at - --output /Users/distiller/Library/Caches/Homebrew/readseq-2.1.30.jar.incomplete http://iubio.bio.indiana.edu/soft/molbio/readseq/java/readseq.jar
curl: (52) Empty reply from server
Error: Failed to download resource "readseq"
Download failed: http://iubio.bio.indiana.edu/soft/molbio/readseq/java/readseq.jar
Error: 2 problems in 1 formula
brewsci/bio/readseq:
  * The URL http://iubio.bio.indiana.edu/soft/molbio/readseq/java/ is not reachable
  * Stable: The URL http://iubio.bio.indiana.edu/soft/molbio/readseq/java/readseq.jar is not reachable
```
Seems to work from other servers I try. And it worked on Linux.

**Comment by tseemann** [comment]
macOS circle can't seem to retrieve this.
It's just a JAR file, so it will be easy to build without a bottle for MacOS people.
I'm going to pull this.

**Comment by sjackman** [comment]
If you pull it without bottles, add `bottle :unneeded`

**Comment by sjackman** [comment]
The web site hosting the homepage and JAR file are not responding. I've opened PR https://github.com/brewsci/homebrew-bio/pull/596 to remove `readseq`.

**Pull request merged**
