### PR TITLE
Gatk make bottle

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
This PR indicates that it was merged, but I don't see the commit in the commit history of `master` or `develop`. Was there a force push to remove this commit? What's going on?
```
❯❯❯ grep bottle Formula/gatk.rb               develop
  bottle :unneeded
```

**Comment by sjackman** [comment]
I've cherry-picked this commit e85543270e16eb8c3c5e9d4deb50c3de22af9f56 and pushed it to `develop`.

**Comment by lbergelson** [comment]
Why was a bottle needed for gatk?  It's a prebuilt java application.

**Comment by sjackman** [comment]
To provide a second location from which to download GATK.
To make it easier to install older versions of GATK.

**Comment by lbergelson** [comment]
Ah, that makes sense, thank you.

**Pull request merged**
