### PR TITLE
ntedit 1.3.4

### PR DESCRIPTION
**Pull request by lcoombe**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by lcoombe** [comment]
Hmm.. failure seems unrelated to building ntedit?
```
==> brew install-bundler-gems
==> FAILED
```

**Comment by sjackman** [comment]
Yeah definitely not related to your PR. Another Homebrew maintainer reported a similar error, so hopefully there will be a fix coming.

**Comment by sjackman** [comment]
This issue should be resolve now. Can you try rebasing this PR onto `origin/develop`?

**Comment by lcoombe** [comment]
Rebased, and CI looks good now!

**Pull request merged**
