### PR TITLE
mlst 2.11

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Only the first 100 operations were output.
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/cpan -i XML::Parser
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/perl/post_install.01.cpan:
2018-08-05 04:08:08 +0000
/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/cpan
-i
XML::Parser
Can't load '/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/auto/POSIX/POSIX.so' for module POSIX: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/auto/POSIX/POSIX.so) at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/XSLoader.pm line 93.
 at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/POSIX.pm line 24.
Compilation failed in require at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/Net/Ping.pm line 14.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/Net/Ping.pm line 14.
Compilation failed in require at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/CPAN/Mirrors.pm line 42.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/CPAN/Mirrors.pm line 42.
Compilation failed in require at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/CPAN/FirstTime.pm line 11.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/CPAN/FirstTime.pm line 11.
Compilation failed in require at /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/CPAN/HandleConfig.pm line 585.
Loading internal logger. Log::Log4perl recommended for better logging
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.
```

**Comment by sjackman** [comment]
It looks like `brew postinstall perl` is failing when it runs the command `cpan -i XML::Parser`.
@imichka Any thoughts?

**Comment by iMichka** [comment]
Yes it is broken (again). Probably a superenv bug. I had no time to look at it.

**Comment by tseemann** [comment]
```
make[1]: Entering directory '/home/linuxbrew/.cpan/build/XML-Parser-2.44-0/Expat'
cp Expat.pm ../blib/lib/XML/Parser/Expat.pm
Running Mkbootstrap for Expat ()
chmod 644 "Expat.bs"
"/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Expat.bs ../blib/arch/auto/XML/Parser/Expat/Expat.bs 644
"/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/perl" "/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/ExtUtils/xsubpp" -noprototypes -typemap '/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/ExtUtils/typemap' -typemap '/home/linuxbrew/.cpan/build/XML-Parser-2.44-0/Expat/typemap'  Expat.xs > Expat.xsc
mv Expat.xsc Expat.c
cc -c   -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/linuxbrew/.linuxbrew/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2   -DVERSION=\"2.44\" -DXS_VERSION=\"2.44\" -fPIC "-I/home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/lib/perl5/5.28.0/x86_64-linux-thread-multi/CORE"   Expat.c
Expat.xs:14:20: fatal error: EXTERN.h: No such file or directory
compilation terminated.
Makefile:319: recipe for target 'Expat.o' failed
make[1]: *** [Expat.o] Error 1
make[1]: Leaving directory '/home/linuxbrew/.cpan/build/XML-Parser-2.44-0/Expat'
Makefile:537: recipe for target 'subdirs' failed
make: *** [subdirs] Error 2
  TODDR/XML-Parser-2.44.tar.gz
  /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make -- NOT OK
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
```

**Comment by iMichka** [comment]
https://github.com/Linuxbrew/homebrew-core/issues/8597#issuecomment-409773878
https://github.com/Linuxbrew/homebrew-core/pull/8709

Can you test this? Not sure why it is needed though.

**Pull request closed without merging**
