### PR TITLE
snippy 4.2.2

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI on macOS
```
==> /usr/local/Cellar/snippy/4.2.1/bin/snippy-core --version 2>&1
Error: brewsci/bio/snippy: failed
An exception occured within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<255>.
```
https://circleci.com/gh/brewsci/homebrew-bio/4189

**Comment by tseemann** [comment]
@sjackman Last version i couldn't build it either - the tests returned error 135 but you said it worked for you. Very weird.

**Comment by sjackman** [comment]
Your best bet to troubleshoot is interactive SSH on CircleCI with `Rerun job with SSH`

**Comment by sjackman** [comment]
This version also works on my local macOS machine.

**Comment by sjackman** [comment]
Does adding `depends_on "perl"` even on macOS make your life easier?

**Pull request closed without merging**
