### PR TITLE
Parsnp.migrate to

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
g++-5 -O3 -m64 -fopenmp -funroll-all-loops -fomit-frame-pointer -ftree-vectorize  -g -O2 -lgomp -lstdc++ -lpthread -std=gnu++0x -Wl,-rpath,/tmp/parsnp-20180811-9069-15u0ftn/parsnp-1.2/muscle/lib -L/tmp/parsnp-20180811-9069-15u0ftn/parsnp-1.2/muscle/lib -lMUSCLE-3.7   -o parsnp parsnp-MuscleInterface.o parsnp-parsnp.o parsnp-LCB.o parsnp-LCR.o parsnp-TMum.o parsnp-Converter.o parsnp-iniFile.o  
parsnp-MuscleInterface.o: In function `MuscleInterface::CallMuscleFast(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
MuscleInterface.cpp:(.text+0x6b): undefined reference to `muscle::g_SeqType'
MuscleInterface.cpp:(.text+0x7d): undefined reference to `muscle::g_uMaxIters'
MuscleInterface.cpp:(.text+0x8e): undefined reference to `muscle::g_bStable'
MuscleInterface.cpp:(.text+0x9c): undefined reference to `muscle::g_bVerbose'
MuscleInterface.cpp:(.text+0xaa): undefined reference to `muscle::g_bQuiet'
MuscleInterface.cpp:(.text+0xb9): undefined reference to `muscle::g_SeqWeight1'
MuscleInterface.cpp:(.text+0xcb): undefined reference to `muscle::g_uMaxIters'
MuscleInterface.cpp:(.text+0xd0): undefined reference to `muscle::SetMaxIters(unsigned int)'
MuscleInterface.cpp:(.text+0xde): undefined reference to `muscle::g_SeqWeight1'
MuscleInterface.cpp:(.text+0xe3): undefined reference to `muscle::SetSeqWeightMethod(muscle::SEQWEIGHT)'
MuscleInterface.cpp:(.text+0x104): undefined reference to `muscle::g_ulMaxSecs'
MuscleInterface.cpp:(.text+0x11a): undefined reference to `vtable for muscle::SeqVect'
MuscleInterface.cpp:(.text+0x1ae): undefined reference to `muscle::Seq::SetName(char const*)'
MuscleInterface.cpp:(.text+0x259): undefined reference to `muscle::SeqVect::AppendSeq(muscle::Seq const&)'
MuscleInterface.cpp:(.text+0x275): undefined reference to `muscle::MSA::MSA()'
MuscleInterface.cpp:(.text+0x284): undefined reference to `muscle::MUSCLE(muscle::SeqVect&, muscle::MSA&)'
MuscleInterface.cpp:(.text+0x31e): undefined reference to `muscle::MSA::GetSeqIndex(unsigned int) const'
MuscleInterface.cpp:(.text+0x32a): undefined reference to `muscle::MSA::GetSeqBuffer(unsigned int) const'
MuscleInterface.cpp:(.text+0x368): undefined reference to `muscle::MSA::~MSA()'
MuscleInterface.cpp:(.text+0x372): undefined reference to `muscle::SeqVect::~SeqVect()'
MuscleInterface.cpp:(.text+0x3bd): undefined reference to `muscle::MSA::~MSA()'
MuscleInterface.cpp:(.text+0x3cc): undefined reference to `muscle::SeqVect::~SeqVect()'
collect2: error: ld returned 1 exit status
Makefile:359: recipe for target 'parsnp' failed
make[1]: *** [parsnp] Error 1
make[1]: Leaving directory '/tmp/parsnp-20180811-9069-15u0ftn/parsnp-1.2/src'
Makefile:339: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by sjackman** [comment]
`g++-5 -O3 -m64 -fopenmp -funroll-all-loops -fomit-frame-pointer -ftree-vectorize  -g -O2 -lgomp -lstdc++ -lpthread -std=gnu++0x -Wl,-rpath,/tmp/parsnp-20180811-9069-15u0ftn/parsnp-1.2/muscle/lib -L/tmp/parsnp-20180811-9069-15u0ftn/parsnp-1.2/muscle/lib -lMUSCLE-3.7   -o parsnp parsnp-MuscleInterface.o parsnp-parsnp.o parsnp-LCB.o parsnp-LCR.o parsnp-TMum.o parsnp-Converter.o parsnp-iniFile.o`

`-lMUSCLE-3.7` needs to come after the object files. This bug could be reported upstream.

**Comment by tseemann** [comment]
Reported upstream https://github.com/marbl/parsnp/issues/57

**Comment by tseemann** [comment]
I got this when building on linux locally:
```
Warning: parsnp dependency protobuf was built with a different C++ standard
library (libstdc++ from gcc-6). This may cause problems at runtime.
```

**Comment by tseemann** [comment]
```
==> make
Making all in src
clang++ -DPACKAGE_NAME=\"parsnp\" -DPACKAGE_TARNAME=\"parsnp\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"parsnp\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"parsnp\" -DVERSION=\"1.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -I.   -I/private/tmp/parsnp-20180908-9023-74052e/parsnp-1.2/muscle -O3 -m64 -fopenmp -funroll-all-loops -fomit-frame-pointer -ftree-vectorize  -g -O2 -MT parsnp-MuscleInterface.o -MD -MP -MF .deps/parsnp-MuscleInterface.Tpo -c -o parsnp-MuscleInterface.o `test -f 'MuscleInterface.cpp' || echo './'`MuscleInterface.cpp
In file included from MuscleInterface.cpp:3:
./MuscleInterface.h:11:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
```

Will depend on GCC now

**Comment by sjackman** [comment]
> Warning: parsnp dependency protobuf was built with a different C++ standard
library (libstdc++ from gcc-6). This may cause problems at runtime.

You can usually safely ignore this warning.

**Comment by tseemann** [comment]
This package was a monster to figure out....

**Pull request closed without merging**
