### PR TITLE
maker 2.31.9 (new formula)

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman do you mean `depends_on "cpanminus"` ? (not `cpanm`)

**Comment by sjackman** [comment]
Sigh, yes.

**Comment by sjackman** [comment]
CircleCI on macOS
```
--> Working on forks
…
Building and testing List-MoreUtils-0.428 ... OK
Successfully installed List-MoreUtils-0.428
…
Successfully installed Acme-Damn-0.08
! Installing the dependencies failed: Module 'List::MoreUtils' is not installed
! Bailing out the installation for forks-0.36.
12 distributions installed
```
https://circleci.com/gh/brewsci/homebrew-bio/1258
That's weird.

**Comment by sjackman** [comment]
Successful on CircleCI on Linux!

**Comment by sjackman** [comment]
Grr. Failed again on macOS with the same error. I'll try adding `List::MoreUtils` as an explicit dependency.

**Comment by tseemann** [comment]
```
Successfully installed Test-Exception-0.43
Building and testing Acme-Damn-0.08 ... OK
Successfully installed Acme-Damn-0.08
! Installing the dependencies failed: Module 'List::MoreUtils' is not installed
! Bailing out the installation for forks-0.36.
12 distributions installed

```

**Comment by sjackman** [comment]
```
! Installing the dependencies failed: Module 'List::MoreUtils' is not installed
```
https://circleci.com/gh/brewsci/homebrew-bio/1262

@tseemann Do you have any idea why it would say that `Module 'List::MoreUtils' is not installed` when earlier in the log it says
```
Building and testing List-MoreUtils-0.428 ... OK
Successfully installed List-MoreUtils-0.428
```
?

**Comment by sjackman** [comment]
Gist from CircleCI on macOS by interactive `ssh`
```
! Installing the dependencies failed: Module 'List::MoreUtils' is not installed
! Bailing out the installation for forks-0.36.
```
https://gist.github.com/sjackman/d8b2d14cf5f594f997ab692f3dab4eda#file-01-cpanm-L82

**Comment by sjackman** [comment]
CirlceCI on macOS and local
```
❯❯❯ /usr/bin/perl -e 'use List::MoreUtils' && echo good
good
```
`List::MoreUtils` is already installed on macOS with `/usr/bin/perl`. I wonder if the version is too old or something like that, and that's causing this grief.

```
$ /usr/bin/perl --version
This is perl 5, version 18, subversion 2 (v5.18.2) built for darwin-thread-multi-2level
$ /usr/bin/perl -MList::MoreUtils -le 'print $List::MoreUtils::VERSION'
0.33
```
The most recent version of `List::MoreUtils` is 0.428. Perhaps I need to specify to `cpanm` that it needs to be upgraded. It does not appear to be installed in `prefix`.
```sh
$ find /usr/local/Cellar/maker/2.31.9_1/perl5//lib/perl5/darwin-thread-multi-2level/List -type f
/usr/local/Cellar/maker/2.31.9_1/perl5//lib/perl5/darwin-thread-multi-2level/List/MoreUtils/XS.pm
```

**Comment by sjackman** [comment]
I'm trying without using `--self-contained` on macOS. Perhaps we shouldn't use `--self-contained` on Linux either.

**Comment by sjackman** [comment]
Success! Bye bye `--self-contained`

**Pull request closed without merging**
