### PR TITLE
crass 1.0.1

### PR DESCRIPTION
**Pull request by gaberoo**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

Question for @sjackman:
What is the policy about putting things in `pkgshare` vs `share` ?

### CODE REVIEW

**Comment by sjackman** [comment]
> What is the policy about putting things in pkgshare vs share ?

Always use `pkgshare`. The only two directories under `share` should be the package name and `man`.

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/fontconfig/2.13.1/bin/fc-cache: failed
Warning:‌ The post-install step did not complete successfully‌
You can try again using `brew postinstall fontconfig`
```
https://dev.azure.com/brewsci/brewsci/_build/results?buildId=503&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=4350&lineEnd=4351&colStart=1&colEnd=1

**Comment by sjackman** [comment]
CircleCI on Linux
```
checking for Xerces C++ Parser... no
configure: error: Cannot find Xerces-c
```
https://circleci.com/gh/brewsci/homebrew-bio/5768

I see that you do have `depends_on "xerces-c"` but it still doesn't seem to be finding it. You can troubleshoot using the `linuxbrew/brew` Docker image, used by CircleCI.

**Comment by gaberoo** [comment]
I'll check the `fontconfig` error. But the more worrying one is

```
checking for Xerces C++ Parser... no
configure: error: Cannot find Xerces-c
```

on both Azure and CircleCI Linux builds.

**Comment by gaberoo** [comment]
There are two problems now:

1. `xerces-c` is still not found on Linux. This must be a problem with the `m4` file or the way `xerces-c` is install on Linux versus macOS. One thing I did observe is that on linux `libxerces-c.a` is not symlinked, only the versioned library `libxerces-c-3.2.a`.

2. The newest `netpbm` does not build on Linux.

**Comment by sjackman** [comment]
> The newest netpbm does not build on Linux.

I've asked Michka to take a look at `netpbm`. https://github.com/Homebrew/linuxbrew-core/pull/13078#issuecomment-496702619

**Comment by sjackman** [comment]
On macOS `xerces-c` installs…
```
lib/libxerces-c-3.2.dylib
lib/libxerces-c.so
lib/pkgconfig/xerces-c.pc
```
Pretty weird that it installs an unversioned `.so` file on macOS rather than a `.dylib` file.

My guess is that `pkg-config` should be used to find the correct compiler flags. Is that working as expected on Linux? Is `crass` using `pkg-config` to find `xerces-c`?

**Comment by gaberoo** [comment]
`pkgconfig/xerces-c.pc` is not installed on Linux.

**Comment by sjackman** [comment]
> `lib/pkgconfig/xerces-c.pc` is not installed on Linux.

If `crass` does use `pkg-config` to find `xerces-c`, then I feel like that not installing the `.pc` file on Linux may the root of the problem.

**Pull request closed without merging**
