### PR TITLE
bioperl: bump revision for perl

### PR DESCRIPTION
**Pull request by lcoombe**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
Once this PR succeeds and is merged, could you please open a PR to bump the version to `BioPerl-Run-1.007003.tar.gz` and delete the `revision`?

**Comment by lcoombe** [comment]
Yup for sure! I'll update the version to `1.007003` once the revision is all done.

**Comment by sjackman** [comment]
```
==> brew install abricate
==> FAILED
==> Installing abricate from brewsci/bio
==> Downloading https://linuxbrew.bintray.com/bottles-bio/abricate-0.8.10.x86_64_linux.bottle.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/d2980ef35c0ef1e21b55a6b7b6af901bb0576e33dcc7a3fd49f0cc7de4677ab4--abricate-0.8.10.x86_64_linux.bottle.tar.gz
==> Pouring abricate-0.8.10.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/abricate/0.8.10/bin/abricate --setupdb
Last 150 lines from /root/.cache/Homebrew/Logs/abricate/post_install.01.abricate:
2019-05-10 23:31:26 +0000

/home/linuxbrew/.linuxbrew/Cellar/abricate/0.8.10/bin/abricate
--setupdb

Removing old BLAST indices for /home/linuxbrew/.linuxbrew/Cellar/abricate/0.8.10/libexec/bin/../db/argannot/sequences
Making nucl BLAST index for /home/linuxbrew/.linuxbrew/Cellar/abricate/0.8.10/libexec/bin/../db/argannot/sequences
ERROR: Database argannot is not indexed, please try: abricate --setupdb
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall brewsci/bio/abricate`
```
https://circleci.com/gh/brewsci/homebrew-bio/5950

**Comment by sjackman** [comment]
```
==> brew test --verbose maker
==> FAILED
Testing brewsci/bio/maker
==> /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/bin/maker --version
/home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/bin/maker: /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/libexec/bin/maker: /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/perl: bad interpreter: No such file or directory
/home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/bin/maker: line 2: /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/libexec/bin/maker: Success
Error: brewsci/bio/maker: failed
```
https://circleci.com/gh/brewsci/homebrew-bio/5950

**Comment by sjackman** [comment]
```
==> brew test --verbose maxbin2
==> FAILED
Testing brewsci/bio/maxbin2
==> perl /usr/local/Cellar/maxbin2/2.2.5/libexec/run_MaxBin.pl 2>&1
Error: brewsci/bio/maxbin2: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Usage/> expected to be =~
<"sh: line 1: 41429 Abort trap: 6           idba_ud > /dev/null 2> tmp_1557531215\nCannot run IDBA-UD. Please indicate the file directory in 'setting' file.\n">.
```
https://circleci.com/gh/brewsci/homebrew-bio/5951

**Comment by lcoombe** [comment]
We had issues with abricate earlier in the ORCA build: https://github.com/bcgsc/orca/pull/80

**Comment by sjackman** [comment]
@tseemann What do you know about this `brew postinstall abricate` failure?
https://github.com/brewsci/homebrew-bio/pull/621#issuecomment-491458089

**Comment by sjackman** [comment]
The revision of `maker` needs to be bumped before this PR can be merged.

**Comment by lcoombe** [comment]
Yup makes sense -- I'll do the Maker PR now

**Comment by sjackman** [comment]
I didn't get to looking at `maxbin2` this weekend. One hack workaround to avoid the failure on macOS is to add a commit to this PR that removes the file `Formula/maxbin2.rb`. That should allow this PR to pass. I can merge this PR, and when I do, discard that commit.

**Comment by sjackman** [comment]
@lcoombe On second thought, I bet `idba` needs to be rebuilt for GCC on macOS. Bumping its revision should fix the issue with `maxbin2` I bet.

**Comment by lcoombe** [comment]
> On second thought, I bet `idba` needs to be rebuilt for GCC on macOS. Bumping its revision should fix the issue with `maxbin2` I bet.

Ok - I'll update the `abricate` version, bump the revision for `idba` and hope those changes make circleCI happy here!

**Comment by lcoombe** [comment]
CircleCI error on linux:
```
==> brew test --verbose maker
==> FAILED
Testing brewsci/bio/maker
==> /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/bin/maker --version
/home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/bin/maker: /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/libexec/bin/maker: /home/linuxbrew/.linuxbrew/Cellar/perl/5.28.0/bin/perl: bad interpreter: No such file or directory
/home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/bin/maker: line 2: /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10/libexec/bin/maker: Success
Error: brewsci/bio/maker: failed
```
Could be due to the fact that I hadn't rebased these changes on master yet - I'll rebase and re-try

**Comment by lcoombe** [comment]
CircleCI error on linux:
```
==> brew audit brewsci/bio/idba --online
==> FAILED
Error: 1 problem in 1 formula detected
brewsci/bio/idba:
  * C: 19: col 3: `depends_on` (line 19) should be put before `fails_with` (line 17)
```

**Comment by lcoombe** [comment]
@sjackman - CircleCI succeeded! (Although azure failed..)
Are you happy for me to `brewsci-pull` to merge these commits?

**Comment by sjackman** [comment]
🎆 Yes! That's most awesome! Please do `brewsci-pull`.

**Comment by sjackman** [comment]
@tseemann: Lauren updated `abricate` to version 0.8.13

**Pull request closed without merging**
