### PR TITLE
bandage: Add a test

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by tseemann** [comment]
I thought Qt required X11 connection even to just run `--help` ?

**Comment by sjackman** [comment]
Ah, that could be. Let's find out…
We can disable this test on CircleCI, which is sad, but better than nothing.

**Comment by sjackman** [comment]
TravisCI is unhappy with the `bandage` binary executable.
```
0.00s==> brew test brewsci/bio/bandage --verbose
Testing brewsci/bio/bandage
==> /home/linuxbrew/.linuxbrew/Cellar/bandage/0.8.1/bin/bandage --help
Error: brewsci/bio/bandage: failed
No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/bandage/0.8.1/bin/bandage
```
https://travis-ci.org/brewsci/homebrew-bio/builds/348041432#L8477

**Comment by tseemann** [comment]
Yeah, @rrwick has some unusual ideas on capitalisation ;-)    (Hi Ryan!)

**Comment by sjackman** [comment]
All the tests are 💚, so it looks as though `bandage --help` does not require X11. Merging.

**Pull request merged**
