### PR TITLE
ntcard: import from brewsci/science

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by tseemann** [comment]
```
2.00s==> brew install --verbose --build-bottle brewsci/bio/ntcard
==> Installing ntcard from brewsci/bio
git config --replace-all homebrew.private true
==> Downloading https://github.com/bcgsc/ntCard/archive/1.0.1.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/ntcard-1.0.1.tar.gz
==> Verifying ntcard-1.0.1.tar.gz checksum
tar xzf /home/linuxbrew/.cache/Homebrew/ntcard-1.0.1.tar.gz
==> ./autogen.sh
.
Last 150 lines from /home/linuxbrew/.cache/Homebrew/Logs/ntcard/01.autogen.sh:
2018-03-01 23:08:14 +0000
./autogen.sh
+ aclocal
+ autoconf
+ autoheader
+ automake -a
"none" is not exported by the List::Util module
Can't continue after import errors at /home/linuxbrew/.linuxbrew/opt/automake/bin/automake line 76.
BEGIN failed--compilation aborted at /home/linuxbrew/.linuxbrew/opt/automake/bin/automake line 76.
==> Formula
Tap: brewsci/bio
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/ntcard.rb
==> Configuration
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: aa4303ffc3a8ec8ab6a16f30a90edf093256c50e
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 5ec1eff722902f4889515db8ba10c2a49ce660f8
Core tap last commit: 73 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_ENV_FILTERING: 1
HOMEBREW_FAIL_LOG_LINES: 150
HOMEBREW_FORCE_VENDOR_RUBY: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_NO_AUTO_UPDATE: 1
HOMEBREW_NO_EMOJI: 1
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_SANDBOX: 1
HOMEBREW_VERBOSE_USING_DOTS: 1
CPU: dual-core 64-bit sandybridge
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.15.1 => /usr/bin/git
Curl: 7.35.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /opt/pyenv/shims/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: 1.8.0_151
Kernel: Linux 4.4.0-101-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.5 LTS (trusty)
Host glibc: 2.19
/usr/bin/gcc: 4.8.4
glibc: 2.23
Error: brewsci/bio/ntcard 1.0.1 did not build
gcc: 5.5.0_1
xorg: N/A
==> ENV
HOMEBREW_CC: gcc-5
HOMEBREW_CXX: g++-5
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
ACLOCAL_PATH: /home/linuxbrew/.linuxbrew/share/aclocal
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/home/linuxbrew/.linuxbrew/opt/autoconf/bin:/home/linuxbrew/.linuxbrew/opt/automake/bin:/home/linuxbrew/.linuxbrew/opt/binutils/bin:/usr/bin:/bin:/usr/sbin:/sbin:/home/linuxbrew/.linuxbrew/opt/gcc/bin
Logs:
     /home/linuxbrew/.cache/Homebrew/Logs/ntcard/00.options.out
     /home/linuxbrew/.cache/Homebrew/Logs/ntcard/01.autogen.sh
If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
brewsci/bio
These open issues may also help:
ntcard: import from brewsci/science https://github.com/brewsci/homebrew-bio/pull/78
==> FAILED
brew.audit.10
5.00s==> brew audit brewsci/bio/ntcard --online --new-formula
==> Installing or updating 'rubocop' gem
Successfully installed parallel-1.12.1
Successfully installed ast-2.4.0
Successfully installed parser-2.5.0.2
Successfully installed powerpack-0.1.1
Successfully installed rainbow-3.0.0
Successfully installed ruby-progressbar-1.9.0
Successfully installed unicode-display_width-1.3.0
Successfully installed rubocop-0.52.1
8 gems installed
==> PASSED
brew.uninstall.11
0.00s==> brew uninstall --force autoconf automake m4
Warning: /home/linuxbrew/.linuxbrew/Cellar/m4/1.4.18 is required by isl 0.18, which is currently installed.
You can silence this warning with:
  brew uninstall --ignore-dependencies autoconf automake m4
Uninstalling autoconf... (70 files, 3MB)
Uninstalling automake... (131 files, 3.1MB)
Uninstalling m4... (13 files, 1.1MB)
==> PASSED
Error: Kernel.exit
The command "brew test-bot" exited with 1.
Done. Your build exited with 1.
```

**Comment by tseemann** [comment]
I think this error is related to https://github.com/Linuxbrew/homebrew-core/issues/6275

**Comment by sjackman** [comment]
```
+ automake -a
"none" is not exported by the List::Util module
Can't continue after import errors at /home/linuxbrew/.linuxbrew/opt/automake/bin/automake line 76.
```
https://travis-ci.org/brewsci/homebrew-bio/builds/348009339#L2159
Never seen that error before.

**Comment by sjackman** [comment]
Merging despite the TravisCI failure. Not sure what's up with that.

**Pull request closed without merging**
