### PR TITLE
pullseq 1.0.2 (new formula)

### PR DESCRIPTION
**Pull request by gaberoo**
- [ x ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ x ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

This is rather old software, but a dependency of more current tools (for example https://github.com/cmks/DAS_Tool).

### CODE REVIEW

**Comment by gaberoo** [comment]
`brew test pullseq` is failing locally also. The output is 
```
 ❯ brew test pullseq
Testing brewsci/bio/pullseq
==> /usr/local/Cellar/pullseq/1.0.2/bin/pullseq --help 2>&1
Error: brewsci/bio/pullseq: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was
<1>.
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:55:in `block in assert_block'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1632:in `_wrap_assertion'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:53:in `assert_block'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:240:in `assert_equal'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula_assertions.rb:10:in `shell_output'
/Volumes/SSD/Homebrew/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/pullseq.rb:20:in `block in <class:Pullseq>'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula.rb:1724:in `block (3 levels) in run_test'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/utils.rb:476:in `with_env'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula.rb:1723:in `block (2 levels) in run_test'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula.rb:864:in `with_logging'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula.rb:1722:in `block in run_test'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula.rb:1961:in `block in mktemp'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula.rb:1960:in `mktemp'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/formula.rb:1716:in `run_test'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/Volumes/SSD/Homebrew/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

However, running the test "manually" works:

```
 ❯ /usr/local/Cellar/pullseq/1.0.2/bin/pullseq --help 2>&1 | grep "Usage"
Usage:
```

**Comment by sjackman** [comment]
`shell_output` checks that the exit status is 0. Try…
```sh
/usr/local/Cellar/pullseq/1.0.2/bin/pullseq --help >/dev/null 2>/dev/null
echo $?
```
If it reports an exit status of `1`, then
```ruby
    assert_match "Usage", shell_output("#{bin}/pullseq --help 2>&1", 1)
```

**Comment by gaberoo** [comment]
I think this PR is good to go.

**Comment by sjackman** [comment]
Thanks, Gabriel. Note that a force-push on GitHub doesn't trigger a notification, which is a bug in my opinion. After a force push and CI going from 🔴 to 💚 you can at me for a review.

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to Brewsci/bio, Gabriel!
https://twitter.com/brew_sci/status/1105141654707556352

**Pull request closed without merging**
