### PR TITLE
bifrost 1.0.1

### PR DESCRIPTION
**Pull request by GuillaumeHolley**
Created with `brew bump-formula-pr`.

---

Update bifrost to 1.0.1 with brew bump-formula-pr

### CODE REVIEW

**Comment by tseemann** [comment]
Thank you @GuillaumeHolley

**Comment by GuillaumeHolley** [comment]
You're welcome @tseemann. My next commit will be to fix [pmelsted/bifrost#14](pmelsted/bifrost#14).

**Comment by sjackman** [comment]
@GuillaumeHolley The default branch of Brewsci/bio recently changed from `master` to `develop`. Please run…

```sh
cd $(brew --repo brewsci/bio)
git remote set-head origin -a
```

Thank you!

**Comment by GuillaumeHolley** [comment]
Thanks @sjackman, will do!

**Pull request merged**
