### PR TITLE
bioperl 1.007002 (new formula)

### PR DESCRIPTION
**Pull request by sjackman**
A work in progress.

### CODE REVIEW

**Comment by tseemann** [comment]
I don't think I've ever read the paper!
```
# cite Stajich_2002: "https://doi.org/10.1101/gr.361602"
```

**Comment by tseemann** [comment]
```
This package requires Module::Build v0.42 or greater to install itself.
```

**Comment by sjackman** [comment]
Getting close…
```
==> brew test brewsci/bio/bioperl --verbose
Testing brewsci/bio/bioperl
==> bp_biogetseq.pl -h </dev/null 2>&1
==> bp_classify_hits_kingdom.pl -h </dev/null 2>&1
Error: brewsci/bio/bioperl: failed
<0> expected but was
<2>.
==> FAILED
```
https://travis-ci.org/brewsci/homebrew-bio/builds/355593719#L2634

**Comment by sjackman** [comment]
@tseemann 🎉 🍾

**Pull request closed without merging**
