### PR TITLE
taxonkit 0.2.5 stable

### PR DESCRIPTION
**Pull request by shenwei356**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by shenwei356** [comment]
Well, I have no idea why the tests failed

**Comment by sjackman** [comment]
```ruby
assert_match version.to_s, shell_output("#{bin}/taxonkit --help 2>&1")
```
The test didn't pass because `taxonkit --help` doesn't contain the string `0.2.5-stable`. If you're the upstream author, since the version number 0.2.5 has already been used, please tag a new stable release 0.2.6.

**Comment by tseemann** [comment]
@shenwei356 another option is to add `version 2.5.0` and `revision 1` and leave `url` as-is.

In general, for packaging, it is much better to only ever use `X.Y.Z` versions, and never add suffixes like `-dev`, `-beta` etc. I have made this mistake too in my past and life is much easier now.

**Comment by shenwei356** [comment]
Thank you @sjackman and @tseemann . I create another PR to avoid interference from other tools.

**Pull request closed without merging**
