### PR TITLE
sga: update patch url

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

Fix style error:

```
C: 25: 10: Use a commit hash URL rather than an unstable pull request URL
```

### CODE REVIEW

**Comment by sjackman** [comment]
How did you merge this PR and #1131 without updating the bottle? I'm glad you didn't update the bottle, but I want to know how you did it! 😁

**Comment by SeekingMeaning** [comment]
Easy, just have an audit failure due to other formulae 😝

I was just thinking that for PRs that _do_ have bottles we could just delete the artifact to prevent a bottle update

**Comment by sjackman** [comment]
> I was just thinking that for PRs that do have bottles we could just delete the artifact to prevent a bottle update

Yep, that'd work. I never noticed the 🗑️ icon on the Artifacts page.

I was also thinking it may be possible by intentionally merging the PR to `master` instead of `develop`. That may or may not need a tweak to the GitHub Actions scripts.

**Comment by SeekingMeaning** [comment]
> I was also thinking it may be possible by intentionally merging the PR to `master` instead of `develop`. That may or may not need a tweak to the GitHub Actions scripts.

Opened #1139

**Pull request merged**
