### PR TITLE
wtdbg2 2.1

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
macos:

```
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="Thu Oct 25 23:44:41 PDT 2018" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o wtpoa-cns wtpoa-cns.c ksw.c -lm -lrt -lpthread
In file included from In file included from wtdbg.cwtdbg-cns.c::2020:
In file included from In file included from :
wtpoa-cns.cIn file included from In file included from ./kswx.h./kbm.h:kbm.c:::2023:
In file included from ./kbm.h:23:
In file included from 2420:
:
In file included from :
./list.h./list.hIn file included from :In file included from ./tripoa.h28::
23:28:
:
In file included from ./poacns.h:23:
In file included from ./bit2vec.h:27:
./mem_share.h:26./mem_share.h::1026:: 10./mem_share.h:: 26fatal error:: 10:fatal error'endian.h' file not found: 
 fatal error: 'endian.h' file not found
'endian.h' file not found
./dna.h:27:
In file included from ./list.h:28:
./mem_share.h:26:#include <endian.h>#include <endian.h>10
:         ^~~~~~~~~~ 
fatal error: 
'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
         ^~~~~~~~~~
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
```

**Comment by tseemann** [comment]
Solved and filed at https://github.com/ruanjue/wtdbg2/issues/31

**Comment by tseemann** [comment]
```
gcc -g3 -W -Wall -Wno-unused-but-set-variable -O4 -DTIMESTAMP="Thu Oct 25 23:58:01 PDT 2018" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -mpopcnt -msse4.2 -o wtpoa-cns wtpoa-cns.c ksw.c -lm -lrt -lpthread
kbm.c:244:10: error: use of undeclared identifier '_proc_deamon'; did you mean '_sig_proc_deamon'?
                ncpu = _proc_deamon->ncpu;
                       ^~~~~~~~~~~~
                       _sig_proc_deamon
./mem_share.h:570:36: note: '_sig_proc_deamon' declared here
static struct _proc_deamon_struct* _sig_proc_deamon = NULL;
```

I feel i'm in quicksand here.

**Comment by tseemann** [comment]
```
Error: GitHub API Error: API rate limit exceeded for 35.184.226.236. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 30 minutes 13 seconds, or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile
```
Does this mean my token @sjackman ?

I have HOMEBREW_GITHUB_API_TOKEN and HOMEBREW_GITHUB_USER set in my local env.

**Comment by sjackman** [comment]
`Test::Unit::AssertionFailedError: <1> expected but was <139>.`

Exit status 139 is 139-128 = signal 11 = SIGSEGV = segmentation fault. See `kill -l 11`
Did you get it working?

**Comment by sjackman** [comment]
> Does this mean my token @sjackman ? I have HOMEBREW_GITHUB_API_TOKEN and HOMEBREW_GITHUB_USER set in my local env.

Assuming you saw this error message on CircleCI (and not your local box) then it's the CircleCI token that has expired or isn't working. I'm not sure why they stop working, but I can fix it if you see it again. Let me know.

**Pull request closed without merging**
