### PR TITLE
viennarna 2.4.13

### PR DESCRIPTION
**Pull request by dmohadjel**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

Wasn't able to install locally

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI on Linux
```
make[3]: Entering directory '/tmp/viennarna-20190725-11346-9d1nnz/ViennaRNA-2.4.13/interfaces/Perl'
  CXX      RNA_la-RNA_wrap.lo
RNA_wrap.cpp:762:20: fatal error: EXTERN.h: No such file or directory
compilation terminated.
Makefile:709: recipe for target 'RNA_la-RNA_wrap.lo' failed
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6908

The file `EXTERN.h` is provided by the brewed formula `perl`.

**Comment by sjackman** [comment]
CircleCI on macOS
```
  CC       special_const.lo
<stdin>:9:2: error: instruction requires: AVX-512 ISA
        vpbroadcastd    %eax, %zmm2
        ^
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6907

The CPUs on CircleCI support AVX-512, so ViennaRNA is trying to use AVX-512 instructions, but Homebrew has disable support for AVX-512 instructions as a compiler option so that the compiled bottles may be run on older machines. Is there a configure option to ViennaRNA to disable the use of AVX-512 instructions?

**Comment by sjackman** [comment]
This formula is not a high priority. I would not let this issue hold up the release of the next version of ORCA.

**Comment by tseemann** [comment]
Looks like it is all or nothing:
```
  --disable-simd          Speed-up MFE computations using explicit SIMD
                          instructions.
  --enable-sse            Deprecated switch for SIMD optimizations. Use
                          --enable-simd/--disable-simd instead
  --disable-vectorize     Apply automatic SIMD vectorization to optimize
                          execution speed
```

**Pull request closed without merging**
