### PR TITLE
quast: import from brewsci/science

### PR DESCRIPTION
**Pull request by emreerhan**

### CODE REVIEW

**Comment by sjackman** [comment]
Hi, Emre. It looks as though you used GitHub's `Resolve merge conflict` button, which doesn't work with our workflow. You can instead rebase your PR onto `master`?

**Comment by emreerhan** [comment]
This time the error is a compilation error. Any thoughts @sjackman ?

**Comment by sjackman** [comment]
On Linux it appears to be trying to compile `gcc` from source and failing. It shouldn't be doing that. I'll look into it.

**Comment by sjackman** [comment]
The above `gcc` issue should be fixed by https://github.com/Linuxbrew/homebrew-core/pull/6633

**Comment by emreerhan** [comment]
What's the next step? Should I force push?

**Comment by sjackman** [comment]
`test-bot` didn't build bottles, and I'm not sure why. I'm looking into it.

**Comment by sjackman** [comment]
`test-bot` isn't testing `quast`, and I'm not sure why. It's quite mysterious. Can you try…
```sh
git checkout migrate-quast
git commit --amend
git push --force
```

**Comment by tseemann** [comment]
```
../../gcc/graphite-optimize-isl.c:30:22: fatal error: isl/band.h: No such file or directory
 #include <isl/band.h>
                      ^
compilation terminated.
```

Seems to be the gcc / isl problem. I'll restart it.

**Comment by emreerhan** [comment]
Thanks @tseemann!

**Comment by sjackman** [comment]
I rebased the PR onto master and happily started working again! I don't know why it wasn't working before. `brew test-bot` should automatically rebase the PR when it pulls it.  ¯\_(ツ)_/¯

**Comment by sjackman** [comment]
Merged. Thanks, Emre!

**Pull request closed without merging**
