### PR TITLE
discovardenovo: import from brewsci/science

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
```
Error: No available formula with the name "allpaths-lg" 
```
https://circleci.com/gh/brewsci/homebrew-bio/2851

**Comment by sjackman** [comment]
CircleCI on Linux with GCC 5.5.0
```
In file included from ./Alignment.h:33:0,
                 from ./PrintAlignment.h:12,
                 from pairwise_aligners/Mutmer.cc:10:
./PackAlign.h:170:20: error: reference to ‘align’ is ambiguous
   packalign( const align& a );
```
https://circleci.com/gh/brewsci/homebrew-bio/2854

**Comment by sjackman** [comment]
```
  * C: 17: col 3: dependency "gcc@4.9" (line 17) should be put before dependency "linux" (line 16)
  * C: 18: col 3: dependency "jemalloc" (line 18) should be put before dependency "linux" (line 16)
```
grumble

**Comment by sjackman** [comment]
CircleCI on Linux exceeded available memory
https://circleci.com/gh/brewsci/homebrew-bio/2853
https://circleci.com/gh/brewsci/homebrew-bio/2860

| Jobs | Status |
|---|---|
| 32 | ❌ |
| 16 | ❌ |
| 8 | |

**Comment by sjackman** [comment]
```
std::char_traits<char> > const&, unsigned char const&, FeudalString<char, std::char_traits<char> > const&, std::map<FeudalString<char, std::char_traits<char> >, GapToyResults, std::less<FeudalString<char, std::char_traits<char> > >, std::allocator<std::pair<FeudalString<char, std::char_traits<char> > const, GapToyResults> > >&, FeudalString<char, std::char_traits<char> > const&, FeudalString<char, std::char_traits<char> > const&, vec<int, std::allocator<int> > const&, MasterVec<BaseVec> const&, unsigned char)':
/tmp/discovardenovo-20180604-4886-pr0a9e/discovardenovo-52488/src/paths/long/large/FinalFiles.cc:249: undefined reference to `digraphE<BaseVec>::O(int) const'
/home/linuxbrew/.linuxbrew/bin/ld: final link failed: No space left on device
collect2: error: ld returned 1 exit status
Makefile:877: recipe for target 'FormPath' failed
```
https://circleci.com/gh/brewsci/homebrew-bio/2865

Whoah! Haven't seen a full disk error before on CircleCI!

**Comment by iMichka** [comment]
I saw it once. I tried a new build later and it worked.

**Comment by sjackman** [comment]
Thanks for the suggestion to rerun the job, Michka. I did indeed get a different error this time.

**Comment by sjackman** [comment]
```
/bin/bash ../libtool --tag=CXX   --mode=link g++-4.9 -pthread -fopenmp -fpermissive -std=c++11 -Wextra -Wall -Wsign-promo -Woverloaded-virtual -Wendif-labels -Wno-unused -Wno-deprecated -Wno-long-long -Wno-parentheses -Wno-unused-parameter -fno-nonansi-builtins -mieee-fp -fno-strict-aliasing -iquote . -ggdb -DNDEBUG   -o QueryLookupTable QueryLookupTable.o libDiscovarDeNovo.a  
libtool: link: g++-4.9 -pthread -fopenmp -fpermissive -std=c++11 -Wextra -Wall -Wsign-promo -Woverloaded-virtual -Wendif-labels -Wno-unused -Wno-deprecated -Wno-long-long -Wno-parentheses -Wno-unused-parameter -fno-nonansi-builtins -mieee-fp -fno-strict-aliasing -iquote . -ggdb -DNDEBUG -o QueryLookupTable QueryLookupTable.o  libDiscovarDeNovo.a -pthread
libDiscovarDeNovo.a(FinalFiles.o): In function `FinalFiles(HyperBasevector const&, vec<int, std::allocator<int> > const&, MasterVec<ReadPath> const&, vec<FeudalString<char, std::char_traits<char> >, std::allocator<FeudalString<char, std::char_traits<char> > > > const&, vec<long, std::allocator<long> > const&, FeudalString<char, std::char_traits<char> > const&, FeudalString<char, std::char_traits<char> > const&, int, int, unsigned char, FeudalString<char, std::char_traits<char> > const&, unsigned char const&, FeudalString<char, std::char_traits<char> > const&, std::map<FeudalString<char, std::char_traits<char> >, GapToyResults, std::less<FeudalString<char, std::char_traits<char> > >, std::allocator<std::pair<FeudalString<char, std::char_traits<char> > const, GapToyResults> > >&, FeudalString<char, std::char_traits<char> > const&, FeudalString<char, std::char_traits<char> > const&, vec<int, std::allocator<int> > const&, MasterVec<BaseVec> const&, unsigned char)':
/tmp/discovardenovo-20180605-4882-1bgtc1l/discovardenovo-52488/src/paths/long/large/FinalFiles.cc:249: undefined reference to `digraphE<BaseVec>::O(int) const'
collect2: error: ld returned 1 exit status
Makefile:868: recipe for target 'CrossOut' failed
make[1]: *** [CrossOut] Error 1
```
https://circleci.com/gh/brewsci/homebrew-bio/2867

**Comment by sjackman** [comment]
I really would like to get this formula working, but I'm running out of ideas to try.

**Comment by sjackman** [comment]
```
==> brew linkage --test brewsci/bio/discovardenovo
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz.so.1
==> FAILED
```
https://github.com/brewsci/homebrew-bio/pull/309/checks?check_run_id=549818537#step:6:1012

**Comment by sjackman** [comment]
```
##[error]Unable to process command '::add-matcher::brew-audit.json' successfully.
##[error]Could not find file '/home/runner/work/homebrew-bio/homebrew-bio/brew-audit.json'.
```
@jonchang I got this error again just now, and it worked just minutes ago.
https://github.com/brewsci/homebrew-bio/pull/309/checks?check_run_id=549947506#step:5:50

**Comment by sjackman** [comment]
```
==> /home/linuxbrew/.linuxbrew/Cellar/discovardenovo/52488/bin/DiscovarDeNovo --version
1019
Error: brewsci/bio/discovardenovo: failed
1020
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </Usage/> was expected to be =~
<"Performing re-exec to adjust stack size.\n" + "DiscovarDeNovo r52488\n">.
```
https://github.com/brewsci/homebrew-bio/pull/309/checks?check_run_id=550130184#step:6:1022

**Pull request merged**
