### PR TITLE
shovill 0.9.0

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
W: The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release' is not signed.
W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
```

I think Travis CI is having some network issues?

**Comment by sjackman** [comment]
Those are warnings. You can ignore them. I'm not sure what they mean.
CircleCI is 💚

**Comment by sjackman** [comment]
`shovill --check` is failing on TravisCI. You can ignore, but you may want to look into it.
```
==> brew test brewsci/bio/shovill --verbose
Testing brewsci/bio/shovill
==> /home/linuxbrew/.linuxbrew/Cellar/shovill/0.9.0/bin/shovill --version 2>&1
==> /home/linuxbrew/.linuxbrew/Cellar/shovill/0.9.0/bin/shovill --help 2>&1
==> /home/linuxbrew/.linuxbrew/Cellar/shovill/0.9.0/bin/shovill --check 2>&1
Error: brewsci/bio/shovill: failed
<0> expected but was
<1>.
==> FAILED
```
https://travis-ci.org/brewsci/homebrew-bio/builds/348034286#L2336
CircleCI is running Ubuntu 16.04, and TravisCI is running Ubuntu 14.04.

**Comment by tseemann** [comment]
@sjackman am i able to look at the output of the failing `shovill --check` test line?

**Comment by sjackman** [comment]
> am i able to look at the output of the failing shovill --check test line?

Sadly no. I wouldn't worry too terribly much about the TravisCI failure. I'd suggest merging this PR, then if you're keen, try to replicate the failure in Docker on Ubuntu 14.04 (which TravisCI runs).

**Comment by tseemann** [comment]
```
brewsci-pull https://github.com/brewsci/homebrew-bio/pull/80
==> Fetching patch
Patch: https://github.com/brewsci/homebrew-bio/pull/80.patch
-=O=-#   #    #     #
==> Applying patch
Applying: shovill 0.9.0
==> Patch closes issue #80
==> Fetching patch (bottle commit)
Patch: https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-80.patch
-#O#- #    #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /home/linuxbrew/.linuxbrew/opt/curl/bin/curl --show-error --user-agent Linuxbrew/1.5.4-3-gaa4303f\ (Linux;\ x86_64\ "Red\ Hat\ Enterprise\ Linux\ Server\ release\ 7.4\ (Maipo)")\ curl/7.58.0 --fail --progress-bar --location --remote-time --continue-at - --output /home/linuxbrew/.cache/Homebrew/brewsci:master...pr-80.patch https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-80.patch
```

**Comment by sjackman** [comment]
No bottles were built because of an issue in Linuxbrew/brew.
```
==> SKIPPING: brewsci/bio/shovill
Java is required to install this formula.
JavaRequirement unsatisfied!
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
To install it, run:
  brew install jdk
```
https://circleci.com/gh/brewsci/homebrew-bio/738
The simplest way forward is to add…
```sh
bottle :unneeded
```
Then `Squash and merge` this PR. Does that work for you?

**Pull request merged**
