### PR TITLE
beagle: import from brewsci/science

### PR DESCRIPTION
**Pull request by jonchang**

### CODE REVIEW

**Comment by jonchang** [comment]
Requires `libtool` at runtime for some reason.

**Comment by sjackman** [comment]
That's unusual. What was the error message?

**Comment by jonchang** [comment]
`brew linkage` failed after uninstalling build time dependencies on Linux, not finding `libltdl`. I tried `ENV.refurbish_args` but that didn't work.

**Comment by jonchang** [comment]
Looks like `beagle` uses `libtool` to dynamically load shared libraries at runtime... `libhmsbeagle/plugin/LibtoolSharedLibrary.h`: `This header implements unix libraries using libtool loading instead of the standard dlopen() interface`

**Comment by jonchang** [comment]
BEAST and MrBayes both seem happy with `beagle` without run-time libtool. Disabling it.

**Pull request closed without merging**
