### PR TITLE
staden-io-lib 1.14.11 (new formula)

### PR DESCRIPTION
**Pull request by gaberoo**
- [ x ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ x ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ x ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

This is a dependency of salmon.

### CODE REVIEW

**Comment by gaberoo** [comment]
Interesting: The test returns exit code 0 on macOS and 1 on Linux.

**Comment by sjackman** [comment]
> This is a dependency of salmon.

No kidding. @rob-p Do you prefer to htslib?

**Comment by sjackman** [comment]
The name `io_lib` is too generic. Debian and variants calls this library `staden-io-lib`. Let's use that name. See https://repology.org/project/staden-io-lib/versions

**Comment by rob-p** [comment]
I do. The reasons are twofold. First, io_lib supported multithreaded bam decompression long before htslib (though mut point now). Second, however, it adopts a different encoding of bam records that is more memory efficient than that of htslib.

**Comment by sjackman** [comment]
`brew test` failed. See the Azure build logs.

**Comment by gaberoo** [comment]
@sjackman: quite strange about the test. In any case, I wrote a much more minimal one.

@rob-p: Interesting about the encoding of BAM records, can you elaborate?

**Comment by sjackman** [comment]
Merged. Thanks again, Gabriel!

**Pull request closed without merging**
