### PR TITLE
gatk 4.2.2.0

### PR DESCRIPTION
**Pull request by lbergelson**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----
Updating gatk to it's newest release.

4.2.0.0 -> 4.2.1.0

### CODE REVIEW

**Comment by lbergelson** [comment]
The bottles failed to build because of this error:
```
==> brew audit brewsci/bio/gatk --online --git --skip-style
==> FAILED
brewsci/bio/gatk:
  * The homepage URL https://software.broadinstitute.org/gatk is not reachable (HTTP status code 403)
Error: 1 problem in 1 formula detected
```

But the website seems to be reachable, and when I run `brew audit --strict` locally it doesn't show that error.  Not sure what's going on.  Maybe a badly timed temporary outage of some sort?

**Comment by sjackman** [comment]
I can reproduce the issue locally on both Linux and macOS with `brew audit --online`.
```console
$ brew audit --online brewsci/bio/gatk
brewsci/bio/gatk:
  * The homepage URL https://software.broadinstitute.org/gatk is not reachable (HTTP status code 403)
Error: 1 problem in 1 formula detected
```

```console
$ curl -s https://software.broadinstitute.org/gatk
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://gatk.broadinstitute.org">here</a>.</p>
</body></html>
$ curl -s https://gatk.broadinstitute.org
<html><body>You are being <a href="https://gatk.broadinstitute.org/hc">redirected</a>.</body></html>
$ curl -s https://gatk.broadinstitute.org/hc
<html><body>You are being <a href="https://gatk.broadinstitute.org/hc/en-us">redirected</a>.</body></html>
$ curl -is https://gatk.broadinstitute.org/hc/en-us | egrep '403|Security'
HTTP/2 403 
  <title>Security check</title>
```

There's three HTTPS 302 redirects followed by a HTTPS 403 Forbidden from CloudFlare "Security check", which I presume CI is failing, because it's not human.

@GregBrimble What's the recommended way of dealing with a CloudFlare "Security check" failing CI?

**Comment by GregBrimble** [comment]
Sorry, @sjackman, I forgot to post back to Homebrew about this. I did speak to the Bot Management team, but unfortunately given `brew`'s distributed traffic, I don't think there's any way to always securely discern from legitimate traffic from abusive. `brew` attaches a user-agent header, but that is, of course, easily forged, and therefore not enough to be allow-listed.

The only advice I can really suggest at the moment is that site owners (in this case, broadinstitute.org, either reduce the overall security of their site, or preferably, add a rule themselves to explicitly allow brew traffic. This could be based on the user-agent header, the originating IPs (GitHub Actions runners in this case) or whatever other identifiers the owners find useful.

Ultimately, site owners are in control here, since they could decide to host a cask and also just block all traffic (even if they weren't using Cloudflare).

It's very annoying that there's no catch-all solution we can apply here. If anyone has any other suggestions, I'd be more than happy to discuss.

**Comment by sjackman** [comment]
@lbergelson Since you work at the Broad, Louis, feel free to raise this issue with your systems infrastructure department, if you're so inclined. In the mean time, if you would like a workaround, I'd suggest changing the homepage to `https://github.com/broadinstitute/gatk#readme`

**Comment by lbergelson** [comment]
@sjackman I'm not even sure who to contact about cloudflare blocking the brew bots.  It seems like it's correctly identifying that it's a bot and blocking it.  I'll reach out to our IT.  In the meantime I've taken your suggestion and updated the homepage. 

It seems like the linux bottle failed again for an unrelated reason.

```
Run actions/checkout@master
/usr/bin/docker exec  91cbbba4abdc7720ea0959beb25719bea6658eedae078612d3cbdff75a13b3c8 sh -c "cat /etc/*release | grep ^ID"
Syncing repository: brewsci/homebrew-bio
Getting Git version info
Deleting the contents of '/__w/homebrew-bio/homebrew-bio'
Initializing the repository
  /usr/bin/git init /__w/homebrew-bio/homebrew-bio
  /__w/homebrew-bio/homebrew-bio/.git: Permission denied
  Error: The process '/usr/bin/git' failed with exit code 1
```

**Comment by lbergelson** [comment]
We've actually released a new version of GATK since I made this PR.  So I pushed it to 4.2.2.0

**Comment by lbergelson** [comment]
Can anyone help with the linux bottle failure?  I'm not sure what the issue is.

**Comment by lbergelson** [comment]
@sjackman The bottle builds keep failing but I'm not sure how to debug.  It looks like it's happening very early in the process so it's unclear to me what I can do.   Can you help?

**Comment by lbergelson** [comment]
@sjackman Sorry to keep bugging you but I'm not sure how to fix he bottle build since it fails at the git checkout stage before even getting to anything gatk related.  

It looks like it's failing while checking out homebrew-bio but I'm not sure how/why.

```
Run actions/checkout@master
/usr/bin/docker exec  5253a9ddf551fca2633282558ccf7f55652a1d0c7d660e86dd3b150c19a44af5 sh -c "cat /etc/*release | grep ^ID"
Syncing repository: brewsci/homebrew-bio
Getting Git version info
Deleting the contents of '/__w/homebrew-bio/homebrew-bio'
Initializing the repository
  /usr/bin/git init /__w/homebrew-bio/homebrew-bio
  /__w/homebrew-bio/homebrew-bio/.git: Permission denied
  Error: The process '/usr/bin/git' failed with exit code 1
```

**Comment by lbergelson** [comment]
I saw in another thread that the bottle issue should be fixed so I repushed it.

**Comment by lbergelson** [comment]
Oh, now it failed with a real issue.  Apparently bio perl moved to brew core.

**Comment by lbergelson** [comment]
Nevermind, the perl thing seems like a red herring.  

These lines seem like a possible problem:
```
==> brew install gcc
Warning: openjdk cannot be built with any available compilers.
==> SKIPPED gatk
Install Clang or run `brew install gcc`.
```

**Pull request closed without merging**
