### PR TITLE
mreps 2.6

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
this only fails on macos.... they don't have an HTTPS server :-(

```
Error: 2 problems in 1 formula detected
brewsci/bio/mreps:
  * The URL http://mreps.univ-mlv.fr/index.html should use HTTPS rather than HTTP
  * Stable: The URL http://mreps.univ-mlv.fr/mreps-2.6.tar should use HTTPS rather than HTTP
```

**Comment by sjackman** [comment]
HTTPS works for me on macOS in Safari, and with `curl` at the command line.
```console
$ curl -s https://mreps.univ-mlv.fr/index.html | file -
/dev/stdin: HTML document text, ASCII text, with very long lines
$ curl -s https://mreps.univ-mlv.fr/mreps-2.6.tar | file -
/dev/stdin: POSIX tar archive
```

**Comment by tseemann** [comment]
But it doesn't work on the macos testbot.
Do you have `insecure` in your `~/.curlrc` perhaps?

**Comment by sjackman** [comment]
> Do you have insecure in your ~/.curlrc perhaps?

No, I don't. I'm not sure why the `https` doesn't work on the test bot.

**Pull request closed without merging**
