### PR TITLE
megahit 1.2.9

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
/usr/bin/env: ‘python’: No such file or directory
Error: brewsci/bio/megahit: failed
```

**Comment by sjackman** [comment]
Try…
```
inreplace "FILENAME.py", "#!/usr/bin/env python", "#!/usr/bin/env python3"
```
and replace `FILENAME` with the name of the script.

**Comment by sjackman** [comment]
```
==> Pouring gcc-9.2.0_3.catalina.bottle.tar.gz
121
/usr/local/Cellar/gcc/9.2.0_3: 1,462 files, 287.9MB
122

123
==> brew install gcc
124
Warning: gcc 9.2.0_3 is already installed and up-to-date
125
To reinstall 9.2.0_3, run `brew reinstall gcc`
126

127
==> brew install gcc
128
Warning: gcc 9.2.0_3 is already installed and up-to-date
129
To reinstall 9.2.0_3, run `brew reinstall gcc`
130

131
==> brew install gcc
132
Warning: gcc 9.2.0_3 is already installed and up-to-date
133
To reinstall 9.2.0_3, run `brew reinstall gcc`
134

…
```
GitHub Actions on macOS looped infinitely and timed out after 6 hours. Looks like a bug in `brew test-bot` to me. I believe this `fails_with "gcc" => "9"` and `depends_on "gcc@8"` worked before. Are you able to test `brew install megahit` on a local macOS machine?

**Comment by tseemann** [comment]
@sjackman yes it builds fine on Catalina brew (uses gcc-8.3)

**Comment by tseemann** [comment]
🎆 🍾 turns out they fixed the gcc9 bugs. hooray!

**Pull request merged**
