### PR TITLE
dsh-bio: Use depends_on openjdk instead of java 1.8+

### PR DESCRIPTION
**Pull request by heuermh**
See #1158 

- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
```console
$ brew install dsh-bio
$ dsh-bio --version
dsh-bio-tools 1.3.4
Commit: caee3362436a799e07f21b0a4a17c75e269fc02f  Build: 2020-07-16
Copyright (c) 2013-2020 held jointly by the individual authors.
Licensed GNU Lesser General Public License (LGPL), version 3 or later.
```
Works for me?

**Comment by heuermh** [comment]
As described a bit further in #1158, this is apparently due to there no longer a JDK 8 option available via `java` on OSX, and only presented itself when setting up a new machine.

**Comment by sjackman** [comment]
I was behind current events and didn't realize that `depends_on java: "1.8+"` had been replaced by `depends_on "openjdk"`. Could you please rebase this PR onto `origin/develop`?

**Comment by heuermh** [comment]
Superceded by #1215

**Comment by sjackman** [comment]
@heuermh I suspect that `dsh-bio` and `nextflow` may currently fail on Linux. If so, would you like to open a PR to bump the revision of each formula and address the build failure? If it does succeed without change, then no need, we can just close the PR.

**Pull request closed without merging**
