### PR TITLE
[FIX] Missing permissions in CI

### LINKED ISSUE #1395: All CI linux builds fail: "Initializing the repository /usr/bin/git init Permission denied"
All PRs (at least the first two I checked) seem to have linux builds fail in Github actions with the following stack trace:
```
Initializing the repository
  /usr/bin/git init /__w/homebrew-bio/homebrew-bio
  /__w/homebrew-bio/homebrew-bio/.git: Permission denied
  Error: The process '/usr/bin/git' failed with exit code 1
```

See here for details: https://github.com/brewsci/homebrew-bio/pull/1394/checks?check_run_id=3335797430

image

### PR DESCRIPTION
**Pull request by eseiler**
Resolves #1395

### CODE REVIEW

**Comment by corneliusroemer** [comment]
Thanks for figuring this out! I hope it'll work!

**Comment by YoshitakaMo** [comment]
I'm also waiting for the review by @sjackman, but he seems to be busy, so I'll merge this PR instead of him.
If there are any inconveniences, please revert it.

**Comment by YoshitakaMo** [comment]
Unfortunately, the CI was not successfully fixed yet. Is this unrelated to the previous issue?

```
[FIX] Missing permissions in CI
From https://github.com/brewsci/homebrew-bio
 * [new ref]         refs/pull/1400/head -> pr-head
pr=1400 sha1=87eb7c5fece7cd39a35841f57423efa2e9482134
run_id=1173580685 artifact_id=87205930
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100   275    0   275    0     0    747      0 --:--:-- --:--:-- --:--:--   747
bottles.zip: Zip archive data, at least v2.0 to extract
Archive:  bottles.zip
 extracting: bottle_output.txt       
  inflating: steps_output.txt        
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
/usr/bin/skopeo
/bin/skopeo
skopeo version 1.3.0
Warning: pr-upload is a developer command, so
Homebrew's developer mode has been automatically turned on.
To turn developer mode off, run brew developer off

Error: No bottle JSON files found in the current working directory
Error: Process completed with exit code 1.
```

**Comment by eseiler** [comment]
I think this was another problem. Not sure if the script has some trouble if there are no changed recipes.
CI seems fine on my other PR that was rebased on this one https://github.com/brewsci/homebrew-bio/pull/1399

**Comment by YoshitakaMo** [comment]
@eseiler Thank you for your comment. The PR #1399 successfully passed the CI and was merged. I'm still not sure why the PR #1400 didn't work well when I merged it, but could you re-upload the PR again? Thank you in advance.

**Comment by YoshitakaMo** [comment]
Let the rest of the discussion take place here. https://github.com/brewsci/homebrew-bio/issues/1395

**Pull request merged**
