### PR TITLE
gfakluge 0.2.2

### PR DESCRIPTION
**Pull request by edawson**
- [X] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [X] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [X] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
Build error:

```
make: *** No rule to make target `pliib/pliib.hpp', needed by `build/main.o'.  Stop.
```

The commit message should also be `gfakludge 0.2.1`

**Comment by sjackman** [comment]
@edawson How are you making out with this PR?

**Comment by edawson** [comment]
I think I've fixed the build issue, but I also became distracted with other deadlines and didn't cut a release and switch out the sha256s. I'm hoping not to let it languish much longer than this weekend!

**Comment by sjackman** [comment]
```
==> brew test brewsci/bio/gfakluge --verbose
Testing brewsci/bio/gfakluge
==> /home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfa_stats -s -i test.gfa
Error: brewsci/bio/gfakluge: failed
No such file or directory - /home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfa_stats
```
https://travis-ci.org/brewsci/homebrew-bio/builds/373678231#L1611

**Comment by sjackman** [comment]
```
==> brew test brewsci/bio/gfakluge --verbose
Testing brewsci/bio/gfakluge
==> /home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfak stats -s -i test.gfa
/home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfak: invalid option -- 's'
/home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfak stats: print assembly / graph stats for a GFA file.
Usage: /home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfak stats [options] <GFA_File>
Options:
   -a / --assembly  print assembly statistics (N50, N90, L50, L90).
   -A / --all       print all graph statistics.
   -l / --length    print the total sequence length (in S lines).
   -n / --num-nodes print the number of nodes.
   -e / --num-edges print the number of edges.
   -p / --paths     print some path statistics.
   -v / --version        print GFAK version and exit.
Error: brewsci/bio/gfakluge: failed
<0> expected but was
<3>.
```
https://travis-ci.org/brewsci/homebrew-bio/builds/373971175#L1622

**Comment by sjackman** [comment]
```
==> /home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfak stats -A -i test.gfa
/home/linuxbrew/.linuxbrew/Cellar/gfakluge/0.2.2/bin/gfak: invalid option -- 'i'
```
https://travis-ci.org/brewsci/homebrew-bio/builds/374026615#L1610

**Comment by sjackman** [comment]
@edawson You can test your changes locally with
```sh
brew install gfakluge
brew audit gfakluge
brew test gfakluge
```

**Comment by edawson** [comment]
Sorry for bombarding y'all with test commits. My work Mac can't update XCode, so I couldn't test locally. I've swapped machines for a bit to work on this.

**Comment by sjackman** [comment]
No worries. If it helps, you can test on Linux using Linuxbrew. http://linuxbrew.sh
PR is 💚 !
For future PRs please use `git commit --amend; git push --force` to revise a single commit.

**Comment by sjackman** [comment]
> Fix build error by forcing gcc and fix tests to reflect current API

@edawson What's the build error with clang?

**Comment by sjackman** [comment]
Merged. Thanks for your first contribution to Brewsci/bio, Eric! 🏅

**Comment by edawson** [comment]
@sjackman openmp with clang is a mess it seems. I can strip out the openmp dependency in the next minor version bump. Thanks for all the help!

**Comment by sjackman** [comment]
No need. OpenMP is a legit reason to use GCC on macOS. I've added a comment.
See c76935a3896354ab70354f15966d50175c84cc95

**Pull request closed without merging**
