### PR TITLE
hisat2 2.2.0

### PR DESCRIPTION
**Pull request by czhu**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by czhu** [comment]
not sure about the error, I could build bottle on my Mac

**Comment by sjackman** [comment]
```
==> brew audit --skip-style brewsci/bio/hisat2 --online
Error: 1 problem in 1 formula detected
brewsci/bio/hisat2:
* Non-executables were installed to "/usr/local/opt/hisat2/bin"
The offending files are:
/usr/local/opt/hisat2/bin/HISAT2-genotype.png
==> FAILED
```
https://github.com/brewsci/homebrew-bio/pull/999/checks#step:4:369

**Comment by czhu** [comment]
it looks like for ` bin.install`, `Dir["hisat2-*"]` isn't case specific, which included `HISAT2-genotype.png`. How to make this case specific?

**Comment by sjackman** [comment]
The macOS file system is not case specific by default, so that's not easy (AFAIK). I suggest
```ruby
rm "HISAT2-genotype.png"
bin.install, Dir["hisat2-*"]
```

**Comment by sjackman** [comment]
Merged. Thank you for your contributions to Brewsci/bio, Chenchen.🌟

**Pull request merged**
