### PR TITLE
beast2 2.5.0

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
Audit is failing because I'm setting `JAVA_HOME` but it fails to build/test if I don't set it.

**Comment by tseemann** [comment]
```
Checking out /home/linuxbrew/.linuxbrew/Cellar/beast2/2.4.8/libexec/lib
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at beast.app.beastapp.BeastLauncher.checkForBEAST(Unknown Source)
	at beast.app.beastapp.BeastLauncher.loadBEASTJars(Unknown Source)
	at beast.app.beastapp.BeastLauncher.main(Unknown Source)
Error: brewsci/bio/beast2: failed
Failed executing: /home/linuxbrew/.linuxbrew/Cellar/beast2/2.4.8/bin/beast-2 -java -seed 1000 testCalibration.xml
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1792:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1730:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1730:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/beast2.rb:49:in `block in <class:Beast2>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1636:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:554:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1635:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:835:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1634:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1628:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:29:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:28:in `<main>'
```

**Comment by sjackman** [comment]
```
* Use `depends_on :java` to set JAVA_HOME
```
https://travis-ci.org/brewsci/homebrew-bio/builds/357026966#L2311

Looks like we need to fix Linuxbrew/brew's `depends_on :java` to set JAVA_HOME. Would you be interested in looking into that? Here's the relevant files:

https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/java_requirement.rb
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/os/linux/requirements/java_requirement.rb
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/os/mac/requirements/java_requirement.rb

**Comment by jonchang** [comment]
I'm working on it, bot.

**Comment by jonchang** [comment]
:pray: that v2.5.0 is now compatible with jdk 9

**Pull request closed without merging**
