### PR TITLE
canu 1.7

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
@sjackman  I thought your
```
  # Fix fatal error: 'omp.h' file not found
  depends_on "gcc" unless OS.mac? # for openmp
```
fixed this?

```
clang++ -o /private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/Darwin-amd64/obj/lib/libcanu.a/AS_UTL/AS_UTL_reverseComplement.o -c -MD -DBROKEN_CLANG_OpenMP -pthread -fPIC -m64 -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-sign-compare -Wformat -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -DNOBACKTRACE -I/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon AS_UTL/AS_UTL_reverseComplement.C
In file included from AS_UTL/AS_UTL_decodeRange.C:34:
In file included from AS_UTL/AS_UTL_decodeRange.H:33:
In file included from AS_UTL/AS_UTL_reverseComplement.C:34:
/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/src/AS_global.H:/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/src/AS_global.H94::9410::10 :fatal error : fatal error: 'omp.h' file not found
'omp.h' file not found
In file included from AS_UTL/AS_UTL_fasta.C:42:
In file included from AS_UTL/AS_UTL_fasta.H:37:
/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/src/AS_global.H:94#include <omp.h>#include <omp.h>
         ^~~~~~~
:10: fatal error: 'omp.h' file not found
In file included from AS_UTL/AS_UTL_fileIO.C#include <omp.h>
         ^~~~~~~:
38:
In file included from AS_UTL/AS_UTL_fileIO.H:37:
/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/src/AS_global.H:94:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
         ^~~~~~~

1 error generated.
make: *** [/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/Darwin-amd64/obj/lib/libcanu.a/AS_UTL/AS_UTL_reverseComplement.o] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/Darwin-amd64/obj/lib/libcanu.a/AS_UTL/AS_UTL_fasta.o] Error 1
1 error generated.
make: *** [/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/Darwin-amd64/obj/lib/libcanu.a/AS_UTL/AS_UTL_fileIO.o] Error 1
1 error generated.
make: *** [/private/tmp/canu-20180228-6578-1xncl9u/canu-1.7/Darwin-amd64/obj/lib/libcanu.a/AS_UTL/AS_UTL_decodeRange.o] Error 1
```

**Comment by sjackman** [comment]
Woops. Yep, it should be
```ruby
depends_on "gcc" if OS.mac? # for openmp
```

**Comment by tseemann** [comment]
It's comforting to know that even you can make mistakes sometimes too ;-)

**Comment by sjackman** [comment]
I added…
```ruby
  fails_with :clang # needs openmp
```

**Comment by sjackman** [comment]
Merged. Thanks, Torsten!

**Pull request closed without merging**
