### PR TITLE
express: import from brewsci/science

### PR DESCRIPTION
**Pull request by jonchang**

### CODE REVIEW

**Comment by jonchang** [comment]
Blocked on https://github.com/Linuxbrew/homebrew-core/pull/8423

testing static builds so we can bottle

**Comment by jonchang** [comment]
express is needed for trinity and jellyfish, which I'll migrate next.

**Comment by jonchang** [comment]
Trying 8 cores...

**Comment by sjackman** [comment]
```
-lz ../bamtools/lib/libbamtools.a
```
In the above link command line, these two options are reversed. It should be…
```
../bamtools/lib/libbamtools.a -lz
```

**Comment by sjackman** [comment]
What's the status of this PR, @jonchang?

**Comment by jonchang** [comment]
@sjackman I'm thinking of actually migrating it to homebrew/core instead. brewsci/science/express has 101 install-on-request events in the last month [according to analytics](https://formulae.brew.sh/analytics/install-on-request/30d/). Thoughts? (Other candidates include openalpr, opennni and opennni2)

**Comment by sjackman** [comment]
Since eXpress is no longer being developed, I'd suggest Brewsci/bio.

> Note that the eXpress software is also no longer being developed. We recommend you use kallisto instead.

https://pachterlab.github.io/eXpress/

**Comment by jonchang** [comment]
Oh, good call, I should have noticed that.

**Comment by jonchang** [comment]
Not sure why the PR isn't updating, I pushed some changes to my branch.

**Comment by sjackman** [comment]
CircleCI reports `Finished: 19 min ago`, so it looks like it's up to date.
https://circleci.com/gh/brewsci/homebrew-bio/3704

The issue with the `-lz` option remains. See https://github.com/brewsci/homebrew-bio/pull/331#issuecomment-414424132

**Comment by jonchang** [comment]
Thanks @sjackman I somehow had totally missed that comment. Let's see if this passes tests.

**Comment by jonchang** [comment]
🎉! Thanks @sjackman

**Comment by sjackman** [comment]
No worries!

**Comment by gmbaquino** [comment]
Thanks for your work on this. Still eagerly awaiting the update of the Trinity formula. Cheers!

**Pull request closed without merging**
