### PR TITLE
iqtree2 2.0.7

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by SeekingMeaning** [comment]
Ouch it's a prerelease

**Comment by sjackman** [comment]
No, you can leave it as is. I wouldn't be surprised if 2.0.7 was marked as prerelease accidentally.
You could if you were keen add a `brew audit --online` check that checked the prerelease status of a tag on GitHub.

**Comment by SeekingMeaning** [comment]
> You could if you were keen add a `brew audit --online` check that checked the prerelease status of a tag on GitHub.

You mean for CI?

**Comment by sjackman** [comment]
Yeah, it would require a PR to Homebrew/brew to add this check to `brew audit`, which also runs on CI.

**Comment by SeekingMeaning** [comment]
So I looked into this and the core taps actually do check if prerelease but it's disabled for non-core taps: https://github.com/Homebrew/brew/blob/4c23fd0/Library/Homebrew/dev-cmd/audit.rb#L726

**Comment by sjackman** [comment]
I wish that audits could be enabled/discarded using a config file, and perhaps even enabled-disabled per formula, similar to `pylint` and other linters.

**Comment by SeekingMeaning** [comment]
> I wish that audits could be enabled/disabled using a config file

Opened Homebrew/brew/pull/8354

**Comment by sjackman** [comment]
😮 Wow! Thank you!

**Pull request merged**
