### PR TITLE
cannoli 0.14.0

### PR DESCRIPTION
**Pull request by heuermh**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by heuermh** [comment]
From [build-linux-bottles](https://github.com/brewsci/homebrew-bio/pull/1397/checks?check_run_id=3384478379) failure
```
Run actions/checkout@master
/usr/bin/docker exec  0d906eaace697b2e9cadf2eaf82b57da1b4e36155a0bd74c9edbe7d1fbbe847c sh -c "cat /etc/*release | grep ^ID"
Syncing repository: brewsci/homebrew-bio
Getting Git version info
Deleting the contents of '/__w/homebrew-bio/homebrew-bio'
Initializing the repository
  /usr/bin/git init /__w/homebrew-bio/homebrew-bio
  /__w/homebrew-bio/homebrew-bio/.git: Permission denied
  Error: The process '/usr/bin/git' failed with exit code 1
```

**Comment by YoshitakaMo** [comment]
This issue is now resolved (See https://github.com/brewsci/homebrew-bio/issues/1395). Your PR will pass the CI now if you merge the latest commit and push it again.

**Comment by heuermh** [comment]
Thank you, @YoshitakaMo!

**Comment by heuermh** [comment]
Please don't close this, bot

**Pull request merged**
