### PR TITLE
trans-abyss: import from brewsci/science

### PR DESCRIPTION
**Pull request by gejessicama**

### CODE REVIEW

**Comment by gejessicama** [comment]
screenshot from 2018-04-11 11-19-55
Encountered an error we haven't gotten before, i.e. the problem with git -C.

**Comment by gejessicama** [comment]
I'm not sure why it removed trans-abyss.rb either, because I meant to amend the commit (forgot to redirect stderr to stdout) but couldn't find the file, so I just did it here on the GitHub website.

**Comment by sjackman** [comment]
To resolve the `git` error, try…
```
export HOMEBREW_NO_ENV_FILTERING=1 
brew install git
brew migrate-formula …
```

**Comment by sjackman** [comment]
Superseded by PR https://github.com/brewsci/homebrew-bio/pull/232

**Pull request closed without merging**
