### PR TITLE
pymol: change CPPFLAGS for M1 Mac

### PR DESCRIPTION
**Pull request by YoshitakaMo**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

On M1 Mac, CPPFLAGS `-I#{Formula["freetype"].opt_include}/freetype2` didn't work (https://github.com/brewsci/homebrew-bio/issues/1290). This PR will solve the issue on M1 Mac.

### CODE REVIEW

**Comment by YoshitakaMo** [comment]
build-linux-bottles has an error: 

```
Error: The following formula cannot be installed from bottle and must be
built from source.
  ffmpeg
```

https://github.com/brewsci/homebrew-bio/pull/1291/checks?check_run_id=1952147531

I will retry later.

**Comment by sjackman** [comment]
https://github.com/Homebrew/linuxbrew-core/commit/ea26a8f520f2887c422cb9f0bdc19d612d08c15e
`ffmpeg` is bottled for Linux now.

**Comment by sjackman** [comment]
Thanks for this fix, Yoshitaka!

**Comment by sjackman** [comment]
It's cool to see Brewsci/bio being used on Apple Silicon hardware.

**Pull request merged**
