### PR TITLE
repeatmasker: Bump the revision for Perl

### PR DESCRIPTION
**Pull request by sjackman**
Fix the error:
```
Soundex.c: loadable library and perl binaries are mismatched
(got handshake key 0xde00080, needed 0xce00080)
```

### CODE REVIEW

**Comment by sjackman** [comment]
```
/home/linuxbrew/.linuxbrew/Cellar/maker/2.31.9_1/bin/maker --version
/home/linuxbrew/.linuxbrew/Cellar/maker/2.31.9_1/libexec/bin/maker: /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1_1/bin/perl: bad interpreter: No such file or directory
```
https://circleci.com/gh/brewsci/homebrew-bio/3899

**Comment by sjackman** [comment]
```
==> brew install --verbose --build-bottle brewsci/bio/maker
==> cpanm -l /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.9_2/perl5 Bit::Vector DBD::SQLite Inline::C
--> Working on DBD::SQLite
Fetching http://www.cpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.58.tar.gz ... OK
Configuring DBD-SQLite-1.58 ... ! Configure failed for DBD-SQLite-1.58. See /tmp/maker-20180831-50565-1apxrr2/maker/.brew_home/.cpanm/work/1535700756.52554/build.log for details.
N/A
```
https://circleci.com/gh/brewsci/homebrew-bio/3911
https://circleci.com/api/v1.1/project/github/brewsci/homebrew-bio/3911/output/104/0?file=true

**Comment by sjackman** [comment]
@suujia Can you look into the above build error of `maker`?

**Comment by sjackman** [comment]
Superseded by https://github.com/brewsci/homebrew-bio/pull/409

**Comment by suujia** [comment]
Are you still having trouble with Maker or is it fixed in: https://github.com/brewsci/homebrew-bio/commit/f70aa97a5a4020648095da93c27cbae66e84b152
I got this message on docker orca-6 image: 
```
$ maker --version
/home/linuxbrew/.linuxbrew/bin/maker: /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.9_1/libexec/bin/maker: /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1_1/bin/perl: bad interpreter: No such file or directory
/home/linuxbrew/.linuxbrew/bin/maker: line 2: /home/linuxbrew/.linuxbrew/Cellar/maker/2.31.9_1/libexec/bin/maker: Success
```
may be fixed after Perl: https://github.com/brewsci/homebrew-bio/pull/410

**Comment by sjackman** [comment]
f70aa97 fixed a small `brew audit` issue. I'm hoping that #410 resolves the bad interpreter issue.

**Pull request closed without merging**
