### PR TITLE
circos: revision bump

### PR DESCRIPTION
**Pull request by dmohadjel**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI on Linux
```
==> brew readall --aliases brewsci/bio
==> FAILED
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/brewsci/homebrew-bio/Formula/transdecoder.rb
Unsupported type NilClass for nil
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6767

Hopefully fixed by PR https://github.com/brewsci/homebrew-bio/pull/699. Rebase this PR onto `origin/master`.

**Comment by dmohadjel** [comment]
It seems there is actually a new version of `circos`. Should I change this PR to update the formula to the new version?

**Comment by sjackman** [comment]
>  dmohadjel force-pushed the dmohadjel:circos  branch from 8b5741f to 8fcf8f0 7 days ago

Force pushes are fine (I prefer them), but they don't trigger a GitHub notification. If you force push, please also comment to ask for a re-review once CI has passed 💚.

**Comment by sjackman** [comment]
I've merged this PR. Please create a new PR to bump the version of `circos`.

**Comment by sjackman** [comment]
Thank you, Dara! 🌟

**Pull request closed without merging**
