### PR TITLE
nanopolish: import from brewsci/science

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by tseemann** [comment]
```
party/scrappie -I./src/common -I./src/alignment -I./src/pore_model -I/home/linuxbrew/.linuxbrew/opt/eigen/include/eigen3 -fPIC src/test/nanopolish_test.cpp
g++-5: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
```

**Comment by sjackman** [comment]
```
g++-5: internal compiler error: Killed (program cc1plus)
```

| Make jobs | Status |
|---|---|
| 32 | ❌ |
| 16 | |

**Comment by sjackman** [comment]
@jts I've packaged Nanopolish for Brewsci/bio with binary packages for both Linux and macOS.
```sh
brew install brewsci/bio/nanopolish
```

**Comment by jts** [comment]
Thanks!

**Comment by sjackman** [comment]
No worries at all!

**Pull request closed without merging**
