### PR TITLE
tbl2asn 25.8

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Persisting to Workspace00:00

The specified paths did not match any files in /tmp
```

**Comment by sjackman** [comment]
I've got the GitHub Actions CI working for building Linux and macOS bottles. If you rebase this PR onto `origin/master`, I'll merge it for you. The procedure to merge the PR is different than it was before, and I'm still working out the kinks.

**Comment by tseemann** [comment]
@sjackman I think I did what you asked. but not sure :-|

**Comment by sjackman** [comment]
```
[04:14:36] Determined makeblastdb version is 2.10
[04:14:36] Prokka needs makeblastdb 2.8 or higher. Please upgrade and try again
Warning: The post-install step did not complete successfully
```
https://github.com/brewsci/homebrew-bio/pull/869/checks?check_run_id=400142102#step:4:733

CI failed when testing `prokka`. Is that something you can fix in `prokka`?

**Comment by tseemann** [comment]
@sjackman yes .... my naive version parsing has been borked by samtools 1.10 and blast  2.10.

**Comment by sjackman** [comment]
> yes .... my naive version parsing has been borked by samtools 1.10 and blast 2.10.

@tseemann Any progress on this issue?

**Comment by sjackman** [comment]
@tseemann You'll likely need to open a PR that updates the version of both `prokka` and `tbl2asn` in the same PR, since they're both currently broken and co-dependent.

**Comment by tseemann** [comment]
Replaced by https://github.com/brewsci/homebrew-bio/pull/909

**Pull request closed without merging**
