### PR TITLE
breseq 0.33.0 + migrate

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI on Linux
```
g++-5: internal compiler error: Killed (program cc1plus)
```
Add…
```ruby
    # Reduce memory usage for CircleCI.
    ENV["MAKEFLAGS"] = "-j16" if ENV["CIRCLECI"]
```

**Comment by sjackman** [comment]
CircleCI on macOS
```
Error: No available formula with the name "libunwind" 
```
https://circleci.com/gh/brewsci/homebrew-bio/1081

Is this dependency necessary? If so, perhaps…
```ruby
if OS.mac?
  depends_on "libunwind-headers" => :build
else
  depends_on "libunwind"
end
```

**Comment by tseemann** [comment]
```
==> brew readall --aliases brewsci/bio
==> brew uses --recursive brewsci/bio/breseq
Error: undefined local variable or method `unchanged_dependencies' for #<Homebrew::Test:0x00000102054e40>
Did you mean?  @unchanged_dependencies
               changed_dependencies
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:672:in `setup_formulae_deps_instances'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:860:in `formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1240:in `block in run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1239:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1239:in `run'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1587:in `test_bot'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/cmd/brew-test-bot.rb:1680:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'
Exited with code 1
```

**Comment by tseemann** [comment]
```
==> brew uses --recursive brewsci/bio/breseq
Error: undefined local variable or method `unchanged_dependencies' for #<Homebrew::Test:0x00000102054e40>
Did you mean?  @unchanged_dependencies
               changed_dependencies
```

**Comment by sjackman** [comment]
The above error is CircleCI on macOS. It looks like an upstream Homebrew/brew bug. Let's give it a couple of days.

**Comment by sjackman** [comment]
It looks as though the `brew uses` bug is fixed in Homebrew/brew.

**Comment by tseemann** [comment]
I'll try and and depend on `isl@0.18`

```
g++-5 -c   -g -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wno-format -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings -fno-common  -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/home/linuxbrew/.linuxbrew/opt/gmp/include -I/home/linuxbrew/.linuxbrew/opt/mpfr/include -I/home/linuxbrew/.linuxbrew/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/bid -I../libdecnumber -I../../gcc/../libbacktrace -I/home/linuxbrew/.linuxbrew/opt/isl/include  -o graphite-optimize-isl.o -MT graphite-optimize-isl.o -MMD -MP -MF ./.deps/graphite-optimize-isl.TPo ../../gcc/graphite-optimize-isl.c
../../gcc/graphite-optimize-isl.c:30:22: fatal error: isl/band.h: No such file or directory
compilation terminated.
Makefile:1066: recipe for target 'graphite-optimize-isl.o' failed
make[3]: *** [graphite-optimize-isl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by sjackman** [comment]
CircleCI on macOS
```
brewsci/bio/breseq:
  * C: 24: col 3: dependency "linux" (line 24) should be put before dependency "r" (line 15)
  * Dependency 'libunwind-headers' may be unnecessary as it is provided by macOS; try to build this formula without it.
  * Dependency 'libunwind-headers' may be unnecessary as it is provided by macOS; try to build this formula without it.
```
https://circleci.com/gh/brewsci/homebrew-bio/1800

**Comment by sjackman** [comment]
```ruby
    depends_on "isl@0.18"
```
Do you know for a fact that `breseq` depends on `isl`? This seems like it may be a bit of a red herring.

**Comment by sjackman** [comment]
```
  * Formulae should not have an unstable spec
```
https://circleci.com/gh/brewsci/homebrew-bio/3149

I'm not entirely sure what it's complaining about here. Does that error persist if you try it again? (rebase)

**Comment by sjackman** [comment]
Success!

**Comment by tseemann** [comment]
@sjackman but we still can't pull bottles correctly yet right? (for mac)

**Comment by sjackman** [comment]
bot.linuxbrew.sh seems broken. I'm looking into it.

**Comment by sjackman** [comment]
Merged. Thanks, Torsten!

**Pull request closed without merging**
