### PR TITLE
dsh-bio 1.3.3

### PR DESCRIPTION
**Pull request by SeekingMeaning**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by heuermh** [comment]
Thank you for this update, @SeekingMeaning!

**Comment by SeekingMeaning** [comment]
Courtesy of `brew livecheck`

**Comment by SeekingMeaning** [comment]
Hmm now that I'm looking at it, I don't think this formula needs bottles

**Comment by heuermh** [comment]
I can merge this, but I forget, on this repository is it Create a merge commit or Squash and merge?

**Comment by SeekingMeaning** [comment]
Ah sorry, the work for this is still in progress, the bottles for `dsh-bio-1.3.3` are no longer listed in https://api.github.com/repos/brewsci/homebrew-bio/actions/workflows/build-bottles.yml/runs because I opened so many PRs

Right now I'm waiting on @sjackman since the latest merge for `minigraph` failed

**Comment by heuermh** [comment]
Got it, thanks!  I'll be patient then 😉

**Comment by heuermh** [comment]
Thank you, @SeekingMeaning @sjackman!

**Pull request merged**
