### PR TITLE
xmatchview 1.1.1 (new formula)

### PR DESCRIPTION
**Pull request by lcoombe**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI on Linux
```
==> brew linkage --test brewsci/bio/xmatchview
==> FAILED
Missing libraries:
  libz-a147dcb0.so.1.2.3
```
https://circleci.com/gh/brewsci/homebrew-bio/5621

You can run `brew linkage --reverse xmatchview` locally to see which file depends on this oddly named library. It looks to me like it was installed by `pip`. I suspect that adding `depends_on "zlib" unless OS.mac?` would fix it.

**Comment by sjackman** [comment]
CircleCI on macOS
```
Error: Failed changing dylib ID of /usr/local/Cellar/xmatchview/1.1.1/libexec/lib/python2.7/site-packages/PIL/.dylibs/liblcms2.2.dylib
  from /DLC/PIL/liblcms2.2.dylib
    to /usr/local/opt/xmatchview/libexec/lib/python2.7/site-packages/PIL/.dylibs/liblcms2.2.dylib
Error: Failed to fix install linkage
```
https://circleci.com/gh/brewsci/homebrew-bio/5621

I haven't seen this error message before. Do you have access to a macOS machine to troubleshoot?

**Comment by lcoombe** [comment]
Looks like the linux failure was a similar error (circle CI on linux):
```
==> brew linkage --test brewsci/bio/xmatchview
==> FAILED
Missing libraries:
  libz-a147dcb0.so.1.2.3
```

I don't have access to a macOS machine to troubleshoot the macOS circleCI error unfortunately...

**Comment by sjackman** [comment]
I suspect that adding `depends_on "zlib" unless OS.mac?` would fix the Linux error.

**Comment by lcoombe** [comment]
I still got the same errors unfortunately :(

**Comment by lcoombe** [comment]
Ok I added:
```
system "pip", "install", "--prefix=#{libexec}", "pillow", "--no-binary=pillow"
```
Because you found that that helped a similar error in #457 if you installed the package from source. I had to add a `depends_on "jpeg"` as well to make the compilation work.

So now CircleCI is happy, but azure is still failing:
```

==&gt;‌ ‌brew linkage --test brewsci&#x2F;bio&#x2F;xmatchview‌
Unwanted system libraries:
  /usr/lib/x86_64-linux-gnu/libfreetype.so.6
  /usr/lib/x86_64-linux-gnu/liblcms2.so.2
  /usr/lib/x86_64-linux-gnu/libtiff.so.5
==&gt; ‌FAILED‌
```

**Comment by sjackman** [comment]
The failure on AzureCI is…
```
Unwanted system libraries:
  /usr/lib/x86_64-linux-gnu/libfreetype.so.6
  /usr/lib/x86_64-linux-gnu/liblcms2.so.2
  /usr/lib/x86_64-linux-gnu/libtiff.so.5
```
https://dev.azure.com/brewsci/brewsci/_build/results?buildId=451&view=logs&jobId=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&taskId=8ef82b3b-1feb-5bbd-06f6-b1f7b5467f03&lineStart=2472&lineEnd=2476&colStart=1&colEnd=2

The problem is Python linking opportunistically against libraries found in `/usr/lib/x86_64-linux-gnu/` even though we don't want it to. We prevent that in CircleCI by ensuring that only the bare minimum of packages are installed. We can ignore the AzureCI build failure.

Feel free to merge!

**Comment by lcoombe** [comment]
Thanks @sjackman - Merged!

**Comment by sjackman** [comment]
Thanks, Lauren!

**Pull request closed without merging**
