### PR TITLE
fastp 0.19.5

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
The bottles didn't seem to make it to bintray: https://bintray.com/linuxbrew/bottles-bio/fastp#files

**Comment by sjackman** [comment]
Could you please rebase this PR onto master? Let me know if you have trouble with the bottle again.

**Comment by sjackman** [comment]
I've triggered a bottle transfer with https://github.com/Linuxbrew/linuxbrew-lambda

**Comment by sjackman** [comment]
Merged.

**Pull request closed without merging**
