### PR TITLE
fraggenescan 1.13 (fix missing exe)

### PR DESCRIPTION
**Pull request by tseemann**
- source code was installed
- was missing actual compilation of binaries
- relative paths didn't work to access training files

### CODE REVIEW

**Comment by tseemann** [comment]
```
==> Downloading https://linuxbrew.bintray.com/bottles-bio/fraggenescan-1.31_1.x86_64_linux.bottle.tar.gz
/usr/bin/curl -q --show-error --user-agent Linuxbrew/1.7.2-2-g27cf347\ \(Linux\;\ x86_64\ 4.4.0-134-generic\)\ curl/7.47.0 --fail --silent --location --remote-time --continue-at - --output /home/linuxbrew/.cache/Homebrew/fraggenescan--1.31_1.x86_64_linux.bottle.tar.gz.incomplete https://linuxbrew.bintray.com/bottles-bio/fraggenescan-1.31_1.x86_64_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "fraggenescan"
```

Why is it trying to install a bottle?

**Comment by sjackman** [comment]
```
==> Migrating cache entries...
Too long with no output (exceeded 10m0s)
```
https://circleci.com/gh/brewsci/homebrew-bio/3956

More CI weirdness. I've rerun CI.

**Comment by sjackman** [comment]
Could you please rebase this PR onto `master`?

**Comment by tseemann** [comment]
Success now - thanks @sjackman .

**Pull request closed without merging**
