### PR TITLE
abricate 0.8

### PR DESCRIPTION
**Pull request by tseemann**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
Error: No available formula with the name "emboss" 
```

**Comment by sjackman** [comment]
You'll have to first migrate `emboss` if it's a strict dependency of `abricate`.

**Comment by tseemann** [comment]
```
Error: No available formula with the name "patchelf" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
Exited with code 1
```

**Comment by tseemann** [comment]
```
Error: Your Xcode (9.0) is outdated. Please update to Xcode 9.2 (or delete it). Xcode can be updated from the App Store. Error: A newer Command Line Tools release is available. Update them from Software Update in the App Store.
```

**Comment by tseemann** [comment]
Waiting on: https://github.com/Linuxbrew/brew/pull/660

**Comment by tseemann** [comment]
Macos:
```
Successfully installed Test-RequiresInternet-0.05
! Installing the dependencies failed: Installed version (6.06) of Net::HTTP is not in range '6.07'
! Bailing out the installation for libwww-perl-6.33.
8 distributions installed
```

Linux:
```
Error: GitHub 
The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
```

**Comment by sjackman** [comment]
```
! Installing the dependencies failed: Installed version (6.06) of Net::HTTP is not in range '6.07'
```

```
❯❯❯ /usr/bin/perl -MNet::HTTP -le 'print $Net::HTTP::VERSION'
6.06
```

`cpanm Net::HTTP` to the rescue?

**Comment by tseemann** [comment]
I decided to remove `LWP::Simple` (the web stuff) 
It's only needed if you want to download new databases etc.
I'll consider adding it back when I can figure it out.
LWP is a big package and might need to be its own brew formula...

**Pull request closed without merging**
