### PR TITLE
gatk 4.1.6.0

### PR DESCRIPTION
**Pull request by lbergelson**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] ~~Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?~~ 
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by lbergelson** [comment]
I've done what I'd normally do to update, but I noticed there's a new bottles section here.  I'm not sure what to do about that, does it get built automagically?

Why do we need a bottle for a prebuilt jar?

**Comment by sjackman** [comment]
> I've done what I'd normally do to update, but I noticed there's a new bottles section here. I'm not sure what to do about that, does it get built automagically?

Yes, the bottle gets built automagically by GitHub Actions.

> Why do we need a bottle for a prebuilt jar?

To provide a second location from which to download GATK.
To make it easier to install older versions of GATK.

**Comment by sjackman** [comment]
Thank you for your contributions to Brewsci/bio, Louis! 🏆

**Comment by lbergelson** [comment]
@sjackman Thank you!

**Pull request merged**
