### PR TITLE
mp-est 2.0

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
Maths library linking issue. I thinkl the first gcc line below is missing `-lm`.

```
gcc -DUNIX_VERSION -O3 -Wall -Wno-uninitialized   -c -o mpest.o mpest.c
<warnings>
gcc -DUNIX_VERSION -O3 -Wall -Wno-uninitialized -lm  mpest.o tool.o   -o mpest
mpest.o: In function `logbinomialP':
mpest.c:(.text+0x40): undefined reference to `log'
mpest.c:(.text+0x68): undefined reference to `log'
mpest.o: In function `logLikelihood':
mpest.c:(.text+0x15e2): undefined reference to `exp'
mpest.c:(.text+0x1761): undefined reference to `log'
mpest.c:(.text+0x1789): undefined reference to `log'
tool.o: In function `rndgamma1':
tool.c:(.text+0x4bd): undefined reference to `pow'
```

**Comment by sjackman** [comment]
This line
```
gcc -DUNIX_VERSION -O3 -Wall -Wno-uninitialized -lm  mpest.o tool.o   -o mpest
```
needs to be
```
gcc -DUNIX_VERSION -O3 -Wall -Wno-uninitialized mpest.o tool.o -lm -o mpest
```

**Comment by jonchang** [comment]
Gah! This was annoying to debug. People shouldn't use implicit make rules unless they really understand them!

**Comment by jonchang** [comment]
Merged. Thanks for the help guys!

**Comment by sjackman** [comment]
No worries! People use the implicit make rules but use the wrong variables, putting what should be in CXXFLAGS in CPPFLAGS, or LIBS in LDFLAGS, et c.

**Pull request closed without merging**
