### PR TITLE
bali-phy 3.1.4 (new formula)

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
These builds might fail, bali-phy has an issue with opportunistic linking since I don't think we filter flags as aggressively (or at all) when building with meson.

**Comment by sjackman** [comment]
```
g++-5: internal compiler error: Killed (program cc1plus)
```
https://circleci.com/gh/brewsci/homebrew-bio/2878
```ruby
      # Reduce memory usage for CircleCI.
      ENV["MAKEFLAGS"] = "-j8" if ENV["CIRCLECI"]
```

**Comment by jonchang** [comment]
Sadly I don't think `ninja` respects `MAKEFLAGS`.

**Comment by sjackman** [comment]
😢

**Comment by jonchang** [comment]
Odd that's it not relocatable. Will figure it out later.

**Pull request closed without merging**
