### PR TITLE
gemma 0.98 [torsten]

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
clang++ -DOPENBLAS -isystem/usr/local/opt/openblas/include -DNDEBUG -O3 -std=c++11 -isystem/usr/local/opt/openblas/include -isystem/usr/local/opt/eigen/include/eigen3  -isystem/usr/local/opt/eigen/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  src/bslmm.o src/bslmmdap.o src/debug.o src/eigenlib.o src/fastblas.o src/gemma.o src/gemma_io.o src/gzstream.o src/lapack.o src/ldr.o src/lm.o src/lmm.o src/logistic.o src/main.o src/mathfunc.o src/mvlmm.o src/param.o src/prdt.o src/varcov.o src/vc.o -lgsl -lz -lopenblas -lgfortran -lquadmath -o ./bin/gemma
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gemma] Error 1
```

**Comment by sjackman** [comment]
`clang` doesn't provide Fortran by default. If it depends on Fortran, then you need…
```ruby
fails_with :clang
depends_on "gcc" if OS.mac? # for gfortran
```

**Comment by tseemann** [comment]
@sjackman I did do that originally (use `gcc`) but that fails with lots of C++ void context errors with `gcc-8` :-(

**Comment by sjackman** [comment]
Try…
```ruby
fails_with :clang
fails_with :gcc => "8"
depends_on "gcc@7" if OS.mac? # for gfortran
```

**Comment by pjotrp** [comment]
Hmm. I don't see why we can't use clang++ as I do that too (see gemma's travis builds). GEMMA actually does not use gfortran, but openblas does. Openblas should pull that dependency in. It needs the gfortran libraries, really, at run-time.

**Comment by sjackman** [comment]
> Hmm. I don't see why we can't use clang++ as I do that too (see gemma's travis builds). GEMMA actually does not use gfortran, but openblas does. Openblas should pull that dependency in. It needs the gfortran libraries, really, at run-time.

This link command includes `-lgfortran` in the link.
```
clang++ -DOPENBLAS -isystem/usr/local/opt/openblas/include -DNDEBUG -O3 -std=c++11 -isystem/usr/local/opt/openblas/include -isystem/usr/local/opt/eigen/include/eigen3  -isystem/usr/local/opt/eigen/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  src/bslmm.o src/bslmmdap.o src/debug.o src/eigenlib.o src/fastblas.o src/gemma.o src/gemma_io.o src/gzstream.o src/lapack.o src/ldr.o src/lm.o src/lmm.o src/logistic.o src/main.o src/mathfunc.o src/mvlmm.o src/param.o src/prdt.o src/varcov.o src/vc.o -lgsl -lz -lopenblas -lgfortran -lquadmath -o ./bin/gemma
```

If the dependency is only indirect (that is `gemma` depends on `-lopenblas` which depends on `-lgfortran`) then you can remove `-lgfortran` from the link line. In this case you may be able to compile with `clang` rather than `gcc` (though I haven't tried it myself).

**Comment by sjackman** [comment]
@pjotrp Are you able to take a look at and fix the build errors with GCC 8?

**Comment by pjotrp** [comment]
> @pjotrp Are you able to take a look at and fix the build errors with GCC 8?

yes I will tomorrow. I think clang is a better option right now. gfortran, btw, is not linked in by openblas automatically. But I'll test on your CI. I think these are specific lapack functions that use fortran's libraries. Note that I don't have a Mac, so I have to do it through the CI.

**Comment by sjackman** [comment]
You should be able to reproduce the GCC 8 errors on Linux as well, I'd guess. You can install GCC 8 on Linux with `brew install gcc@8` using Linuxbrew.

**Comment by pjotrp** [comment]
On Wed, Oct 10, 2018 at 10:10:30AM -0700, Shaun Jackman wrote:
>    You should be able to reproduce the GCC 8 errors on Linux as well, I'd
>    guess. You can install GCC 8 on Linux with brew install gcc@8 using
>    Linuxbrew.

Gemma builds fine on GCC8 because that is what I develop on in Linux.

No worries, we'll get there. I have written packages for GNU Guix and
Conda already and gemma builds on Travis-CI MacOS with clang++. There
is always this flakiness with build chains.

**Comment by tseemann** [comment]
Ah goo idea - use gcc but don't tell it to fail with clang.  Trying now...

**Comment by tseemann** [comment]
```
clang++ -DOPENBLAS -isystem/usr/local/opt/openblas/include -DNDEBUG -O3 -std=c++11 -isystem/usr/local/opt/openblas/include -isystem/usr/local/opt/eigen/include/eigen3  -isystem/usr/local/opt/eigen/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  src/bslmm.o src/bslmmdap.o src/debug.o src/eigenlib.o src/fastblas.o src/gemma.o src/gemma_io.o src/gzstream.o src/lapack.o src/ldr.o src/lm.o src/lmm.o src/logistic.o src/main.o src/mathfunc.o src/mvlmm.o src/param.o src/prdt.o src/varcov.o src/vc.o -lgsl -lz -lopenblas -lgfortran -lquadmath -o ./bin/gemma
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gemma] Error 1
```

**Comment by pjotrp** [comment]
Openblas needs gfortran:libs:

https://aichamp.wordpress.com/2016/11/20/compiling-installing-openblas-in-ubuntu-16-04/

is there no package in brew for that?

**Comment by sjackman** [comment]
It's provided, but stored in an atypical location.
```sh
❯❯❯ ls /usr/local/lib/gcc/8/libgfortran*
/usr/local/lib/gcc/8/libgfortran.5.dylib
/usr/local/lib/gcc/8/libgfortran.a
/usr/local/lib/gcc/8/libgfortran.dylib
/usr/local/lib/gcc/8/libgfortran.spec
```
You could add `Formula["gcc"].lib/"gcc/8"` to the library search path.

It's not typical to link explicitly against the library `-lgfortran`. It's a language support library, similar to `-lstdlibc++ -lc -lgcc`. It's not typical to explicitly include those libraries in the link.

@tseemann Can you try using `inreplace` to remove `-lgfortran` from the link line?

**Comment by pjotrp** [comment]
Removing -lgfortran won't work. I know from experience.

**Comment by sjackman** [comment]
> Removing `-lgfortran` won't work. I know from experience.

The `libgfortran.5.dylib` is listed embedded in `libopenblas.dylib`.

```
❯❯❯ otool -L /usr/local/Cellar/openblas/0.3.3/lib/libopenblas.dylib
/usr/local/Cellar/openblas/0.3.3/lib/libopenblas.dylib:
	/Users/sjackman/.homebrew/opt/openblas/lib/libopenblasp-r0.3.3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/sjackman/.homebrew/opt/gcc/lib/gcc/8/libgfortran.5.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/Users/sjackman/.homebrew/opt/gcc/lib/gcc/8/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/Users/sjackman/.homebrew/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

`gemma` should not need to specify the indirect dependency on `libopenblas` explicitly.

If your experience is with Conda or static linking, then yes, you do need to specify indirect dependencies explicitly.

Homebrew/Linuxbrew (and most non-Conda package systems) use dynamic linking, where it is not necessary to explicitly list indirect dependencies.

**Comment by sjackman** [comment]
Similarly on Linux, the dependency of `libopenblas.so` on `libgfortran.so.3` is embedded in the shared library.

```
❯❯❯ patchelf --print-needed /home/sjackman/.linuxbrew/Cellar/openblas/0.3.3/lib/libopenblas.so
libm.so.6
libpthread.so.0
libgfortran.so.3
libgomp.so.1
libc.so.6
```

**Comment by pjotrp** [comment]
On Thu, Oct 11, 2018 at 04:17:08PM +0000, Shaun Jackman wrote:
>    Similarly on Linux, the dependency of libopenblas.so on
>    libgfortran.so.3 is embedded in the shared library.
> ❯❯❯ patchelf --print-needed /home/sjackman/.linuxbrew/Cellar/openblas/0.3.3/lib/
> libopenblas.so
> libm.so.6
> libpthread.so.0
> libgfortran.so.3
> libgomp.so.1
> libc.so.6

Interesting. That is actually the correct way.

Pj.

**Comment by sjackman** [comment]
@tseemann Can you try using inreplace to remove -lgfortran from the link line?

**Comment by tseemann** [comment]
```
en/include/eigen3  -isystem/usr/local/opt/eigen/include/eigen3 -Icontrib/catch-1.9.7 -Isrc  src/bslmm.o src/bslmmdap.o src/debug.o src/eigenlib.o src/fastblas.o src/gemma.o src/gemma_io.o src/gzstream.o src/lapack.o src/ldr.o src/lm.o src/lmm.o src/logistic.o src/main.o src/mathfunc.o src/mvlmm.o src/param.o src/prdt.o src/varcov.o src/vc.o -lgsl -lz -lopenblas -lquadmath -o ./bin/gemma
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/gemma] Error 1
```

I'll try removing that too

**Comment by pjotrp** [comment]
Whoa :). Thanks @tseemann and @sjackman! Everyday I learn something new.

**Comment by sjackman** [comment]
@pjotrp Would you like to tag a new stable release of Gemma that fixes this build issue?

**Comment by pjotrp** [comment]
The problem is that all other build systems require these fortran libs openblas :/. I believe Brew is doing the right thing. Even so, I need to upstream this first with Debian, Guix and Conda. So, if you don't mind, have brew patch it for now. Next release it won't be necessary. I promise.

**Comment by sjackman** [comment]
Cool. I believe it's only statically linking distributions that need to specify these libraries explicitly. As far as I know, that's only Conda. I'm not sure about Guix though.

**Pull request closed without merging**
