### PR TITLE
edirect: Fix PERL5LIB path so it works on macos

### PR DESCRIPTION
**Pull request by christiam**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
@christiam i am unsure how it passed the MacOS tests here. what was the error you were getting?

**Comment by christiam** [comment]
> @christiam i am unsure how it passed the MacOS tests here. what was the error you were getting?

Here are the errors I got: [edirect-mac-error.log.gz](https://github.com/brewsci/homebrew-bio/files/3832218/edirect-mac-error.log.gz)

**Comment by tseemann** [comment]
Your bug is `501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)` which is an older bug I used to encounter.

Are you using brew perl or MacOS system perl?
```
which perl
perl -V
```

**Comment by christiam** [comment]
It failed with both system perl (5.18.4) and brew perl (5.30.0).

**Comment by christiam** [comment]
@tseemann - would you have any additional feedback on this PR?

**Pull request closed without merging**
