### PR TITLE
squeakr 0.6

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
On MacOS:

```
g++ -std=c++11 -Wall   -Ofast -msse4.2 -D__SSE4_2_ -m64 -I. -Iinclude  -c -o obj/gqf_file.o src/gqf/gqf_file.c
src/gqf/gqf_file.c:51:8: error: use of undeclared identifier 'posix_fallocate'
        ret = posix_fallocate(qf->runtimedata->f_info.fd, 0, total_num_bytes);
              ^
1 error generated.
make: *** [obj/gqf_file.o] Error 1
```

**Comment by tseemann** [comment]
Filed upstream: https://github.com/splatlab/squeakr/issues/40

**Comment by jonchang** [comment]
Looks like v0.7 is out which fixes the build error on macOS?

**Comment by tseemann** [comment]
I will do a new PR for 0.7

**Pull request closed without merging**
