### PR TITLE
Maker: revision bump

### PR DESCRIPTION
**Pull request by dmohadjel**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by dmohadjel** [comment]
Error on CircleCI for Linux:
```
Fetching http://www.cpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.62.tar.gz ... OK
Configuring DBD-SQLite-1.62 ... ! No MYMETA file is found after configure. Your toolchain is too old?
! Configure failed for DBD-SQLite-1.62. See /tmp/maker-20190703-30375-1ospimq/maker/.brew_home/.cpanm/work/1562184007.32372/build.log for details.
N/A
``` 

I tried to run `brew install -dv https://raw.githubusercontent.com/dmohadjel/homebrew-bio/maker/Formula/maker.rb` on the `docker02` machine to take a look at the `…/build.log` file, however I don't arrive at the menu with the option for interacting with the shell in the temporary build directory after running the command.

**Comment by sjackman** [comment]
Try…
```sh
brew install -sdv maker
```
That displayed the prompt for me:
```
Successfully installed Inline-C-0.81
13 distributions installed
/usr/bin/curl --version
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
FormulaUnavailableError: No available formula with the name "xorg" 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
```
Here's a gist of the `build.log` file.
https://gist.github.com/sjackman/a252891dde60f3cb73b5766fdf776e0a

The relevant error lines are:
```
Unpacking DBD-SQLite-1.62.tar.gz
Entering DBD-SQLite-1.62
Checking configure dependencies from META.json
Checking if you have File::Spec 0.82 ... Yes (3.78)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Checking if you have DBI 1.57 ... Yes (1.642)
Configuring DBD-SQLite-1.62
Running Makefile.PL
DBI.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
-> N/A
```
https://gist.github.com/sjackman/a252891dde60f3cb73b5766fdf776e0a#file-maker-build-log-L201-L210

The PERL module `DBI` has a mismatched Perl version. The two installed versions of Perl are…
```
❯❯❯ which -a perl
/home/linuxbrew/.linuxbrew/bin/perl
/usr/bin/perl
❯❯❯ /home/linuxbrew/.linuxbrew/bin/perl --version
This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-thread-multi
❯❯❯ /usr/bin/perl --version
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 73 registered patches, see perl -V for more detail)
```

So my best guess is that somehow it's confused about which version of `perl` it's using. They system's perl, or Homebrew's perl.

**Comment by dmohadjel** [comment]
I haven't been having much success fixing the issue so far, any suggestions on what I should try?

**Comment by sjackman** [comment]
Since we suspect that multiple versions of Perl are to blame, to aid trouble shooting you could try removing the brewed version of Perl (`brew remove perl` and remove the `perl` dependency from `maker`), and install `maker` and see what happens, and you can try removing the system version of Perl (`apt-get remove perl`), and install `maker` and see what happens, and that may give you some insight into the problem.

**Comment by sjackman** [comment]
Ultimately we'll need both the system and brewed version of Perl installed. The above suggestion is only to aid troubleshooting and learn about the root cause of the problem.

**Comment by dmohadjel** [comment]
So an issue I wanted to mention is that I am trying to run the following commands:
```
ssh docker02
docker pull linuxbrew/brew
docker run -it --rm linuxbrew/brew
brew install -sdv maker
```
However, after I do `docker run -it --rm linuxbrew/brew`, the `brew install -sdv maker` command will fail and say the following:
```
Error: No available formula with the name "bioperl" (dependency of maker)
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
/usr/bin/curl -q --show-error --user-agent Linuxbrew/2.1.6-44-g895467a\ \(Linux\;\ x86_64\ Ubuntu\ 16.04.6\ LTS\)\ curl/7.47.0 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Abioperl\+extension\%3Arb\&per_page=100 --header application/vnd.github.v3\+json --write-out '
'\%\{http_code\} --dump-header /tmp/github_api_headers20190704-25776-8d4fxl
Error: No formulae found in taps.
```
I'd need to get this to work if I want to try removing the system version of Perl and testing the installation.

I also wanted to ask what specifically I'd have to remove from `maker` to completely remove the `perl` dependency.

**Comment by sjackman** [comment]
```diff
 ssh docker02
 docker pull linuxbrew/brew
 docker run -it --rm linuxbrew/brew
+brew tap brewsci/bio
 brew install -sdv maker
```

> I also wanted to ask what specifically I'd have to remove from maker to completely remove the perl dependency.

Remove this line:
https://github.com/brewsci/homebrew-bio/blob/8feed8f48623f0a917cd7bfe39628261cf5c672e/Formula/maker.rb#L31

**Comment by dmohadjel** [comment]
It seems the same problem occurs in both circumstances when trying to install `maker`. It happened when the brewed version of Perl was removed, and when the system version was removed:
```
DBI.c: loadable library and perl binaries are mismatched (got handshake key 0xce00080, needed 0xcd00080)
```

**Comment by sjackman** [comment]
Where and how are `DBI.pm` and `DBI.so` installed? You could try explicitly reinstalling DBI with `cpanm DBI`.

**Comment by dmohadjel** [comment]
Yeah if I just run `cpanm DBD::SQLite` and try to install `maker`, it will successfully install. 
```
root@ce430ed669d0:/home/linuxbrew# cpanm DBD::SQLite
--> Working on DBD::SQLite
Fetching http://www.cpan.org/authors/id/I/IS/ISHIGAKI/DBD-SQLite-1.62.tar.gz ... OK
==> Found dependencies: DBI
--> Working on DBI
Fetching http://www.cpan.org/authors/id/T/TI/TIMB/DBI-1.642.tar.gz ... OK
Configuring DBI-1.642 ... OK
Building and testing DBI-1.642 ... OK
Successfully installed DBI-1.642
Configuring DBD-SQLite-1.62 ... OK
Building and testing DBD-SQLite-1.62 ... OK
Successfully installed DBD-SQLite-1.62
2 distributions installed
```
In this case it's not going to be included in the bottle though, right?

**Comment by sjackman** [comment]
That's right. You'd need to run and troubleshoot
```
export PERL5LIB=$HOME/testing
cpanm -l ~/testing DBD::SQLite
```

**Comment by dmohadjel** [comment]
```
export PERL5LIB=$HOME/testing
cpanm -l ~/testing DBD::SQLite
```
Running these commands will just successfully install the modules. Do you have any ideas from this point? I haven't been able to find a clear solution online. Seems the problem is arising when: 
```
PERL5LIB=/home/linuxbrew/.linuxbrew/Cellar/maker/2.31.10_1/perl5/lib/perl5:/home/linuxbrew/.linuxbrew/opt/bioperl/libexec/lib/perl5
```

**Comment by sjackman** [comment]
Does `bioperl` install a conflicting version of `DBI`?  I bet that's the problem. Does `brew install bioperl && brew test bioperl` succeed? If you not, you'll need to bump the version of `bioperl`.

**Comment by dmohadjel** [comment]
Running `brew install bioperl && brew test bioperl` does fail and reports the following error:
```
Error: brewsci/bio/bioperl: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was <126>.
```
I'll bump the revision of `bioperl`.

**Comment by sjackman** [comment]
Superseded by PR https://github.com/brewsci/homebrew-bio/pull/674

**Pull request closed without merging**
