### PR TITLE
Maker: bump revision for perl

### PR DESCRIPTION
**Pull request by lcoombe**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by lcoombe** [comment]
Errors on circleCI:
```failed: brew install --verbose --build-bottle brewsci/bio/maker```

```failed: brew install --devel brewsci/bio/maker --verbose --build-bottle```

**Comment by lcoombe** [comment]
`brew install maker` works fine for me locally:
```==> cpanm -l /projects/btl/lcoombe/linuxbrew/Cellar/maker/2.31.10_1/perl5 IO::All Perl::Unsafe::Signals Want forks forks::shared
==> cpanm -l /projects/btl/lcoombe/linuxbrew/Cellar/maker/2.31.10_1/perl5 Bit::Vector DBD::SQLite Inline::C
==> (echo no; yes '') |perl Build.PL
==> ./Build install
==> Caveats
Optional compoments of MAKER that can be installed using brew:
  infernal
  mir-prefer
  snoscan
  trnascan

Optional components of MAKER that are not available using brew:
  GeneMarkS and GeneMark-ES. Download from http://exon.biology.gatech.edu
  FGENESH 2.4 or higher. Purchase from http://www.softberry.com

MAKER is available for academic use under either the Artistic
License 2.0 developed by the Perl Foundation or the GNU General
Public License developed by the Free Software Foundation.

MAKER is not available for commercial use without a license. Those
wishing to license MAKER for commercial use should contact Beth
Drees at the University of Utah TCO to discuss your needs.
==> Summary
🍺  /projects/btl/lcoombe/linuxbrew/Cellar/maker/2.31.10_1: 885 files, 49.4MB, built in 7 minutes 57 seconds
```

**Comment by lcoombe** [comment]
Error on CircleCI (mac):
```
==> brew uninstall --devel --force brewsci/bio/maker
==> FAILED
Usage: brew uninstall, rm, remove [options] formula

Uninstall formula.

    -f, --force                      Delete all installed versions of the
                                     formula
        --ignore-dependencies        Don't fail uninstall, even if formula is
                                     a dependency of any installed formulae.
    -d, --debug                      Display any debugging information.
    -h, --help                       Show this message.
Error: invalid option: --devel```

**Comment by sjackman** [comment]
```
Building and testing Inline-C-0.80 ... FAIL
! Installing Inline::C failed. See /tmp/maker-20190511-32807-xoj4jh/maker/.brew_home/.cpanm/work/1557536964.34804/build.log for details. Retry with --force to force install it.
```
You can ssh into a CircleCI build while it's building. I'll do that to fetch this `…/build.log` file and find out what the error is.

**Comment by lcoombe** [comment]
> You can ssh into a CircleCI build while it's building. I'll do that to fetch this `…/build.log` file and find out what the error is.

> I've opened PR [Homebrew/homebrew-test-bot#257](https://github.com/Homebrew/homebrew-test-bot/pull/257) to address this issue. I'll merge it once CI passes.

Thank you Shaun!

**Comment by sjackman** [comment]
Merged PR https://github.com/Homebrew/homebrew-test-bot/pull/257

**Comment by sjackman** [comment]
This build on CircleCI was successful on Linux (https://circleci.com/gh/brewsci/homebrew-bio/5973). So I can't say why `Inline::C` failed last time. Try rebasing this PR onto `origin/master` and give it another go!

**Comment by lcoombe** [comment]
Strange -- sounds good! (fingers crossed)

**Comment by lcoombe** [comment]
Circle-CI is happy now, but Azure is still failing:
```
Building and testing Inline-C-0.81 ... FAIL
! Installing Inline::C failed. See /tmp/maker-20190513-10049-t50nq3/maker/.brew_home/.cpanm/work/1557775501.12322/build.log for details. Retry with --force to force install it.
13 distributions installed
```

**Comment by sjackman** [comment]
You can ignore the Azure failure. Bottles are built on CircleCI. Please merge this PR.

**Comment by sjackman** [comment]
Thank you, Lauren!

**Pull request closed without merging**
