### PR TITLE
indel-seq-gen 2.1.03

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
`fails_with ;clang` didn't help - still fails with gcc8 on macos...

```
g++-8 -DHAVE_CONFIG_H -I. -I..  -I../lib -I../lib   -g -O2 -MT inClade.o -MD -MP -MF .deps/inClade.Tpo -c -o inClade.o inClade.cpp
random.cpp: In function 'void mt_next_state()':
random.cpp:148:5: error: reference to 'next' is ambiguous
     next = state;
     ^~~~
In file included from /usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/bits/stl_algobase.h:66,
                 from /usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/bits/char_traits.h:39,
                 from /usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/ios:40,
                 from /usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/ostream:38,
                 from /usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/iostream:39,
                 from random.h:6,
                 from random.cpp:3:
/usr/local/Cellar/gcc/8.1.0/include/c++/8.1.0/bits/stl_iterator_base_funcs.h:213:5: note: candidates are: 'template<class _InputIterator> _InputIterator std::next(_InputIterator, typename std::iterator_traits<_Iter>::difference_type)'
     next(_InputIterator __x, typename
     ^~~~
random.cpp:68:18: note:                 'uint32_t* next'
 static uint32_t *next;
                  ^~~~
random.cpp: In function 'uint32_t mt_rand()':
```

**Comment by jonchang** [comment]
Looks like a type mismatch. Try changing `next` to `*next`?

**Comment by sjackman** [comment]
Report this bug to the upstream authors. A hack workaround that may work is to change `next` to `::next` to disambiguate it from `std::next`.

**Comment by tseemann** [comment]
Superseded by #356

**Pull request closed without merging**
