### PR TITLE
any2fasta 0.4.2

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
As expected...

```
Error: 1 problem in 1 formula detected
  * GitHub repository too new (<30 days old)
```

image

**Comment by jonchang** [comment]
@tseemann looks like this will have passed its 30 day check...

**Comment by sjackman** [comment]
```
Testing tap brewsci/bio with:
  origin/master   a192787 (ntedit: Update the citation)
  HEAD            a192787 (ntedit: Update the citation)
  diff_start_sha1 91e7bf62b76427f3c211527ee9266dc03ed9146c
  diff_end_sha1   623a0ea2db584b48e905ca9d5a690e4f62af9e15

==> brew readall --aliases brewsci/bio
Error: No available formula with the name "brewsci/bio/any2fasta"
```
https://circleci.com/gh/brewsci/homebrew-bio/6104

@tseemann Can you try rebasing this PR onto `origin/master`?

**Comment by sjackman** [comment]
Merged. Thanks, Torsten!

**Pull request closed without merging**
