### PR TITLE
minced 0.2.0

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
Before merging this one, let's see if we can resolve the Java dependency issue on Linux, if you're able to wait.

**Comment by sjackman** [comment]
This PR https://github.com/Linuxbrew/brew/pull/629 modifies `depends_on :java` to install `jdk` if it's not provided by the host.

**Comment by sjackman** [comment]
```
==> SKIPPING: brewsci/bio/minced
Java 1.8+ is required to install this formula.
JavaRequirement unsatisfied!
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
To install it, run:
  brew install jdk
```
https://circleci.com/gh/brewsci/homebrew-bio/786

**Comment by sjackman** [comment]
I've merged Linuxbrew/brew#629! I triggered a rebuild of CircleCI.

**Comment by sjackman** [comment]
Success! We have bottles for both Linux and macOS!

**Comment by tseemann** [comment]
Do we need to rebuild figtree, gepard, etc ?

**Comment by sjackman** [comment]
Could do, yep. It's a bit tricky do that and keep the old macOS bottle. You can bump the revision and rebuild both bottles. That's easy. Or you can just leave them without Linux bottles, which is fine too I think.

**Pull request closed without merging**
