### PR TITLE
bwa-mem2 2.2.1

### PR DESCRIPTION
**Pull request by gl-eb**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by heuermh** [comment]
@gl-eb Might you be able to rebase this pull request?

**Comment by gl-eb** [comment]
Done!

**Comment by heuermh** [comment]
Sorry, will have to ask you to do it again, to pick up fixes to CI. 😬 

Alternatively, I see some force pushed commits above, but I'm not certain how those were done?
```
$ git remote add gl-eb https://github.com/gl-eb/homebrew-bio.git
$ git fetch gl-eb
$ git checkout gl-eb/bump-bwa-mem2-2.2.1

# rebase, would require force push
$ git rebase -i upstream/develop

# or create merge commit, would also require a push to your branch?
$ git pull upstream/develop --no-rebase
```

**Comment by gl-eb** [comment]
No worries, my part is easy to do. Thanks for trying to get this to work!

**Comment by gl-eb** [comment]
I think the issue is an incompatibility between bwa-mem2 v2.2.1 with GCC 11 and higher. There's a [fix](https://github.com/bwa-mem2/bwa-mem2/pull/205) for this already, but it has not been tagged as a release.

Does Homebrew allow formulas where tag and revision do not match? Otherwise the only other option would be to ask the bwa-mem2 maintainers to tag a new release. Or am I wrong here?

I am happy to do either, though the latter option could take longer. Do you have a preference @heuermh ?

**Comment by heuermh** [comment]
Yes, the CI issues have been resolved and now we're left with the actual issue with `bwa-mem2`!

Cleanest option is to wait until a new release happens upstream, otherwise we could patch and/or create a homebrew-specific revision with that commit included.  Perhaps also [this patch](https://github.com/bwa-mem2/bwa-mem2/issues/93#issuecomment-886320419)?  I am not sure what the appetite for such here is though.

**Comment by YoshitakaMo** [comment]
@gl-eb I've created bwa-mem2 binaries for Apple Silicon (https://github.com/brewsci/homebrew-bio/commit/658fb604a1b3a870b08b4ac144cad2c8d7edb257), though I don't guarantee whether it works as expected. If you are interested, please test it.

**Pull request closed without merging**
