### PR TITLE
trinity 2.8.6

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
Failed on CircleCI on Linux
```
checking for unzip... no
configure: error: Could not find required tool for UNZIP
configure exiting with result code 1
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/7930

Try `provided_by_macos "unzip"`

**Comment by jonchang** [comment]
That’s an openjdk error I think. That I’m working on over in Linuxbrew-core

**Comment by sjackman** [comment]
You could use `adoptopenjdk` on Linux instead of `openjdk`.

**Comment by sjackman** [comment]
CircleCI on Linux
```
Error encountered::  <!----
CMD: /home/linuxbrew/.linuxbrew/bin/bowtie2-build --threads 2 -o 3 /tmp/trinity-test-20191116-26966-13vlm1x/trinity_out_dir/chrysalis/inchworm.K25.L25.fa.min100 /tmp/trinity-test-20191116-26966-13vlm1x/trinity_out_dir/chrysalis/inchworm.K25.L25.fa.min100 1>/dev/null 2>tmp.26969.1573911945.stderr

Errmsg:
/usr/bin/env: 'python': No such file or directory
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/7932

**Comment by sjackman** [comment]
@jonchang You could try this PR again with GitHub Actions, if you liked.

**Pull request closed without merging**
