### PR TITLE
roary 3.12.0

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
```
  * C: 49: col 1: Trailing whitespace detected.
```

**Comment by sjackman** [comment]
@tseemann I think the only thing holding back this PR was `* C: 49: col 1: Trailing whitespace detected.` Would you like to try rebasing this PR onto `develop`?

**Comment by tseemann** [comment]
Thanks @jonchang for helping me get the commands right:
```
git fetch upstream
git checkout roary
git rebase upstream/develop
```

**Comment by sjackman** [comment]
```
==> brew test brewsci/bio/roary --verbose
2950
Testing brewsci/bio/roary
2951
==> /home/linuxbrew/.linuxbrew/Cellar/roary/3.12.0/bin/roary -w 2>&1
2952
Error: brewsci/bio/roary: failed
2953
An exception occurred within a child process:
2954
  Test::Unit::AssertionFailedError: </3\.12\.0/> was expected to be =~
2955
<"Use of uninitialized value in require at /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.1/lib/perl5/5.30.1/x86_64-linux-thread-multi/Encode.pm line 70.\n" +
2956
"3.13.0\n">.
2957
```
https://github.com/brewsci/homebrew-bio/pull/756/checks?check_run_id=435420843#step:4:2953

**Comment by tseemann** [comment]
old version, will replace.

**Pull request closed without merging**
