### PR TITLE
Miscellaneous fixes/improvements to various formulas

### PR DESCRIPTION
**Pull request by alexreg**
* Use formula-based rather than hard-coded paths.
* Replace `#{bin}` with `#{opt_bin}` in tests, which doesn't rely on linkage of formual.
* Remove obsolete formula *apbspdb2pqr* (which also depends on obsolete Python v2).
* Stylistic conventions

- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by alexreg** [comment]
@jonchang I think this is all in order now. The only formula I couldn't upgrade to python@3.10 is `apbs`, which seems to have problems with undefined symbols.

**Comment by alexreg** [comment]
Ah, it seems there are some pre-existing issues with `velvet` and `gmap-gsnap`. I managed to resolve the former already, and am working on the latter.

**Comment by jonchang** [comment]
> Replace #{bin} with #{opt_bin} in tests, which doesn't rely on linkage of formual.
We don't need to make this change.

All changes from python -> python3.10 need revision bumps. In addition, I suggest updating all python3 dependencies to rely on a function that can easily be changed. See `brew cat bde` from homebrew/core for an example.

**Comment by alexreg** [comment]
@jonchang Ah yes, I should have remembered about the revision bumps!

Re `opt_bin`, it's not necessary, though it's considered "good practice" (at least by the maintainers of homebrew-core). So I'll leave that in, unless you prefer I take it out.

Cheers.

**Comment by jonchang** [comment]
> Re opt_bin, it's indeed not necessary, though it's considered "good practice" (at least by the maintainers of homebrew-core). So I'll leave that in, unless you prefer I take it out.

`opt_bin` is not necessary in `test do` blocks because you can't `brew test` unlinked formulae.

```console
% brew install hello && brew unlink hello && brew test hello
==> Downloading https://ghcr.io/v2/homebrew/core/hello/manifests/2.12.1
==> Downloading https://ghcr.io/v2/homebrew/core/hello/blobs/sha256:a0103553329c
==> Pouring hello--2.12.1.arm64_monterey.bottle.tar.gz
/opt/homebrew/Cellar/hello/2.12.1: 11 files, 177KB
==> Running `brew cleanup hello`...
Unlinking /opt/homebrew/Cellar/hello/2.12.1... 3 symlinks removed.
Error: hello is not linked
```

**Comment by alexreg** [comment]
> `opt_bin` is not necessary in `test do` blocks because you can't `brew test` unlinked formulae.

Okay, I've now undone this change, fixed gmap-gsnap, and another style issue. Hopefully tests will past now (or almost).

**Comment by alexreg** [comment]
@jonchang Looks like the CI checks were passing but timed out... what should we do about this?

**Comment by alexreg** [comment]
?

**Comment by alexreg** [comment]
@jonchang @YoshitakaMo Hello, did this get (partially) merged in the end? If not, may I ask why it was closed?

**Pull request closed without merging**
