### PR TITLE
fasttree: bump revision for gcc

### PR DESCRIPTION
**Pull request by gaberoo**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

```
 ❯ FastTree -help
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libgomp.1.dylib
  Referenced from: /usr/local/bin/FastTree
  Reason: image not found
[1]    8710 abort      FastTree -help
```

### CODE REVIEW

**Comment by gaberoo** [comment]
@sjackman, I've also made the dependence on gcc a function of whether `build.with? "openmp"` was selected. I thought this made the most sense, but it doesn't have to be.

**Comment by sjackman** [comment]
Except for the test failure, looks good to me.

```
failed: brew test --verbose parsnp
Testing brewsci/bio/parsnp
==> /usr/local/Cellar/parsnp/1.2_2/bin/parsnp -v 2>&1
sh: line 1: 19722 Abort trap: 6           /usr/local/Cellar/parsnp/1.2_2/bin/parsnp -v 2>&1
Error: brewsci/bio/parsnp: failed
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: <0> expected but was <134>.
```
https://circleci.com/gh/brewsci/homebrew-bio/6142

Are you able to reproduce this error on your local machine?

**Comment by gaberoo** [comment]
Indeed, `parsnp` is also broken. Why that causes `fasttree` to fail I'm not sure.

**Comment by gaberoo** [comment]
In the mean time, I'm fixing `parsnp` as well.

**Comment by sjackman** [comment]
> Indeed, parsnp is also broken. Why that causes fasttree to fail I'm not sure.

`parsnp` depends on `fasttree`, so it's testing `parsnp` to ensure that this change to `fastree` doesn't break `parsnp.`

**Pull request closed without merging**
