### PR TITLE
mosdepth 0.2.3

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
Why is it returning a different code in travis but not in the others?
Can i ignore?
@sjackman

**Comment by sjackman** [comment]
```
1.00s==> brew test brewsci/bio/mosdepth --verbose
Testing brewsci/bio/mosdepth
==> /home/linuxbrew/.linuxbrew/Cellar/mosdepth/0.2.3/bin/mosdepth --version 2>&1
Error: brewsci/bio/mosdepth: failed
<0> expected but was
<1>.
==> FAILED
```
https://travis-ci.org/brewsci/homebrew-bio/builds/396025920#L2593

I'm not sure, but yes, you can ignore a failure on TravisCI. TravisCI is mostly there to help troubleshooting when CircleCI fails.

**Comment by tseemann** [comment]
@sjackman I can't seem to pull this:
```
Patch: https://github.com/LinuxbrewTestBot/homebrew-bio/compare/brewsci:master...pr-322.patch
curl: (22) The requested URL returned error: 404 Not Found
```

I assume there is no bottle made, as
https://bintray.com/linuxbrew/bottles-bio/mosdepth
is 404.

Does TRAVIS prevent bottles?

**Comment by sjackman** [comment]
> Does TRAVIS prevent bottles?

No, that's not the issue. I'll look into it.

**Comment by sjackman** [comment]
Have you tried building `mosdepth` from source? Could you please add a comment above `depends_on :linux` indicating that it's due to using the precompiled Linux binary, and explaining why?

**Comment by sjackman** [comment]
Probably an intermittent failure. I've triggered a transfer of the bottles from CircleCI to Bintray, which appeared to work this time around.

**Comment by sjackman** [comment]
Thanks for this package! I've been meaning to try it out.

**Pull request closed without merging**
