### PR TITLE
indel-miner 0.2

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
Travis is trolling me again.  🍏

**Comment by sjackman** [comment]
Travis is a cranky SOB.
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -lbam
```
https://travis-ci.org/brewsci/homebrew-bio/builds/428894053#L2367-L2374

In a perfect world, TravisCI would be 🍏, but I'm fine with ignoring it.

**Comment by tseemann** [comment]
It's statically linking to its bundled samtool-0.1.19 libbam.a i thought.

**Comment by tseemann** [comment]
@sjackman I can't get the bottles onto bintray either. Even the lambda is timing out.

**Comment by sjackman** [comment]
If you mean the message `{"message": "Endpoint request timed out"}` it always says that after 30s. That's unfortunately "normal". Wait five minutes, then check the page https://github.com/LinuxbrewTestBot/homebrew-bio/releases or http://bintray.com/linuxbrew/bottles-bio/indel-miner#files to see if it was successful in transferring the bottle.

Ah, in this case though it was CircleCI that failed us. That's the first time that I've seen that so far.
See https://circleci.com/workflow-run/190af1b5-fa2d-4bb6-bd26-387bed7c8894
The `collect-bottles` job hasn't yet run.

`git commit --amend` and `git push tseemann indel-miner-0.2 --force` to trigger a rebuild.

**Comment by tseemann** [comment]
```
brewsci/bio/indel-miner:
Warning: Unable to create issue comment: GitHub {
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}

The GitHub credentials in the macOS keychain may be invalid.
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
Error: 1 problem in 1 formula detected
  * Dependency 'ncurses' may be unnecessary as it is provided by macOS; try to build this formula without it.
```
Oddly, it built macos once yesterday ok.

**Comment by sjackman** [comment]
CircleCI on Linux
```
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=1 -I. bamshuf.c -o bamshuf.o
/usr/bin/ld: cannot find -lbam
collect2: error: ld returned 1 exit status
```
https://circleci.com/gh/brewsci/homebrew-bio/4163

**Comment by tseemann** [comment]
Right back at you stale bot!

**Pull request closed without merging**
