### PR TITLE
shovill 1.0.0

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by tseemann** [comment]
```
configure: error: HTSlib development files not found
Samtools uses HTSlib to parse bioinformatics file formats etc.  Building it
requires an unpacked HTSlib source tree (which will be built in conjunction
with samtools) or a previously-installed HTSlib.  In either case you may
need to configure --with-htslib=DIR to locate the appropriate HTSlib.
FAILED.  You must supply an HTSlib in order to build samtools successfully.
==> Formula
Path: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-co
```

Why i am getting samtools compilation errors when I am just `depends_on `samtools`` ?
Does this mean there is a missing binary package for samtools 1.9 ?

**Comment by tseemann** [comment]
Weird travis error about samtools being compiled with htslib?

```
checking for hts_version in -lhts... no
configure: error: HTSlib development files not found
Samtools uses HTSlib to parse bioinformatics file formats etc.  Building it
requires an unpacked HTSlib source tree (which will be built in conjunction
with samtools) or a previously-installed HTSlib.  In either case you may
need to configure --with-htslib=DIR to locate the appropriate HTSlib.
FAILED.  You must supply an HTSlib in order to build samtools successfully.
```

**Comment by sjackman** [comment]
Yes, it looks like `samtools` is missing a bottle. I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/8733 to build a bottle for it.

**Comment by sjackman** [comment]
Michka merged the `samtools` bottle.

**Pull request closed without merging**
