### PR TITLE
poretools: import from brewsci/science & updated to python3

### PR DESCRIPTION
**Pull request by suujia**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by suujia** [comment]
```
pip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-zrayu4kr/
```

also warning for cython unused functions

**Comment by suujia** [comment]
```
pip3 install pipenv
pip2 install pipenv
```

**Comment by tseemann** [comment]
Maybe many of those python modules may need updating?

**Comment by sjackman** [comment]
I attend Porecamp this past week. There I learned that the primary purpose of converting FAST5 to FASTQ files is no longer needed. Albacore does that. NanoPlot can be used for plotting and reporting https://github.com/wdecoster/NanoPlot
It seems to me that we can remove `poretools`.

**Comment by sjackman** [comment]
@suujia Please open a PR to remove `poretools` from ORCA.

**Pull request closed without merging**
