### PR TITLE
gfaview: deprecate

### PR DESCRIPTION
**Pull request by SeekingMeaning**
- [X] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

Repository https://github.com/lh3/gfa1 is archived

### CODE REVIEW

**Review by sjackman — CHANGES_REQUESTED** [review]
I'd prefer to keep `gfaview` in Brewsci/bio. This tool is still very useful despite not being maintained.

**Comment by SeekingMeaning** [comment]
What about keeping this deprecated indefinitely? The repo description says to use https://github.com/lh3/gfatools instead

**Comment by sjackman** [comment]
Ah, I missed that. Yeah, deprecating indefinitely works for me. Thanks!

**Comment by sjackman** [comment]
Is it possible to add a comment to the reason suggesting that the user use `gfatools` instead?

**Pull request merged**
