### PR TITLE
pymol 2.5.0

### PR DESCRIPTION
**Pull request by YoshitakaMo**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

upgrade to version 2.5.0.

### CODE REVIEW

**Comment by sjackman** [comment]
`Error: mesa: no bottle available!`
https://github.com/brewsci/homebrew-bio/pull/1351/checks?check_run_id=2558963264#step:5:1507

https://github.com/Homebrew/linuxbrew-core/blob/c29bd9476bdf880976ce0aa849e96cb568b572f9/Formula/mesa.rb#

`mesa` is not currently bottled for Linux. I don't see an open PR.

I triggered a bottle build here:
https://github.com/Homebrew/linuxbrew-core/actions/runs/833812175

🤞

**Comment by sjackman** [comment]
`llvm` and `mesa` were lacking bottles. `llvm` is now bottled. I'm trying to bottle `mesa`, but both mesa3d.org and freedesktop.org are down. :cry:
https://github.com/Homebrew/linuxbrew-core/runs/2568327688?check_suite_focus=true#step:5:91

**Comment by sjackman** [comment]
@imichka opened PR https://github.com/Homebrew/linuxbrew-core/pull/23230 to fix and bottle `mesa`.

**Comment by sjackman** [comment]
`mesa` is bottled now. This PR is now waiting on a bottle for `qt@5`. See PR https://github.com/Homebrew/linuxbrew-core/pull/23174

**Comment by YoshitakaMo** [comment]
```
Run actions/checkout@master
  with:
    repository: brewsci/homebrew-bio
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
  env:
    HOMEBREW_NO_ANALYTICS: 1
    HOMEBREW_NO_AUTO_UPDATE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
/usr/bin/docker exec  53297909f56fbe73794e053e7198e583a98fcabe9491508eda0afac34b04f841 sh -c "cat /etc/*release | grep ^ID"
Syncing repository: brewsci/homebrew-bio
Getting Git version info
  Working directory is '/__w/homebrew-bio/homebrew-bio'
  /usr/bin/git version
  git version 2.32.0
Deleting the contents of '/__w/homebrew-bio/homebrew-bio'
Initializing the repository
  /usr/bin/git init /__w/homebrew-bio/homebrew-bio
  /__w/homebrew-bio/homebrew-bio/.git: Permission denied
  Error: The process '/usr/bin/git' failed with exit code 1
```

I couldn't figure out this error. Could anyone help me?

**Comment by vsheg** [comment]
I use macOS; do I have to wait for the formula upgrade until it works on Linux? :)

**Comment by YoshitakaMo** [comment]
Hi, @vsheg. Finally, the longstanding issues with `mesa`, `qt@5` and `pyqt@5` have been all resolved (https://github.com/Homebrew/homebrew-core/pull/84181). It is now possible to build the latest PyMOL 2.5.0 on both macOS and Linux.
Just today, one of the dependencies of PyMOL has been changed, so I have to deal with it. But it will be resolved within a few days. Please stay tuned.

**Pull request merged**
