### PR TITLE
dida: import from brewsci/science

### PR DESCRIPTION
**Pull request by gejessicama**

### CODE REVIEW

**Comment by sjackman** [comment]
Merged. Thank you for your second contribution to Brewsci/bio, Jessica! 💯

Would you like to migrate Trans-ABySS next? If so, open the PR, and if you have any questions, we can discuss it on the GitHub on the PR comments. Don't worry if it doesn't yet install or fails tests. We can tackle them together.

**Comment by sjackman** [comment]
Would you like to migrate Trans-ABySS next? If so, open the PR, and if you have any questions, we can discuss it on the GitHub on the PR comments. Don't worry if it doesn't yet install or fails tests. We can tackle them together.

**Comment by gejessicama** [comment]
Hi Shaun, will do re: Trans-ABySS. Anything to do for the changes that Torsten mentioned?

**Comment by sjackman** [comment]
Could you please add an URL to Torsten's comment?

**Pull request closed without merging**
