### PR TITLE
vg 1.6.0 (new formula) [WIP]

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by sjackman** [comment]
TravisCI
```
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:57:19: fatal error: bzlib.h: No such file or directory
```
https://travis-ci.org/brewsci/homebrew-bio/builds/360128511#L2777

**Comment by sjackman** [comment]
CircleCI
```
./autogen.sh: 35: ./autogen.sh: unzip: not found
```
https://circleci.com/gh/brewsci/homebrew-bio/1761
Depends on `unzip` to build.

**Comment by sjackman** [comment]
Odd error on macOS
```
configure.ac:42: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:44: error: possibly undefined macro: AC_MSG_FAILURE
make: *** [lib/libsnappy.a] Error 1
```
https://circleci.com/gh/brewsci/homebrew-bio/1762

**Comment by sjackman** [comment]
```
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:60:18: fatal error: lzma.h: No such file or directory
```
https://travis-ci.org/brewsci/homebrew-bio/builds/360501874#L2852
Depends on `xz`

**Comment by sjackman** [comment]
CircleCI on Linux
```
glibtool: link: c++  -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o  google/protobuf/stubs/.libs/atomicops_internals_x86_gcc.o google/protobuf/stubs/.libs/atomicops_internals_x86_msvc.o google/protobuf/stubs/.libs/bytestream.o google/protobuf/stubs/.libs/common.o google/protobuf/stubs/.libs/int128.o google/protobuf/stubs/.libs/io_win32.o google/protobuf/stubs/.libs/once.o google/protobuf/stubs/.libs/status.o google/protobuf/stubs/.libs/statusor.o google/protobuf/stubs/.libs/stringpiece.o google/protobuf/stubs/.libs/stringprintf.o google/protobuf/stubs/.libs/structurally_valid.o google/protobuf/stubs/.libs/strutil.o google/protobuf/stubs/.libs/time.o google/protobuf/.libs/arena.o google/protobuf/.libs/arenastring.o google/protobuf/.libs/extension_set.o google/protobuf/.libs/generated_message_util.o google/protobuf/.libs/generated_message_table_driven_lite.o google/protobuf/.libs/message_lite.o google/protobuf/.libs/repeated_field.o google/protobuf/.libs/wire_format_lite.o google/protobuf/io/.libs/coded_stream.o google/protobuf/io/.libs/zero_copy_stream.o google/protobuf/io/.libs/zero_copy_stream_impl_lite.o google/protobuf/.libs/any.pb.o google/protobuf/.libs/api.pb.o google/protobuf/stubs/.libs/mathlimits.o google/protobuf/.libs/any.o google/protobuf/.libs/descriptor.o google/protobuf/.libs/descriptor_database.o google/protobuf/.libs/descriptor.pb.o google/protobuf/.libs/duration.pb.o google/protobuf/.libs/dynamic_message.o google/protobuf/.libs/empty.pb.o google/protobuf/.libs/extension_set_heavy.o google/protobuf/.libs/field_mask.pb.o google/protobuf/.libs/generated_message_reflection.o google/protobuf/.libs/generated_message_table_driven.o google/protobuf/.libs/map_field.o google/protobuf/.libs/message.o google/protobuf/.libs/reflection_ops.o google/protobuf/.libs/service.o google/protobuf/.libs/source_context.pb.o google/protobuf/.libs/struct.pb.o google/protobuf/stubs/.libs/substitute.o google/protobuf/.libs/text_format.o google/protobuf/.libs/timestamp.pb.o google/protobuf/.libs/type.pb.o google/protobuf/.libs/unknown_field_set.o google/protobuf/.libs/wire_format.o google/protobuf/.libs/wrappers.pb.o google/protobuf/io/.libs/gzip_stream.o google/protobuf/io/.libs/printer.o google/protobuf/io/.libs/strtod.o google/protobuf/io/.libs/tokenizer.o google/protobuf/io/.libs/zero_copy_stream_impl.o google/protobuf/compiler/.libs/importer.o google/protobuf/compiler/.libs/parser.o google/protobuf/util/.libs/delimited_message_util.o google/protobuf/util/.libs/field_comparator.o google/protobuf/util/.libs/field_mask_util.o google/protobuf/util/internal/.libs/datapiece.o google/protobuf/util/internal/.libs/default_value_objectwriter.o google/protobuf/util/internal/.libs/error_listener.o google/protobuf/util/internal/.libs/field_mask_utility.o google/protobuf/util/internal/.libs/json_escaping.o google/protobuf/util/internal/.libs/json_objectwriter.o google/protobuf/util/internal/.libs/json_stream_parser.o google/protobuf/util/internal/.libs/object_writer.o google/protobuf/util/internal/.libs/protostream_objectsource.o google/protobuf/util/internal/.libs/protostream_objectwriter.o google/protobuf/util/internal/.libs/proto_writer.o google/protobuf/util/internal/.libs/type_info.o google/protobuf/util/internal/.libs/type_info_test_helper.o google/protobuf/util/internal/.libs/utility.o google/protobuf/util/.libs/json_util.o google/protobuf/util/.libs/message_differencer.o google/protobuf/util/.libs/time_util.o google/protobuf/util/.libs/type_resolver_util.o   -lpthread -L/home/linuxbrew/.linuxbrew/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/home/linuxbrew/.linuxbrew/lib -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/4.8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o  -pthread -O2 -g -Wl,--version-script=./libprotobuf.map   -pthread -Wl,-soname -Wl,libprotobuf.so.14 -o .libs/libprotobuf.so.14.0.0
g++-5: error: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o: No such file or directory
g++-5: error: /usr/lib/gcc/x86_64-linux-gnu/4.8/crtbeginS.o: No such file or directory
g++-5: error: /usr/lib/gcc/x86_64-linux-gnu/4.8/crtendS.o: No such file or directory
g++-5: error: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crtn.o: No such file or directory
Makefile:2896: recipe for target 'libprotobuf.la' failed
```
https://circleci.com/gh/brewsci/homebrew-bio/1766

@ekg Any thoughts on this error? For some reason `protobuf` is trying to link against GCC 4.8 object files, when CircleCI is using GCC 5.3. It's unusual to specifically name these object files, `crti.o` and friends. Normally the compiler takes care of that for you.

**Comment by tseemann** [comment]
@sjackman i can't see `vg` in bioconda so we can't borrow any tips from them

**Comment by ekg** [comment]
Could it be that it isn't aware of the brew GCC and is looking at the system's?

**Comment by sjackman** [comment]
> Could it be that it isn't aware of the brew GCC and is looking at the system's?

The brewed GCC is not installed. It is using the system GCC, which is version 5.4.0.

**Comment by ekg** [comment]
Interesting, I test on 5.4.0 (it's my laptop's gcc version). It looks like it's digging into /usr/lib/gcc/x86_64-linux-gnu/4.8 though, which is strange.

**Pull request closed without merging**
