### PR TITLE
salmon 0.14.1

### PR DESCRIPTION
**Pull request by dmohadjel**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by sjackman** [comment]
CircleCI on Linux
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURL_LIBRARY
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6850

Try adding…
```ruby
uses_from_macos "curl"
```

**Comment by sjackman** [comment]
CircleCI on macOS
```
[ 73%] Linking CXX executable unitTests
cd /tmp/salmon-20190719-5631-1kakj7h/salmon-0.14.1/src && /usr/local/Cellar/cmake/3.15.0/bin/cmake -E cmake_link_script CMakeFiles/unitTests.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/unitTests.dir/__/tests/UnitTests.cpp.o CMakeFiles/unitTests.dir/FragmentLengthDistribution.cpp.o CMakeFiles/unitTests.dir/__/external/install/src/rapmap/rank9b.cpp.o CMakeFiles/unitTests.dir/__/external/install/src/rapmap/bit_array.c.o  -o unitTests  -L/tmp/salmon-20190719-5631-1kakj7h/salmon-0.14.1/lib  -L/tmp/salmon-20190719-5631-1kakj7h/salmon-0.14.1/external/install/lib -Wl,-rpath,/tmp/salmon-20190719-5631-1kakj7h/salmon-0.14.1/lib -Wl,-rpath,/tmp/salmon-20190719-5631-1kakj7h/salmon-0.14.1/external/install/lib libsalmon_core.a libalevin_core.a -lgff /usr/local/lib/libboost_iostreams-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_timer-mt.a /usr/local/lib/libboost_chrono-mt.a /usr/local/lib/libboost_program_options-mt.a /usr/local/lib/libboost_regex-mt.a ../external/install/lib/libstaden-read.a /usr/lib/libcurl.dylib /usr/lib/libz.dylib ../external/install/lib/libdivsufsort.a ../external/install/lib/libdivsufsort64.a -lm /usr/local/lib/liblzma.a /usr/lib/libbz2.dylib /usr/local/lib/libtbbmalloc_proxy.dylib /usr/local/lib/libtbbmalloc.a /usr/local/lib/libtbb.a -all_load 
Undefined symbols for architecture x86_64:
  "_u_charFromName_64", referenced from:
      boost::icu_regex_traits::lookup_collatename(int const*, int const*) const in libboost_regex-mt.a(icu.o)
  "_u_charType_64", referenced from:
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
  "_u_digit_64", referenced from:
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
  "_u_isblank_64", referenced from:
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
  "_u_isspace_64", referenced from:
      boost::icu_regex_traits::lookup_classname(int const*, int const*) const in libboost_regex-mt.a(icu.o)
      boost::icu_regex_traits::isctype(int, unsigned long long) const in libboost_regex-mt.a(icu.o)
  "_u_tolower_64", referenced from:
      boost::icu_regex_traits::lookup_classname(int const*, int const*) const in libboost_regex-mt.a(icu.o)
ld: symbol(s) not found for architecture x86_64
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6849

I think these symbols are from `icu4c`. My best guess is to try adding
```ruby
depends_on "icu4c" if OS.mac?
```

@rob-p Salmon is failing to link on macOS while linking on the unit tests. Any thoughts on the above error message?

**Comment by sjackman** [comment]
CircleCI on Linux
```
g++-5: internal compiler error: Killed (program cc1plus)
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6861

This means that compiling Salmon exceeded the 4 GB of RAM available on CircleCI. Try reducing the number of parallel compiler processes from 4 to 2.
```ruby
ENV["MAKEFLAGS"] = "-j4" if ENV["CIRCLECI"]
```

**Comment by sjackman** [comment]
Same missing symbol errors on macOS, even with `depends_on "icu4c" if OS.mac?`.
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6860

**Comment by dmohadjel** [comment]
CircleCI on Linux
```
g++-5: internal compiler error: Killed (program cc1plus)
```
Okay I think I misunderstood the necessary change. The line:
```
ENV["MAKEFLAGS"] = "-j4" if ENV["CIRCLECI"]
```
was already included in the file.

**Comment by sjackman** [comment]
```
g++-5: internal compiler error: Killed (program cc1plus)
```
https://app.circleci.com/jobs/github/brewsci/homebrew-bio/6864

Same issue. Try one compiler process.

**Comment by jonchang** [comment]
Seems the build system isn't respecting MAKEFLAGS:

```
CMakeLists.txt
446:    BUILD_COMMAND CC=${CMAKE_C_COMPILER} CXX=${CMAKE_CXX_COMPILER} ${CMAKE_CURRENT_SOURCE_DIR}/external/boost_1_66_0/b2 -d0 -j2 ${BOOST_LIB_SUBSET} toolset=${BOOST_TOOLSET} ${BOOST_EXTRA_FLAGS} cxxflags=${BOOST_CXX_FLAGS} link=static install
```

**Comment by sjackman** [comment]
`… -d0 -j2 ${BOOST_LIB_SUBSET} …`
Yep, seems that way. If `-j2` is hardcoded, you can grep through the source for `-j2` and patch it with `inreplace`.

**Comment by tseemann** [comment]
Replaced with https://github.com/brewsci/homebrew-bio/pull/747

**Pull request closed without merging**
