### PR TITLE
phlawd 3.4b

### PR DESCRIPTION
**Pull request by jonchang**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
Audit failed:

```
==> FAILED
==> Installing or updating 'rubocop' gem
Error: 1 problem in 1 formula
brewsci/bio/phlawd:
  * GitHub fork (not canonical repository)
```

Going to merge this anyway since the canonical repository hasn't been maintained and I maintain the fork.

**Comment by jonchang** [comment]
Gah.

```
brewsci/bio/phlawd:
  * GitHub repository too new (<30 days old)
```

Siri, set a timer for 30 days.

**Comment by sjackman** [comment]
> Going to merge this anyway since the canonical repository hasn't been maintained and I maintain the fork.

> Looks like bottles don't get uploaded if audits fail. I deforked the phlawd repo and rerunning CI now.

Did you defork by deleting and then recreating the repo? Just curious.

**Comment by jonchang** [comment]
Yeah I didn't see any other way to do it. Whatever though this can be merged in like 9 days so I'm not too bummed about it

**Comment by tseemann** [comment]
Nearly 30 days now I think @jonchang !

**Comment by jonchang** [comment]
Alright, let's try it out...

**Comment by sjackman** [comment]
```
❯❯❯ brew desc phlawd
Error: Formulae found in multiple taps: 
       * brewsci/bio/phlawd
       * brewsci/science/phlawd
```
@jonchang Please remove this formula from brewsci/science.
```sh
brew migrate-formula --tap=brewsci/bio brewsci/science/phlawd
```

**Comment by sjackman** [comment]
Ah, there's history. https://github.com/brewsci/homebrew-science/pull/138
54055e3c Revert "phlawd: migrate (#138)"
65179c18 phlawd: migrate (#138)

**Comment by jonchang** [comment]
Whoops fixed

**Pull request closed without merging**
