### PR TITLE
vcflib 1.0.1

### PR DESCRIPTION
**Pull request by tseemann**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by jonchang** [comment]
`version_scheme 1`

**Comment by tseemann** [comment]
Thanks @jonchang  - I didn't know about that tag!
https://www.rubydoc.info/github/Homebrew/brew/Formula.version_scheme=

**Comment by sjackman** [comment]
```
brewsci/bio/vcflib:
  * revision should not decrease (from 2 to 0)
```
https://circleci.com/gh/brewsci/homebrew-bio/7349

My guess is that's a bug in `brew audit`. It's a bit of an edge case that the `version_scheme` increased, the `version` remained identical, and the `revision` decreased.

Note that we usually avoid packaging release candidates like `v1.0.0-rc2`.

**Comment by tseemann** [comment]
@sjackman can you help me to get @ekg to commit to a 1.0.1 release? :)

**Comment by sjackman** [comment]
According to GitHub, you yourself released 1.0.0-rc3! https://github.com/vcflib/vcflib/releases
Want to tag 1.0.1? There's been eight commits to master since 1.0.0.

**Comment by ekg** [comment]
I agree that we should tag 1.0.1

**Comment by tseemann** [comment]
@sjackman yes i know i did :-) but you helped me get @ekg attention and approval now :-P

**Comment by tseemann** [comment]
SUCCESS!

**Comment by sjackman** [comment]
Thanks, Torsten!

**Pull request closed without merging**
