### PR TITLE
canu: Rebuild for gcc on macOS

### PR DESCRIPTION
**Pull request by jpummil**
- [ ] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-bio/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

Fix the error
```
canu: dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib
```
See https://github.com/brewsci/homebrew-bio/issues/283

### CODE REVIEW

**Comment by sjackman** [comment]
Build error on macOS.
```
g++-8 -o /private/tmp/canu-20180522-7501-nkpe2y/canu-1.7/Darwin-amd64/obj/lib/libcanu.a/utgcns/libNDalign/NDalgorithm-allocateMoreSpace.o -c -MD -D_GLIBCXX_PARALLEL -fopenmp -pthread -fPIC -m64 -Wall -Wextra -Wno-write-strings -Wno-unused -Wno-char-subscripts -Wno-sign-compare -Wformat -g3 -O4 -funroll-loops -fexpensive-optimizations -finline-functions -fomit-frame-pointer -DNOBACKTRACE -I/private/tmp/canu-20180522-7501-nkpe2y/canu-1.7/src -IAS_UTL -Istores -Istores/libsnappy -Ialignment -Iutgcns/libNDalign -Iutgcns/libcns -Iutgcns/libpbutgcns -Iutgcns/libNDFalcon -Iutgcns/libboost -Imeryl/libleaff -IoverlapInCore -IoverlapInCore/libedlib -IoverlapInCore/liboverlap -Ifalcon_sense/libfalcon utgcns/libNDalign/NDalgorithm-allocateMoreSpace.C
In file included from utgcns/libNDalign/NDalign.C:39:
AS_UTL/stddev.H: In member function 'std::vector<long long unsigned int>& genericStatistics<TT>::histogram()':
AS_UTL/stddev.H:341:12: error: invalid initialization of non-const reference of type 'std::vector<long long unsigned int>&' from an rvalue of type 'std::vector<long long unsigned int>*'
     return(&_histogram);
```
https://circleci.com/gh/brewsci/homebrew-bio/2679

I'm not sure why Canu built find before but is not building now.

**Comment by jpummil** [comment]
Shaun,
I'm happy to ping Koren, Phillippy, etc. But I'm still curious about my current C++ environment.
```
gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Even though I did a brew install gcc, looks like the CLANG stuff is maintaining its dominance...

**Comment by sjackman** [comment]
The GCC executable installed by `brew` is named `gcc-8`. Try `gcc-8 --version`.

**Comment by sjackman** [comment]
Any progress on this PR, Jeff?

**Comment by sjackman** [comment]
Canu 1.7.1 has been released to hopefully address the build failure on macOS, thanks to @brianwalenz.
https://github.com/marbl/canu/issues/927#issuecomment-398029995

**Comment by sjackman** [comment]
Thanks for submitting this PR, Jeff. Canu 1.7.1 has been released to address the build error that we were seeing with GCC 8.
This PR is superseded by https://github.com/brewsci/homebrew-bio/pull/323

**Pull request closed without merging**
